<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Set up Your Computer for a Keyman Keyboard"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Set up Your Computer for a Keyman Keyboard</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_download-install_keyboard.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_configure_office.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_configure_computer">How To - Set up Your Computer for a Keyman Keyboard</h2></div></div></div><p>Keyman Desktop will automatically set up your computer for best performance with most Keyman keyboards. However, for best performance on some keyboards you may need to manually associate your Keyman keyboard with a Windows language and layout.</p><h3><a name="id543770"></a>Benefits of Association</h3><p>Correctly associating your Keyman keyboard has three main benefits.</p><div class="orderedlist"><ol type="1"><li><p>When a Keyman keyboard and Windows language are correctly associated, turning one on will activate the other. You won't need to adjust both every time you want to use your Keyman keyboard.</p></li><li><p>When a Windows layout and a Keyman keyboard are correctly associated, you can be sure you are using a Keyman keyboard as it was designed. This is especially helpful if you are using a non-English hardware keyboard as your Windows layout. For example, if you are using a Spanish, French, or German hardware keyboard.</p></li><li><p>When a Windows language and a Keyman keyboard are correctly associated, your computer will know which language the keyboard is using. This is helpful for many reasons:</p><div class="itemizedlist"><ul type="disc"><li><p>Applications will know which typing direction to use, left-to-right or right-to-left. This is necessary for right-to-left languages like Arabic, Hebrew, and Farsi.</p></li><li><p>Applications will know how characters and symbols should be rendered. This is partucularly necessary for many Indian languages.</p></li><li><p>Applications will know which language tools to use when spell checking what you type.</p></li></ul></div></li></ol></div><h3><a name="id541643"></a>Association instructions</h3><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>Keyman Desktop allows you to associate multiple Windows languages to a keyboard.</p></div><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Keyboard Layouts tab.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/tab-keyboards.png"></span>
	  </p></li><li><p>Click on the down arrow (<span class="inlinemediaobject"><img src="desktop_images/keyboards-downarrow.png"></span>) beside the keyboard name.</p></li><li><p>Click the <span class="guibutton">Add language</span> button on the left side under 'Languages:'</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/tab-layout.png"></span>
		  </p></li><li><p>From the pop up window, search for the Windows langauge you would like to use and click <span class="guibutton">OK</span></p><p>
        <span class="inlinemediaobject"><img src="desktop_images/language-association.png"></span>
		  </p></li><li><p>To remove an association, hover over the language name, and click the <span class="inlinemediaobject"><img src="desktop_images/icon-uninstall.png"></span> button that appears.</p></li></ol></div><h3><a name="id541767"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_configure_office.php" title="How To - Set up MS Office for a Keyman Keyboard">How To - Set up MS Office for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_font.php" title="How To - Find the Best Fonts for a Keyman Keyboard">How To - Find the Best Fonts for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_rtl.php" title="How To - Type in Right-to-Left Languages">How To - Type in Right-to-Left Languages</a>
      </p></li><li><p>
        <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_download-install_keyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_configure_office.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Download and Install a Keyman Keyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Set up MS Office for a Keyman Keyboard</td></tr></table></div>
