<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Download and Install Keyman Desktop"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Download and Install Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_tutorial.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_download-install_keyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_download-install_keyman">How To - Download and Install Keyman Desktop</h2></div></div></div><h3><a name="id555589"></a>Downloading Keyman Desktop</h3><p>You can download Keyman Desktop with a keyboard for your language from the <a class="ulink" href="https://keyman.com/desktop/" target="_blank">Keyman Website</a>.</p><h3><a name="id555621"></a>Installing Keyman Desktop</h3><p>After you download Keyman Desktop 10.0, to install the program:</p><div class="orderedlist"><ol type="1"><li>Find the Keyman Desktop executable file on your computer. The name of the file begins with 'keymandesktop-10' and ends with '.exe'.</li><li>Double-click the file to begin installation. </li><li><p>You will be asked to allow the installer to access your system. Click <span class="guibutton">Yes</span> to continue.</p><p>
					<span class="inlinemediaobject"><img src="desktop_images/setup-click1.png"></span>
				</p></li><li><p>Once you have read and agree to the license terms, click <span class="guibutton">Install Keyman Desktop</span> to continue.</p><p>
					<span class="inlinemediaobject"><img src="desktop_images/setup-click2.png"></span>
				</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You can select advanced installation options from the Install Options link on the bottom left.</div></li><li><p>At the end of the installation, click <span class="guibutton">Start Keyman Desktop</span> to begin using Keyman or click <span class="guibutton">Take the tour</span> for the Getting Started tutorial.</p><p>
					<span class="inlinemediaobject"><img src="desktop_images/setup-click3.png"></span>
				</p></li></ol></div><p>When you finish your installation of Keyman, you can delete or move the installation's executable file. It doesn't need to remain on your computer for Keyman Desktop to work.</p><h3><a name="id555724"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_uninstall.php" title="Software Task - Uninstall Keyman Desktop">Software Task - Uninstall Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_tutorial.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_download-install_keyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Getting Started with Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Download and Install a Keyman Keyboard</td></tr></table></div>
