<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Set Hotkeys for Keyman Desktop, Keyman Keyboards and Windows Languages"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Set Hotkeys for Keyman Desktop, Keyman Keyboards and Windows Languages</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_locale.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="basic.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_hotkey_set">How To - Set Hotkeys for Keyman Desktop, Keyman Keyboards and Windows Languages</h2></div></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>This feature is only available in Keyman Desktop Professional.</div><p>A hotkey is a keyboard shortcut. In <span class="application">Keyman Desktop</span> these are used to turn on and off Keyman Desktop functions, Keyman keyboards and Windows languages.</p><p>To set the hotkey for a <span class="application">Keyman Desktop</span> function, Keyman keyboard or Windows language:</p><div class="orderedlist"><ol type="1"><li><p>Open Keyman Configuration, from the Keyman menu in the Windows taskbar.</p></li><li><p>Select the Hotkeys tab.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/tab-hotkeys.png"></span>
      </p></li><li><p>Click the hotkey link beside the function, keyboard or language. The Change Hotkey dialog box will be displayed.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/hotkeys-change.png"></span>
      </p></li><li><p>Select a default hotkey or click <span class="guibutton">Custom</span> and type the hotkey you wish to use.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If you press a single letter or <span class="keycap"><strong>Shift</strong></span> plus a single letter, the hotkey will default to <span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>Alt</strong></span> plus the letter you pressed, in order to avoid conflicts with standard keyboard input.</p></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>To clear a hotkey that has been set previously, click <span class="guibutton">Clear Hotkey</span> or press <span class="keycap"><strong>Backspace</strong></span>.</p></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>Be aware that you can set the hotkey to replace common Windows hotkeys (<span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>C</strong></span>, <span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>V</strong></span>, etc).</p></div></li><li><p>Click <span class="guibutton">OK</span> to save your selection.</p></li><li><p>Click <span class="guibutton">OK</span> again from the Configuration window to apply the changes.</p></li></ol></div><p>The new hotkey will now be available.</p><h3><a name="id581523"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Keyman Configuration - Hotkeys Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_locale.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Set the Language for Keyman Desktop Menus </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Chapter 3. Basic Help</td></tr></table></div>
