<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Type in Right-to-Left Languages"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Type in Right-to-Left Languages</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_font.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_locale.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_rtl">How To - Type in Right-to-Left Languages</h2></div></div></div><p>If you will be typing in a right-to-left language (like Arabic, Farsi, Hebrew, or Yiddish) there are three things you should know before you get started.</p><div class="orderedlist"><ol type="1"><li><p>Your computer must be set up for right-to-left language support. Keyman Desktop will automatically set up your computer for most Keyman keyboards that need right-to-left language support. However, you may need to manually adjust your settings for some Keyman keyboards. Otherwise, without right-to-left language support, letters in your right-to-left language might appear in the wrong order, not join correctly, or change after the spacebar is pressed.</p><p>To do this, simply associate the keyboard with a right-to-left Windows language (like Arabic). For instructions on associating a Keyman keyboard with a Windows language, see: <a class="xref" href="start_configure_computer.php" title="How To - Set up Your Computer for a Keyman Keyboard">How To - Set up Your Computer for a Keyman Keyboard</a></p></li><li><p>If you will be using MS Office programs like Word, you should configure MS Office for your right-to-left language. For instructions, see: <a class="xref" href="start_configure_office.php" title="How To - Set up MS Office for a Keyman Keyboard">How To - Set up MS Office for a Keyman Keyboard</a></p></li><li><p>Each time you start typing with a right-to-left Keyman keyboard, you may need to change the typing direction in the program you are using, from left-to-right to right-to-left. In most Windows programs (including MS Word, Internet Explorer, and Notepad), you can use the following shortcuts to switch direction:</p><div class="itemizedlist"><ul type="disc"><li><p>For right-to-left, press: <span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>Right.Shift</strong></span></p></li><li><p>For left-to-right, press: <span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>Left.Shift</strong></span></p></li></ul></div><p>In Firefox:</p><div class="itemizedlist"><ul type="disc"><li><p>To toggle between right-to-left and left-to-right, press: <span class="keycap"><strong>Ctrl</strong></span> + <span class="keycap"><strong>Shift</strong></span> + <span class="keycap"><strong>X</strong></span></p></li></ul></div></li></ol></div><h3><a name="id564441"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_configure_computer.php" title="How To - Set up Your Computer for a Keyman Keyboard">How To - Set up Your Computer for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_configure_office.php" title="How To - Set up MS Office for a Keyman Keyboard">How To - Set up MS Office for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="start_font.php" title="How To - Find the Best Fonts for a Keyman Keyboard">How To - Find the Best Fonts for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_font.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_locale.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Find the Best Fonts for a Keyman Keyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Set the Language for Keyman Desktop Menus</td></tr></table></div>
