<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Fix Font Issues"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Fix Font Issues</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="troubleshooting.php">Prev</a> </td><th width="60%" align="center">Chapter 6. Troubleshooting Index</th><td width="20%" align="right"> <a accesskey="n" href="troubleshooting_sigma.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="troubleshooting_font">How To - Fix Font Issues</h2></div></div></div><p>If you are having font issues, you should first try: <a class="xref" href="start_font.php" title="How To - Find the Best Fonts for a Keyman Keyboard">How To - Find the Best Fonts for a Keyman Keyboard</a></p><h3><a name="id570173"></a>Fix Characters Appearing Smaller than the Selected Font Size</h3><p>If you are typing with a font that does not include all character glyphs, some characters may appear at a smaller size than the selected font size.</p><p>This is due to Windows font-linking -- it automatically selects a different font for those characters when the current font does not contain glyphs for them.</p><p>To correct this problem, select a font which includes glyphs for all the characters you are using.</p><p>EXAMPLE: In Notepad, using the SIL IPA Unicode keyboard, type 'hat_'. With the standard Notepad font selected (Lucida Console) the 't_' appears at a smaller size to the 'ha'.</p><h3><a name="id570194"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_font.php" title="How To - Find the Best Fonts for a Keyman Keyboard">How To - Find the Best Fonts for a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_fonthelper.php" title="Keyman Toolbox - Font Helper">Keyman Toolbox - Font Helper</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="troubleshooting.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="troubleshooting.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="troubleshooting_sigma.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 6. Troubleshooting Index </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Fix Greek Medial Sigma Changing to Final Sigma Unexpectedly in MS Word</td></tr></table></div>
