<?php
  require_once('includes/template.php');

  head([
    'title' => "What's New"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">What's New</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="about_welcome.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman</th><td width="20%" align="right"> <a accesskey="n" href="about_requirements.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="about_whatsnew">What's New</h2></div></div></div><p>Here are some of the great things we have added to Keyman 14.0.</p><div class="itemizedlist"><ul type="disc"><li>Renamed from Keyman Desktop to Keyman for Windows</li><li>Keyman keyboards are no longer hidden from the Windows language picker when you exit Keyman. Rather, if you select a Keyman keyboard, Keyman will be restarted for you automatically.</li><li>Simpler and Smoother Keyboard Search</li><li>Localizable UI through translate.keyman.com</li><li>Added user interface for configuring all Keyman system-level options (#3733)</li><li>Refreshed user interface no longer depends on Internet Explorer (#1720)</li><li>Smoother and more reliable installation of keyboard languages (#3509)</li><li>Choose associated language when keyboard is installed (#3524)</li><li>Much improved keyboard download experience (#3326)</li><li>Improved BCP 47 tag support (#3529)</li><li>Much improved initial download and installation experience including bundled keyboards (#3304)</li><li>Keyman Configuration changes now apply instantly (#3753)</li><li>Improved user experience when many keyboards installed (#3626, #3627)</li><li>Improved bootstrap installer</li><li>Now uses Chromium to host all web-based UI (e.g. Keyman Configuration)</li><li>Breaking change: Keyman Engine no longer supports the keyboard usage page (usage.htm)</li></ul></div><h3><a name="id581221"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="about_history.php" title="Version History">Version History</a>
      </p></li><li><p>
        <a class="xref" href="basic_newways.php" title="New Ways to Use Keyman">New Ways to Use Keyman</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="about_welcome.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="about.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="about_requirements.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Welcome to Keyman </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> System Requirements</td></tr></table></div>
