<?php
  require_once('includes/template.php');

  head([
    'title' => "Welcome to Keyman Desktop 10.0"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Welcome to Keyman Desktop 10.0</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="about.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman Desktop</th><td width="20%" align="right"> <a accesskey="n" href="about_whatsnew.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="about_welcome">Welcome to Keyman Desktop 10.0</h2></div></div></div><p>Thank you for installing Keyman Desktop 10.0. Whether you're a new or returning user, we believe you will appreciate the significant enhancements in this latest version of Keyman Desktop.</p><p>We've added many new features to our market-leading keyboard application and our redesigned Keyman Desktop Help should assist you in getting around.</p><h3><a name="id560146"></a>What is Keyman Desktop?</h3><p>Keyman Desktop is a keyboard application that makes it easy for you to type in your language in all your favourite Windows programs and across the Web. Keyman Desktop is used by more than a million people to type in over 1000 languages and counting.</p><p>Keyman Desktop remaps your hardware keyboard to any one of hundreds of virtual keyboards, available for download from the <a class="ulink" href="https://www.keyman.com/" target="_blank">Keyman Website</a> and around the Web. If you cannot find a keyboard for your language, we offer the companion application <a class="ulink" href="https://keyman.com/developer/" target="_blank">Keyman Developer</a>. Keyman Developer is a powerful software solution for creating the perfect Keyman keyboard to suit your needs.</p><p>Keyman Desktop features seamless integration with your Windows operating system and the Windows language bar. You can use Keyman keyboards with Keyman Desktop in almost any Windows or Web application. Try it in office software like Word or Excel; browsers like Firefox or Internet Explorer; design programs like Adobe InDesign; and email services like Outlook or Gmail.</p><p>Keyman Desktop fully supports <a class="ulink" href="http://www.unicode.org/" target="_blank">Unicode</a> and legacy standards and can be used with all standard hardware keyboards, making it the perfect solution for typing in any language on your computer.</p><p>A list of features in Keyman Desktop 10.0 is available <a class="link" href="about_whatsnew.php" title="What's New">here</a>.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/osk_keyboard.png"></span>
  </p><h3><a name="id560193"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
    <a class="xref" href="about_whatsnew.php" title="What's New">What's New</a>
   </p></li><li><p>
    <a class="xref" href="about_requirements.php" title="System Requirements">System Requirements</a>
   </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="about.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="about.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="about_whatsnew.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 1. About Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> What's New</td></tr></table></div>
