<?php
  require_once('includes/template.php');

  head([
    'title' => "New Ways to Use Keyman"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">New Ways to Use Keyman</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_update.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_newways">New Ways to Use Keyman</h2></div></div></div><p>If you are an existing user of Keyman, you will notice that some parts of the program have changed. This 
  topic describes some of the new ways you can or should access some of Keyman's features. These changes have been 
  implemented as part of enhancing how Keyman integrates with modern versions of Windows.</p><p>Keyman Configuration no longer requires you to click the <span class="guibutton">OK</span> to save changes. All changes are applied instantly.</p><p>Keyman keyboards are no longer hidden from the Windows language picker when you exit Keyman. Rather, if you select a Keyman keyboard, Keyman will be restarted for you automatically.</p><p>The key change in your usage will be how you access keyboard layouts. With version 9.0 and later, all keyboard layouts are
  registered as Windows Text Services, and are always available through Windows language interfaces as well as with the
  <a class="link" href="basic_traymenu.php" title="The Keyman Menu">Keyman menu</a>, 
  <a class="link" href="basic_languageswitcher.php" title="Language Switcher">language switcher</a> and 
  <a class="link" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">hotkeys</a>.</p><p><a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a></p><p>Most of the following changes were made in Keyman 10.0</p><p>When you install a keyboard layout, it will be registered under the language for which the keyboard has been designed,
  or if this has not been specified by the keyboard designer, then it will be installed under your default language. You can
  always change the language registration in the <a class="link" href="basic_keyboards_tab.php" title="Keyman Configuration - Keyboard Layouts Tab">Keyboards tab</a>.</p><p>In earlier versions of Keyman, language association was controlled in the Languages tab in Keyman Configuration.
  With the new model of keyboard registration, all language association is controlled in the Keyboards tab. Each keyboard can be associated with multiple languages.</p><p>The keyboard menu now shows all Windows languages and keyboards, and not just Keyman keyboards. This reflects the tight integration
  with Windows languages that Keyman 10+ provides.</p><p>You may be using a non-US hardware keyboard, which we call the Base Layout.  For example, you may be using a French, or German, or
  other European Latin-script keyboard.  You can change the base layout in the Options tab, which will allow Keyman to automatically
  generate new versions of your keyboards that adapt to your base layout.</p><h3><a name="id592094"></a>Other Minor Changes</h3><div class="itemizedlist"><ul type="disc"><li><p>In the Support tab, we have reorganised the support and diagnostics links.</p></li></ul></div><div class="itemizedlist"><ul type="disc"><li><p>The Addins tab has been eliminated as it is no longer required.</p></li></ul></div><div class="itemizedlist"><ul type="disc"><li><p>A number of obsolete options have been removed.</p></li></ul></div><div class="itemizedlist"><ul type="disc"><li><p>The proxy settings dialog is now accessed through the Options tab.</p></li></ul></div><h3><a name="id592112"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="about_whatsnew.php" title="What's New">What's New</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_update.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 3. Basic Help </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Software Task - Update Keyman</td></tr></table></div>
