<?php
  require_once('includes/template.php');

  head([
    'title' => "The Keyman Desktop Text Editor"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">The Keyman Desktop Text Editor</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_languageswitcher.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_config_menu.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_text_editor">The Keyman Desktop Text Editor</h2></div></div></div><p>The Keyman Text Editor is a basic text editor for testing your Keyman keyboards.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/texteditor.png"></span>
  </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You do not need to use the Keyman Text Editor to type with Keyman Desktop. You can use Keyman Desktop in almost any application on your computer that accepts keyboard input.</div><h3><a name="id565967"></a>Opening the Text Editor</h3><p>To open the Keyman Text Editor:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Text Editor…</span>.</p></li></ol></div><h3><a name="id565991"></a>Using the Text Editor</h3><p>To use the Keyman Text Editor:</p><div class="orderedlist"><ol type="1"><li><p>Open Text Editor.</p></li><li><p>Turn on a Keyman keyboard.</p></li><li><p>Start typing.</p></li></ol></div><p>When you select a Unicode Keyman keyboard, the Text Editor brings up a font panel. This font panel behaves like the <a class="link" href="basic_fonthelper.php" title="Keyman Toolbox - Font Helper">Font Helper tool</a> in the Keyman Toolbox. Each font listed in the panel includes a percentage value.  This value indicates how many characters in the current Keyman keyboard are available from the font.  Most of the time, fonts with greater than 90% coverage will work for nearly all texts.</p><p>You can select a font from the font dropdown menu or by clicking on the link for the font in the font panel.</p><h3><a name="id566041"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_tutorial.php" title="Getting Started with Keyman Desktop">Getting Started with Keyman Desktop</a>
      </p></li><li><p>
        <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_languageswitcher.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_config_menu.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Language Switcher </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Desktop Configuration</td></tr></table></div>
