<?php
  require_once('includes/template.php');

  head([
    'title' => "The Keyman Desktop Help Menu"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">The Keyman Desktop Help Menu</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_support_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="advanced.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_help">The Keyman Desktop Help Menu</h2></div></div></div><p>The Keyman Desktop Help menu gives you comprehensive help for every aspect of Keyman Desktop.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>All of the help available through the Keyman Desktop Help menu is also available online through the <a class="ulink" href="http://help.keyman.com/products/desktop/10.0/" target="_blank">Help Documentation</a> section of the Keyman Desktop help site.</div><h3><a name="id570066"></a>Opening Help</h3><p>To open Keyman Desktop Help:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Help…</span>.</p></li><li><p>Select Help Contents.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/help-dialog.png"></span>
  </p></li></ol></div><h3><a name="id570624"></a>Using Help</h3><p>Keyman Desktop Help is divided into seven sections:</p><div class="orderedlist"><ol type="1"><li><p>About Keyman Desktop — Provides general information and licensing details about the current version of Keyman Desktop.</p></li><li><p>Getting Started — Includes all the help you need to start using Keyman Desktop quickly.</p></li><li><p>Basic Help — Gives a detailed overview of all of the basic features of Keyman Desktop.</p></li><li><p>Advanced Help — Gives an overview of more advanced Keyman Desktop features.</p></li><li><p>Common Questions — Includes a selection of the most frequently asked questions.</p></li><li><p>Troubleshooting Index — Provides reference guides for specific issues.</p></li><li><p>Context Help — Links context-sensitive help (accesible throughout Keyman Desktop using <span class="keycap"><strong>F1</strong></span>) to the correct help topics.</p></li></ol></div><h3><a name="id570704"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_tutorial.php" title="Getting Started with Keyman Desktop">Getting Started with Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_support_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="advanced.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Support Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Chapter 4. Advanced Help</td></tr></table></div>
