<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Toolbox - Font Helper"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Toolbox - Font Helper</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_usage.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_charactermap.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_fonthelper">Keyman Toolbox - Font Helper</h2></div></div></div><p>The Font Helper tool in the <a class="link" href="basic_toolbox.php" title="The Keyman Desktop Toolbox">Keyman Toolbox</a> identifies fonts on your system that should work with the currently selected keyboard layout.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/fonthelper.png"></span>
  </p><h3><a name="id579073"></a>Opening the Font Helper</h3><p>To open the Font Helper:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Font Helper</span>.</p></li></ol></div><h3><a name="id579111"></a>Using the Font Helper</h3><p>To use the Font Helper:</p><div class="orderedlist"><ol type="1"><li><p>Turn on a Keyman keyboard.</p></li><li><p>Open the Font Helper.</p></li></ol></div><p>Each font listed in the Font Helper includes a percentage value.  This value indicates how many characters in the current Keyman Desktop keyboard are available from the font.  Most of the time, fonts with greater than 90% coverage will work for nearly all texts.</p><p>In addition to percentage values, Keyman Desktop also includes a complete Character Chart with all the keyboard characters supported by the font. The Character Chart will allow you to see exactly which characters your font supports. It will also allow you to see how the same characters look in different fonts.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>If no fonts are listed in the Font Helper, check the documentation of the keyboard layout to see if it includes information on where to obtain the fonts you need.</div><h3><a name="id579142"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
    <a class="xref" href="basic_toolbox.php" title="The Keyman Desktop Toolbox">The Keyman Desktop Toolbox</a>
   </p></li><li><p>
    <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
   </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_usage.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_charactermap.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Toolbox - Keyboard Usage </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Toolbox - Character Map</td></tr></table></div>
