<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Configuration - Support Tab"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Support Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_support_tab">Keyman Configuration - Support Tab</h2></div></div></div><p>The Support tab of Keyman Configuration displays Keyman Desktop version information and support tools. You can use the Support tab to send a support request, check Windows language settings, check for updates, and view Keyman Desktop version information.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/tab-support.png"></span>
  </p><h3><a name="id596830"></a>Opening the Support Tab</h3><p>To open the Support tab of Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Support tab.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Keyman Configuration opens in the same tab you last closed it in.</div></li></ol></div><h3><a name="id596891"></a>Collecting Diagnostic Information</h3><p>You can collect diagnostic information about Keyman by clicking the 'Diagnostics' link under the 'Useful Links' section. The support diagnostic will collect critical diagnostic information from your computer and generate a report.</p><h3><a name="id596892"></a>Checking for Updates</h3><p>To check for Keyman Desktop updates, from the Support tab of Keyman Configuration click the 'Check for Updates' link. You can also download and install Keyman Desktop again from the Keyman website.</p><h3><a name="id596897"></a>About Version Information</h3><p>You can view version details from the Support tab of Keyman Configuration. In the Support tab you will see:</p><div class="itemizedlist"><ul type="disc"><li>Version Detals
    <div class="itemizedlist"><ul type="circle"><li><p>Edition — Details on your current edition of Keyman Desktop.</p></li><li><p>Version — The current Keyman Desktop version number</p></li></ul></div></li></ul></div><h3><a name="id596923"></a>Accessing the Keyman Community</h3><p><a class="ulink" href="https://community.software.sil.org/c/keyman" target="_blank">Keyman Community</a> </p><div class="itemizedlist"><ul type="disc"><li><p>Click the <span class="guibutton">Open Keyman Community</span> button. The forums will open in your internet browser. You will need to have internet access for this to open successfully.</p></li></ul></div><h3><a name="id597281"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman Desktop">How To - Download and Install Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Hotkeys Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The Keyman Desktop Help Menu</td></tr></table></div>
