<?php
  require_once('includes/template.php');

  head([
    'title' => "Getting Started with Keyman"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Getting Started with Keyman</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_download-install_keyman.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_tutorial">Getting Started with Keyman</h2></div></div></div><p>Follow these steps for a basic introduction to Keyman:</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><span class="application">Keyman</span> must be installed first. For help on installing <span class="application">Keyman</span>, please see: <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman">How To - Download and Install Keyman</a>.</div><h3><a name="id557749"></a>Step 1</h3><span class="inlinemediaobject"><img src="desktop_images/start_tray.png"></span><p>Check the Windows Taskbar near the clock to see if Keyman is running. If it is running you will see the Keyman icon: <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span></p><h3><a name="id557799"></a><a name="tutorial_step2"></a>Step 2</h3><p>If the Keyman icon is in the Windows Taskbar near the clock, continue on to <a class="link" href="start_tutorial.php#tutorial_step5">Step 5</a>.</p><p>
				<span class="inlinemediaobject"><img src="desktop_images/start_tray.png"></span>
			</p><p>If the Keyman icon is not on the Windows Taskbar near the clock, click the arrow or triangle next to the clock:</p><div class="itemizedlist"><ul type="disc"><li><p>You will see a collection of icons. If the Keyman icon (<span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>) is not in this collection, Keyman is not running. Read steps 3 and 4 to learn how to start Keyman.</p></li><li><p>If the Keyman icon is in this collection, you should move it permanently to the Windows Taskbar. Here's how:</p><div class="itemizedlist"><ul type="circle"><li><p>On Windows 7:</p><div class="orderedlist"><ol type="1"><li><p>Open the Windows Start menu.</p></li><li><p>In the search field, type and enter: Notification Area Icons</p></li><li><p>From the dropdown menu beside SIL International Keyman Engine x86, select 'Show icon and notifications'.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/7-taskbar.png"></span>
												</p></li><li><p>Click <span class="guibutton">OK</span> to apply changes. The Keyman icon will now always appear in the Windows Taskbar near the clock, if Keyman is on.</p></li><li><p>Continue on to <a class="link" href="start_tutorial.php#tutorial_step5">Step 5</a> of this guide.</p></li></ol></div></li><li><p>On Windows 8:</p><div class="orderedlist"><ol type="1"><li><p>Right-click on the Windows Taskbar.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win8-taskbar1.png"></span>
												</p></li><li><p>Select 'Properties'.</p></li><li><p>Next to 'Notification area', click <span class="guibutton">Customize…</span>.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win8-taskbar2.png"></span>
												</p></li><li><p>From the dropdown menu beside SIL International Keyman Engine x86, select 'Show icon and notifications'.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win8-taskbar3.png"></span>
												</p></li><li><p>Click <span class="guibutton">OK</span> to apply changes. The Keyman icon will now always appear in the Windows Taskbar near the clock, if Keyman is on.</p></li><li><p>Continue on to <a class="link" href="start_tutorial.php#tutorial_step5">Step 5</a> of this guide.</p></li></ol></div></li><li><p>On Windows 10</p><div class="orderedlist"><ol type="1"><li><p>Right-click on the Windows Taskbar.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win10-taskbar1.png"></span>
												</p></li><li><p>Select 'Taskbar settings'.</p></li><li><p>Under 'Notification area', click on 'Select which icons appear on the taskbar'</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win10-taskbar2.png"></span>
												</p></li><li><p>From the toggle button beside 'SIL International Keyman Engine x86', click to turn it on.</p><p>
													<span class="inlinemediaobject"><img src="desktop_images/win10-taskbar3.png"></span>
												</p></li><li><p>The Keyman icon will now always appear in the Windows Taskbar near the clock, if Keyman is on.</p></li><li><p>Continue on to <a class="link" href="start_tutorial.php#tutorial_step5">Step 5</a> of this guide.</p></li></ol></div></li></ul></div></li></ul></div><h3><a name="id567665"></a>Step 3</h3><p>To Start Keyman, click on the Windows Start Menu, select All Programs, and select Keyman.</p><h3><a name="id567668"></a>Step 4</h3><span class="inlinemediaobject"><img src="desktop_images/start_tray.png"></span><p>Keyman will now be running and the Keyman icon will be on the Windows Taskbar near the clock.</p><h3><a name="id567708"></a><a name="tutorial_step5"></a>Step 5</h3><p>Open a typing application, like Microsoft Word.</p><h3><a name="id567695"></a>Step 6</h3><span class="inlinemediaobject"><img src="desktop_images/menu.png"></span><p>Select a Keyman keyboard from the Keyman menu. You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>If there are no Keyman keyboards in the Keyman menu, you can learn how to install one here: <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a></div><h3><a name="id567731"></a>Step 7</h3><span class="inlinemediaobject"><img src="desktop_images/osk-tibetan.png"></span><p>To learn how to type with your new Keyman keyboard, open the On Screen Keyboard tool of the Keyman Toolbox. You can open the On Screen Keyboard tool from the On Screen Keyboard link in the Keyman menu.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Some Keyman keyboards do not include an On Screen Keyboard. You can usually find help for these keyboards from the Keyboard Usage tool of the Keyman Toolbox. You can open the Keyboard Usage tool from the Keyboard Usage link in the Keyman menu.</div><h3><a name="id567740"></a>Step 8</h3><p>You can now start typing in your language in almost any application.  Use your hardware keyboard or click the On Screen Keyboard keys to type.</p><h3><a name="id567773"></a>Step 9</h3><p>To return to using your normal keyboard, open the Keyman menu and click 'Switch Keyman Off'.</p><h3><a name="id567781"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman">How To - Download and Install Keyman</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_download-install_keyman.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 2. Getting Started </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Download and Install Keyman</td></tr></table></div>
