<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Set the Language for Keyman Desktop Menus"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Set the Language for Keyman Desktop Menus</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_rtl.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_hotkey_set.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_locale">How To - Set the Language for Keyman Desktop Menus</h2></div></div></div><h3><a name="id558539"></a>Setting a Language for Keyman Desktop Menus</h3><p>If you would like the menus in Keyman Desktop to be in a language other than English: </p><div class="orderedlist"><ol type="1"><li><p>Open Keyman Configuration, from the Keyman menu in the Windows taskbar.</p></li><li><p>Click <span class="guibutton">English</span> in the 'Display in:' menu on the top right corner.</p><p>
			<span class="inlinemediaobject"><img src="desktop_images/config-locale.png"></span>
		</p></li><li><p>Select your language from the list. If your language is not in the list, click <span class="guibutton">Find other display languages online…</span>.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>If your language is not available online, you can write your own translation for your language using our locale editor. For more information, see <a class="xref" href="advanced_locale_edit.php" title="Translating the Keyman for Windows User Interface">Translating the Keyman for Windows User Interface</a>.</div></li><li><p>Restart Keyman Desktop for the language changes to take effect for the entire program.</p></li></ol></div><h3><a name="id559796"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="advanced_locale_edit.php" title="Translating the Keyman for Windows User Interface">Translating the Keyman for Windows User Interface</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_rtl.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_hotkey_set.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Type in Right-to-Left Languages </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Set Hotkeys for Keyman Desktop, Keyman Keyboards and Windows Languages</td></tr></table></div>
