<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Fix A Problem with an Active Keyman Keyboard Not Typing"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Fix A Problem with an Active Keyman Keyboard Not Typing</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="troubleshooting_bootstrapper.php">Prev</a> </td><th width="60%" align="center">Chapter 6. Troubleshooting Index</th><td width="20%" align="right"> <a accesskey="n" href="context.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="troubleshooting_hidden">How To - Fix A Problem with an Active Keyman Keyboard Not Typing</h2></div></div></div><h3><a name="id601545"></a>Symptoms</h3><p>You may experience an issue in Windows 7 where:</p><div class="itemizedlist"><ul type="disc"><li>Keyman Desktop is on; and</li><li>your Keyman keyboard is active, with its icon showing in the Keyman menu; but</li><li>your Keyman keyboard does not work.</li></ul></div><h3><a name="id601675"></a>Resolution</h3><p>Unhide the Keyman Desktop menu as described in <a class="link" href="start_tutorial.php#tutorial_step2">Step 2</a> of the Getting Started tutorial.</p><p>This can also be resolved by switching language using the Windows Language Bar or the Language Icon</p><h3><a name="id601706"></a>Background</h3><p>When the Keyman icon is in the hidden notification area of the Windows taskbar, opening the notification area and selecting the icon causes it to change the keyboard for the taskbar, not for your active application. Clicking back to the active application results in the keyboard turning off again.</p><h3><a name="id601723"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="troubleshooting_bootstrapper.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="troubleshooting.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Use the Keyman Desktop Setup Bootstrapper </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Chapter 7. Context Help</td></tr></table></div>
