<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanAddinsInstalled::Install"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanAddinsInstalled::Install</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanAddinsInstalled.php">Prev</a> </td><th width="60%" align="center">IKeymanAddinsInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddinsInstalled_Items.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanAddinsInstalled_Install"><a class="link" href="comapi_interface_IKeymanAddinsInstalled.php" title="IKeymanAddinsInstalled Interface">IKeymanAddinsInstalled</a>::Install</h5></div></div></div><p>
            Install a .kma addin (optionally bundled in a .kmp package).  New addins should be distributed as .msi or .msm.  This
            function may be deprecated in a future version of Keyman.
          </p><h6><a name="id667197"></a>Declaration</h6><pre class="programlisting">Sub Install(Filename As String, Force As Boolean)</pre><h6><a name="id667203"></a>Parameters</h6><table id="id667205"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr><tr><td>1</td><td>Filename</td><td>String</td><td>Full pathname to the .kma addin file or .kmp package containing a .kma addin file</td></tr><tr><td>2</td><td>Force</td><td>Boolean</td><td>Not currently used.  Use FALSE</td></tr></table><h6><a name="id667239"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanAddinsInstalled.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanAddinsInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddinsInstalled_Items.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanAddinsInstalled Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanAddinsInstalled::Items</td></tr></table></div>
