<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboard::KeyboardName"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboard::KeyboardName</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_Hotkey.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboard Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_LayoutType.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboard_KeyboardName"><a class="link" href="comapi_interface_IKeymanKeyboard.php" title="IKeymanKeyboard Interface">IKeymanKeyboard</a>::KeyboardName</h5></div></div></div><p>
            Returns the name of the keyboard as defined in the keyboard file.
          </p><h6><a name="id627740"></a>Declaration</h6><pre class="programlisting">Property Get KeyboardName As String</pre><h6><a name="id627746"></a>Parameters</h6><table id="id627748"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id627760"></a>Return Value</h6>String<h6><a name="id627764"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_Hotkey.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboard.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_LayoutType.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboard::Hotkey </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboard::LayoutType</td></tr></table></div>
