<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageSubFile::Filename"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageSubFile::Filename</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile_Description.php">Prev</a> </td><th width="60%" align="center">IKeymanPackageSubFile Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_FileType.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackageSubFile_Filename"><a class="link" href="comapi_interface_IKeymanPackageSubFile.php" title="IKeymanPackageSubFile Interface">IKeymanPackageSubFile</a>::Filename</h5></div></div></div><p>
            Returns the name of the file (without path information).
          </p><h6><a name="id609302"></a>Declaration</h6><pre class="programlisting">Property Get Filename As String</pre><h6><a name="id609308"></a>Parameters</h6><table id="id609310"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id609322"></a>Return Value</h6>String<h6><a name="id609326"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile_Description.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackageSubFile.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_FileType.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackageSubFile::Description </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageSubFile::FileType</td></tr></table></div>
