<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageFile::SubFiles"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageFile::SubFiles</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageFile_ReadMe.php">Prev</a> </td><th width="60%" align="center">IKeymanPackageFile Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackageFile_SubFiles"><a class="link" href="comapi_interface_IKeymanPackageFile.php" title="IKeymanPackageFile Interface">IKeymanPackageFile</a>::SubFiles</h5></div></div></div><p>
            Returns a collection of all the files in the package.
          </p><h6><a name="id602702"></a>Declaration</h6><pre class="programlisting">Property Get SubFiles As IKeymanPackageSubFiles</pre><h6><a name="id602708"></a>Parameters</h6><table id="id602710"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id602722"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanPackageSubFiles.php" title="IKeymanPackageSubFiles Interface">IKeymanPackageSubFiles</a><h6><a name="id609079"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageFile_ReadMe.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackageFile.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackageFile::ReadMe </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageSubFile Interface</td></tr></table></div>
