<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboard::Message"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboard::Message</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_LayoutType.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboard Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_Name.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboard_Message"><a class="link" href="comapi_interface_IKeymanKeyboard.php" title="IKeymanKeyboard Interface">IKeymanKeyboard</a>::Message</h5></div></div></div><p>
            Returns the message string from the keyboard.  This will commonly be the usage terms or information about the keyboard design.
          </p><h6><a name="id627824"></a>Declaration</h6><pre class="programlisting">Property Get Message As String</pre><h6><a name="id627830"></a>Parameters</h6><table id="id627832"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id627844"></a>Return Value</h6>String<h6><a name="id627848"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_LayoutType.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboard.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_Name.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboard::LayoutType </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboard::Name</td></tr></table></div>
