<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackage::Keyboards"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackage::Keyboards</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Filename.php">Prev</a> </td><th width="60%" align="center">IKeymanPackage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage_Name.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackage_Keyboards"><a class="link" href="comapi_interface_IKeymanPackage.php" title="IKeymanPackage Interface">IKeymanPackage</a>::Keyboards</h5></div></div></div><p>
            Returns a collection of all the keyboards that are included in the package
          </p><h6><a name="id602222"></a>Declaration</h6><pre class="programlisting">Property Get Keyboards As IKeymanKeyboardsPackage</pre><h6><a name="id602228"></a>Parameters</h6><table id="id602230"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id602242"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanKeyboardsPackage.php" title="IKeymanKeyboardsPackage Interface">IKeymanKeyboardsPackage</a><h6><a name="id602248"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Filename.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage_Name.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackage::Filename </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackage::Name</td></tr></table></div>
