<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanOptions::Items"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanOptions::Items</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOptions_Apply.php">Prev</a> </td><th width="60%" align="center">IKeymanOptions Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanOptions_Items"><a class="link" href="comapi_interface_IKeymanOptions.php" title="IKeymanOptions Interface">IKeymanOptions</a>::Items</h5></div></div></div><p>
            Returns a KeymanOption from the collection
          </p><h6><a name="id601729"></a>Declaration</h6><pre class="programlisting">Property Get Items(Index) As IKeymanOption</pre><h6><a name="id601735"></a>Parameters</h6><table id="id601737"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr><tr><td>1</td><td>Index</td><td>Variant</td><td>1-based index of the KeymanOption to return</td></tr></table><h6><a name="id601760"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanOption.php" title="IKeymanOption Interface">IKeymanOption</a><h6><a name="id601766"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOptions_Apply.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanOptions.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanOptions::Apply </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanOption Interface</td></tr></table></div>
