<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanOption::Value"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanOption::Value</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOption_Name.php">Prev</a> </td><th width="60%" align="center">IKeymanOption Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanOption_Value"><a class="link" href="comapi_interface_IKeymanOption.php" title="IKeymanOption Interface">IKeymanOption</a>::Value</h5></div></div></div><p>
            Gets or sets the current value for the option.  After changing Value, you must Apply the changes with TavultesoftKeyman.Options.Apply.
          </p><h6><a name="id602029"></a>Declaration</h6><pre class="programlisting">Property Get/Let Value As Boolean</pre><h6><a name="id602035"></a>Parameters</h6><table id="id602037"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id602049"></a>Return Value</h6>Boolean<h6><a name="id602053"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOption_Name.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanOption.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanOption::Name </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackage Interface</td></tr></table></div>
