<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboard::Copyright"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboard::Copyright</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_Bitmap.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboard Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_Encodings.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboard_Copyright"><a class="link" href="comapi_interface_IKeymanKeyboard.php" title="IKeymanKeyboard Interface">IKeymanKeyboard</a>::Copyright</h5></div></div></div><p>
            Returns the copyright string from the keyboard
          </p><h6><a name="id627574"></a>Declaration</h6><pre class="programlisting">Property Get Copyright As String</pre><h6><a name="id627580"></a>Parameters</h6><table id="id627582"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id627594"></a>Return Value</h6>String<h6><a name="id627598"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboard_Bitmap.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboard.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard_Encodings.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboard::Bitmap </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboard::Encodings</td></tr></table></div>
