<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardInstalled::Uninstall"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardInstalled::Uninstall</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_OwnerProduct.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_VisualKeyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardInstalled_Uninstall"><a class="link" href="comapi_interface_IKeymanKeyboardInstalled.php" title="IKeymanKeyboardInstalled Interface">IKeymanKeyboardInstalled</a>::Uninstall</h5></div></div></div><p>
            Uninstalls the keyboard.  If the keyboard was InstalledByAdmin then the keyboard must be uninstalled by an administrator.
          </p><h6><a name="id628401"></a>Declaration</h6><pre class="programlisting">Sub Uninstall</pre><h6><a name="id628407"></a>Parameters</h6><table id="id628409"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id628421"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_OwnerProduct.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_VisualKeyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardInstalled::OwnerProduct </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardInstalled::VisualKeyboard</td></tr></table></div>
