<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanError::Severity"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanError::Severity</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanError_ParameterValue.php">Prev</a> </td><th width="60%" align="center">IKeymanError Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanError_Severity"><a class="link" href="comapi_interface_IKeymanError.php" title="IKeymanError Interface">IKeymanError</a>::Severity</h5></div></div></div><p>
            Returns the severity of the error.  Can be: kesFatal, kesError, kesWarning or kesHint.
          </p><h6><a name="id627368"></a>Declaration</h6><pre class="programlisting">Property Get Severity As KeymanErrorSeverity</pre><h6><a name="id627374"></a>Parameters</h6><table id="id627376"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id627388"></a>Return Value</h6>KeymanErrorSeverity<h6><a name="id627392"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanError_ParameterValue.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanError.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanError::ParameterValue </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboard Interface</td></tr></table></div>
