<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageInstalled Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageInstalled Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Name.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageInstalled_InstalledByAdmin.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanPackageInstalled">IKeymanPackageInstalled Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanPackageInstalled_InstalledByAdmin.php">IKeymanPackageInstalled::InstalledByAdmin</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanPackageInstalled_Uninstall.php">IKeymanPackageInstalled::Uninstall</a></span></dt></dl></div><p>
        interface IKeymanPackageInstalled : 
        <a class="link" href="comapi_interface_IKeymanPackage.php" title="IKeymanPackage Interface">IKeymanPackage</a> : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p></p><h5><a name="id602313"></a>Interface Methods</h5><table id="id602315"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageInstalled_Uninstall.php" title="IKeymanPackageInstalled::Uninstall">Uninstall</a></td><td>Method</td><td>Sub Uninstall(RemoveFonts As Boolean)</td></tr></table><h5><a name="id602336"></a>Interface Properties</h5><table id="id602338"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageInstalled_InstalledByAdmin.php" title="IKeymanPackageInstalled::InstalledByAdmin">InstalledByAdmin</a></td><td>Property Get</td><td>Property Get InstalledByAdmin As Boolean</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Name.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageInstalled_InstalledByAdmin.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackage::Name </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageInstalled::InstalledByAdmin</td></tr></table></div>
