<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageSubFile Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageSubFile Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageFile_SubFiles.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_AsStream.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanPackageSubFile">IKeymanPackageSubFile Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanPackageSubFile_AsStream.php">IKeymanPackageSubFile::AsStream</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php">IKeymanPackageSubFile::CopyLocation</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanPackageSubFile_Description.php">IKeymanPackageSubFile::Description</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanPackageSubFile_Filename.php">IKeymanPackageSubFile::Filename</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanPackageSubFile_FileType.php">IKeymanPackageSubFile::FileType</a></span></dt></dl></div><p>
        interface IKeymanPackageSubFile : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>
        A file extracted from a KeymanPackageFile.  These files are available for referencing before a package is installed
      </p><h5><a name="id609099"></a>Interface Properties</h5><table id="id609101"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageSubFile_AsStream.php" title="IKeymanPackageSubFile::AsStream">AsStream</a></td><td>Property Get</td><td>Property Get AsStream As Unknown</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php" title="IKeymanPackageSubFile::CopyLocation">CopyLocation</a></td><td>Property Get</td><td>Property Get CopyLocation As tagKeymanPackageSubFileCopyLocation</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageSubFile_Description.php" title="IKeymanPackageSubFile::Description">Description</a></td><td>Property Get</td><td>Property Get Description As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageSubFile_FileType.php" title="IKeymanPackageSubFile::FileType">FileType</a></td><td>Property Get</td><td>Property Get FileType As tagKeymanFileType</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanPackageSubFile_Filename.php" title="IKeymanPackageSubFile::Filename">Filename</a></td><td>Property Get</td><td>Property Get Filename As String</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageFile_SubFiles.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_AsStream.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackageFile::SubFiles </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageSubFile::AsStream</td></tr></table></div>
