<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanLanguage::LayoutName"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanLanguage::LayoutName</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_KeymanKeyboard.php">Prev</a> </td><th width="60%" align="center">IKeymanLanguage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_LocaleName.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanLanguage_LayoutName"><a class="link" href="comapi_interface_IKeymanLanguage.php" title="IKeymanLanguage Interface">IKeymanLanguage</a>::LayoutName</h5></div></div></div><p>
            Returns the name of the Windows keyboard layout/IME that is associated with the language.
          </p><h6><a name="id614178"></a>Declaration</h6><pre class="programlisting">Property Get LayoutName As String</pre><h6><a name="id614184"></a>Parameters</h6><table id="id614187"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id614199"></a>Return Value</h6>String<h6><a name="id614202"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_KeymanKeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanLanguage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_LocaleName.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanLanguage::KeymanKeyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanLanguage::LocaleName</td></tr></table></div>
