<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanSystemInfo::RunDiagnostics"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanSystemInfo::RunDiagnostics</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_Refresh.php">Prev</a> </td><th width="60%" align="center">IKeymanSystemInfo Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanSystemInfo_RunDiagnostics"><a class="link" href="comapi_interface_IKeymanSystemInfo.php" title="IKeymanSystemInfo Interface">IKeymanSystemInfo</a>::RunDiagnostics</h5></div></div></div><p>
            Start the Tavultesoft System Diagnostics tool included in Keyman Engine 7.0.
          </p><h6><a name="id610095"></a>Declaration</h6><pre class="programlisting">Sub RunDiagnostics</pre><h6><a name="id610101"></a>Parameters</h6><table id="id610103"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id610115"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_Refresh.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanSystemInfo.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanSystemInfo::Refresh </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanVisualKeyboard Interface</td></tr></table></div>
