<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardInstalled::Loaded"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardInstalled::Loaded</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_KeymanID.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_OwnerPackage.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardInstalled_Loaded"><a class="link" href="comapi_interface_IKeymanKeyboardInstalled.php" title="IKeymanKeyboardInstalled Interface">IKeymanKeyboardInstalled</a>::Loaded</h5></div></div></div><p>
            Returns True if the keyboard is currently loaded for use.  If False, then the keyboard is still installed in the system,
            but will not be selectable by the user.
          </p><h6><a name="id628274"></a>Declaration</h6><pre class="programlisting">Property Get/Let Loaded As Boolean</pre><h6><a name="id628280"></a>Parameters</h6><table id="id628282"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id628294"></a>Return Value</h6>Boolean<h6><a name="id628298"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_KeymanID.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_OwnerPackage.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardInstalled::KeymanID </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardInstalled::OwnerPackage</td></tr></table></div>
