<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanControl::StopKeyman32Engine"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanControl::StopKeyman32Engine</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_StartVisualKeyboard.php">Prev</a> </td><th width="60%" align="center">IKeymanControl Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_StopVisualKeyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanControl_StopKeyman32Engine"><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a>::StopKeyman32Engine</h5></div></div></div><p>
            Stops the Keyman32.dll engine for the specified product.  Used by Keyman Controllers, not by client applications.  If you are trying to stop a specific product, use IKeymanProduct.Stop instead.
          </p><h6><a name="id600211"></a>Declaration</h6><pre class="programlisting">Sub StopKeyman32Engine(ProductID As Long)</pre><h6><a name="id600217"></a>Parameters</h6><table id="id600220"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id600232"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_StartVisualKeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanControl.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_StopVisualKeyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanControl::StartVisualKeyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanControl::StopVisualKeyboard</td></tr></table></div>
