<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardsInstalled Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardsInstalled Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardsPackage_Items.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardsInstalled_Items.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanKeyboardsInstalled">IKeymanKeyboardsInstalled Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanKeyboardsInstalled_Items.php">IKeymanKeyboardsInstalled::Items</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanKeyboardsInstalled_GetKeyboardFromFile.php">IKeymanKeyboardsInstalled::GetKeyboardFromFile</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanKeyboardsInstalled_Install.php">IKeymanKeyboardsInstalled::Install</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanKeyboardsInstalled_Apply.php">IKeymanKeyboardsInstalled::Apply</a></span></dt></dl></div><p>
        interface IKeymanKeyboardsInstalled : 
        <a class="link" href="comapi_interface_IKeymanKeyboards.php" title="IKeymanKeyboards Interface">IKeymanKeyboards</a> : 
        <a class="link" href="comapi_interface_IKeymanCollection.php" title="IKeymanCollection Interface">IKeymanCollection</a> : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>
        A collection of keyboards that are currently installed
      </p><h5><a name="id613415"></a>Interface Methods</h5><table id="id613417"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanKeyboardsInstalled_Apply.php" title="IKeymanKeyboardsInstalled::Apply">Apply</a></td><td>Method</td><td>Sub Apply</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanKeyboardsInstalled_GetKeyboardFromFile.php" title="IKeymanKeyboardsInstalled::GetKeyboardFromFile">GetKeyboardFromFile</a></td><td>Method</td><td>Function GetKeyboardFromFile(Filename as String) as IKeymanKeyboardFile</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanKeyboardsInstalled_Install.php" title="IKeymanKeyboardsInstalled::Install">Install</a></td><td>Method</td><td>Sub Install(Filename as String, AllUsers as Boolean, Force as Boolean)</td></tr></table><h5><a name="id613461"></a>Interface Properties</h5><table id="id613463"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanKeyboardsInstalled_Items.php" title="IKeymanKeyboardsInstalled::Items">Items</a></td><td>Property Get</td><td>Property Get Items(Index) As IKeymanKeyboardInstalled</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardsPackage_Items.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardsInstalled_Items.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardsPackage::Items </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardsInstalled::Items</td></tr></table></div>
