<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanOption Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanOption Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOptions_Items.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption_DefaultValue.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanOption">IKeymanOption Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanOption_DefaultValue.php">IKeymanOption::DefaultValue</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanOption_Enabled.php">IKeymanOption::Enabled</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanOption_Group.php">IKeymanOption::Group</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanOption_Name.php">IKeymanOption::Name</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanOption_Value.php">IKeymanOption::Value</a></span></dt></dl></div><p>
        interface IKeymanOption : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>
        A user-configurable option for the Keyman Engine.  Options are per-user but not per-product.
      </p><h5><a name="id601786"></a>Interface Properties</h5><table id="id601789"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanOption_DefaultValue.php" title="IKeymanOption::DefaultValue">DefaultValue</a></td><td>Property Get</td><td>Property Get DefaultValue As Boolean</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanOption_Enabled.php" title="IKeymanOption::Enabled">Enabled</a></td><td>Property Get</td><td>Property Get Enabled As Boolean</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanOption_Group.php" title="IKeymanOption::Group">Group</a></td><td>Property Get</td><td>Property Get Group As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanOption_Name.php" title="IKeymanOption::Name">Name</a></td><td>Property Get</td><td>Property Get Name As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanOption_Value.php" title="IKeymanOption::Value">Value</a></td><td>Property Get/Let</td><td>Property Get/Let Value As Boolean</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOptions_Items.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption_DefaultValue.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanOptions::Items </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanOption::DefaultValue</td></tr></table></div>
