<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackage::Description"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackage::Description</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage.php">Prev</a> </td><th width="60%" align="center">IKeymanPackage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage_Filename.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackage_Description"><a class="link" href="comapi_interface_IKeymanPackage.php" title="IKeymanPackage Interface">IKeymanPackage</a>::Description</h5></div></div></div><p>
            Returns the description of the package as set by the package author.
          </p><h6><a name="id602140"></a>Declaration</h6><pre class="programlisting">Property Get Description As String</pre><h6><a name="id602146"></a>Parameters</h6><table id="id602149"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id602161"></a>Return Value</h6>String<h6><a name="id602164"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackage_Filename.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackage Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackage::Filename</td></tr></table></div>
