<?php
  require_once('includes/template.php');

  head([
    'title' => "ITavultesoftKeyman::Products"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">ITavultesoftKeyman::Products</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Packages.php">Prev</a> </td><th width="60%" align="center">ITavultesoftKeyman Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Refresh.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_ITavultesoftKeyman_Products"><a class="link" href="comapi_interface_ITavultesoftKeyman.php" title="ITavultesoftKeyman Interface">ITavultesoftKeyman</a>::Products</h5></div></div></div><p>
            Returns a collection of all the products installed in the system.
          </p><h6><a name="id626308"></a>Declaration</h6><pre class="programlisting">Property Get Products As IKeymanProducts</pre><h6><a name="id626314"></a>Parameters</h6><table id="id626316"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id626328"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanProducts.php" title="IKeymanProducts Interface">IKeymanProducts</a><h6><a name="id626334"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Packages.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_ITavultesoftKeyman.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Refresh.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">ITavultesoftKeyman::Packages </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> ITavultesoftKeyman::Refresh</td></tr></table></div>
