<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanControl::ShutdownKeyman32Engine"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanControl::ShutdownKeyman32Engine</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_RegisterControllerWindow.php">Prev</a> </td><th width="60%" align="center">IKeymanControl Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_StartKeyman32Engine.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanControl_ShutdownKeyman32Engine"><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a>::ShutdownKeyman32Engine</h5></div></div></div><p>
            Shuts down the Keyman32.dll engine across all processes in the current session.  Used by Keyman Controllers, not by client applications.  If you are trying to stop a specific product, use IKeymanProduct.Stop instead.
          </p><h6><a name="id600089"></a>Declaration</h6><pre class="programlisting">Sub ShutdownKeyman32Engine</pre><h6><a name="id600095"></a>Parameters</h6><table id="id600097"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id600109"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_RegisterControllerWindow.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanControl.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_StartKeyman32Engine.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanControl::RegisterControllerWindow </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanControl::StartKeyman32Engine</td></tr></table></div>
