<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanSystemInfo::IsAdministrator"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanSystemInfo::IsAdministrator</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_EngineVersion.php">Prev</a> </td><th width="60%" align="center">IKeymanSystemInfo Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanSystemInfo_Refresh.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanSystemInfo_IsAdministrator"><a class="link" href="comapi_interface_IKeymanSystemInfo.php" title="IKeymanSystemInfo Interface">IKeymanSystemInfo</a>::IsAdministrator</h5></div></div></div><p>
            Returns True if Keyman Engine has sufficient privileges to install keyboards and packages for all users.
          </p><h6><a name="id610017"></a>Declaration</h6><pre class="programlisting">Property Get IsAdministrator As Boolean</pre><h6><a name="id610023"></a>Parameters</h6><table id="id610025"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id610037"></a>Return Value</h6>Boolean<h6><a name="id610041"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_EngineVersion.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanSystemInfo.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanSystemInfo_Refresh.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanSystemInfo::EngineVersion </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanSystemInfo::Refresh</td></tr></table></div>
