<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageSubFile::Description"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageSubFile::Description</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php">Prev</a> </td><th width="60%" align="center">IKeymanPackageSubFile Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_Filename.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackageSubFile_Description"><a class="link" href="comapi_interface_IKeymanPackageSubFile.php" title="IKeymanPackageSubFile Interface">IKeymanPackageSubFile</a>::Description</h5></div></div></div><p>
            Returns a description of the file as defined by the package author
          </p><h6><a name="id609261"></a>Declaration</h6><pre class="programlisting">Property Get Description As String</pre><h6><a name="id609267"></a>Parameters</h6><table id="id609269"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id609281"></a>Return Value</h6>String<h6><a name="id609285"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackageSubFile.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_Filename.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackageSubFile::CopyLocation </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageSubFile::Filename</td></tr></table></div>
