<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanProduct::GetActivationData"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanProduct::GetActivationData</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanProduct_Filename.php">Prev</a> </td><th width="60%" align="center">IKeymanProduct Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanProduct_GetActivationRequestCode.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanProduct_GetActivationData"><a class="link" href="comapi_interface_IKeymanProduct.php" title="IKeymanProduct Interface">IKeymanProduct</a>::GetActivationData</h5></div></div></div><p>
            This function is often used at startup time to retrive information about the status of a product - whether the 
            product has been activated or not, and whether the trial period has expired.
          </p><h6><a name="id668013"></a>Declaration</h6><pre class="programlisting">Sub GetActivationData(ActivatedState As Long, TrialDayCount As Long, DaysUsed As Long)</pre><h6><a name="id668019"></a>Parameters</h6><table id="id668021"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr><tr><td>1</td><td>ActivatedState</td><td>Long</td><td>Returns 1 if the product has been activated or 0 if the product is in trial mode</td></tr><tr><td>2</td><td>TrialDayCount</td><td>Long</td><td>Returns the number of days that the product can be trialed for</td></tr><tr><td>3</td><td>DaysUsed</td><td>Long</td><td>Returns the number of days that the product has already been trialed for</td></tr></table><h6><a name="id668067"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanProduct_Filename.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanProduct.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanProduct_GetActivationRequestCode.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanProduct::Filename </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanProduct::GetActivationRequestCode</td></tr></table></div>
