<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanControl::RefreshKeyman"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanControl::RefreshKeyman</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_LastFocusWindow.php">Prev</a> </td><th width="60%" align="center">IKeymanControl Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_RegisterControllerWindow.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanControl_RefreshKeyman"><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a>::RefreshKeyman</h5></div></div></div><p>
            Tells Keyman Engine to refresh all running products with current settings.
          </p><h6><a name="id600002"></a>Declaration</h6><pre class="programlisting">Sub RefreshKeyman</pre><h6><a name="id600008"></a>Parameters</h6><table id="id600011"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id600023"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_LastFocusWindow.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanControl.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_RegisterControllerWindow.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanControl::LastFocusWindow </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanControl::RegisterControllerWindow</td></tr></table></div>
