<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanLanguage::IsIME"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanLanguage::IsIME</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_HKL.php">Prev</a> </td><th width="60%" align="center">IKeymanLanguage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_IsKeymanLayout.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanLanguage_IsIME"><a class="link" href="comapi_interface_IKeymanLanguage.php" title="IKeymanLanguage Interface">IKeymanLanguage</a>::IsIME</h5></div></div></div><p>
            Returns True if the language is installed as an IME
          </p><h6><a name="id614053"></a>Declaration</h6><pre class="programlisting">Property Get IsIME As Boolean</pre><h6><a name="id614059"></a>Parameters</h6><table id="id614062"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id614074"></a>Return Value</h6>Boolean<h6><a name="id614077"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_HKL.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanLanguage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_IsKeymanLayout.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanLanguage::HKL </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanLanguage::IsKeymanLayout</td></tr></table></div>
