<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardsInstalled::Items"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardsInstalled::Items</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardsInstalled.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardsInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardsInstalled_GetKeyboardFromFile.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardsInstalled_Items"><a class="link" href="comapi_interface_IKeymanKeyboardsInstalled.php" title="IKeymanKeyboardsInstalled Interface">IKeymanKeyboardsInstalled</a>::Items</h5></div></div></div><p>
            Returns a keyboard from the package.  If Index is not found, raises an exception.
          </p><h6><a name="id613495"></a>Declaration</h6><pre class="programlisting">Property Get Items(Index) As IKeymanKeyboardInstalled</pre><h6><a name="id613501"></a>Parameters</h6><table id="id613504"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr><tr><td>1</td><td>Index</td><td>Variant</td><td>1-based index of the keyboard to retrieve, or the Name of the keyboard to retrieve</td></tr></table><h6><a name="id613527"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanKeyboard.php" title="IKeymanKeyboard Interface">IKeymanKeyboard</a><h6><a name="id613533"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardsInstalled.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardsInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardsInstalled_GetKeyboardFromFile.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardsInstalled Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardsInstalled::GetKeyboardFromFile</td></tr></table></div>
