<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardInstalled::KeymanID"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardInstalled::KeymanID</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_InstallVisualKeyboard.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_Loaded.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardInstalled_KeymanID"><a class="link" href="comapi_interface_IKeymanKeyboardInstalled.php" title="IKeymanKeyboardInstalled Interface">IKeymanKeyboardInstalled</a>::KeymanID</h5></div></div></div><p>
            Returns the KeymanID of the keyboard.  This is guaranteed to be unique on the current environment and is used internally by
            Keyman Engine to refer to the keyboard.
          </p><h6><a name="id628233"></a>Declaration</h6><pre class="programlisting">Property Get KeymanID As Long</pre><h6><a name="id628239"></a>Parameters</h6><table id="id628241"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id628253"></a>Return Value</h6>Long<h6><a name="id628257"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_InstallVisualKeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_Loaded.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardInstalled::InstallVisualKeyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardInstalled::Loaded</td></tr></table></div>
