<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackage::Name"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackage::Name</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Keyboards.php">Prev</a> </td><th width="60%" align="center">IKeymanPackage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageInstalled.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackage_Name"><a class="link" href="comapi_interface_IKeymanPackage.php" title="IKeymanPackage Interface">IKeymanPackage</a>::Name</h5></div></div></div><p>
            Returns the Name of the package, which is always the filename without path or extension.
          </p><h6><a name="id602265"></a>Declaration</h6><pre class="programlisting">Property Get Name As String</pre><h6><a name="id602271"></a>Parameters</h6><table id="id602273"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id602285"></a>Return Value</h6>String<h6><a name="id602289"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackage_Keyboards.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageInstalled.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackage::Keyboards </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageInstalled Interface</td></tr></table></div>
