<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanLanguage::IsKeymanLayout"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanLanguage::IsKeymanLayout</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_IsIME.php">Prev</a> </td><th width="60%" align="center">IKeymanLanguage Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_KeymanKeyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanLanguage_IsKeymanLayout"><a class="link" href="comapi_interface_IKeymanLanguage.php" title="IKeymanLanguage Interface">IKeymanLanguage</a>::IsKeymanLayout</h5></div></div></div><p>
            Returns True if the language has a System Shadow Keyboard installed.  This is a legacy option that is not commonly used any more.
          </p><h6><a name="id614094"></a>Declaration</h6><pre class="programlisting">Property Get IsKeymanLayout As Boolean</pre><h6><a name="id614100"></a>Parameters</h6><table id="id614103"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id614115"></a>Return Value</h6>Boolean<h6><a name="id614118"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanLanguage_IsIME.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanLanguage.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanLanguage_KeymanKeyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanLanguage::IsIME </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanLanguage::KeymanKeyboard</td></tr></table></div>
