<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanControl::AutoRefresh"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanControl::AutoRefresh</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_ActiveKeyboard.php">Prev</a> </td><th width="60%" align="center">IKeymanControl Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_DisableUserInterface.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanControl_AutoRefresh"><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a>::AutoRefresh</h5></div></div></div><p>
            Set to True if Keyman Engine should automatically refresh when changes are applied to other Keyman COM API interfaces.  If false,
            then RefreshKeyman should be called to tell the running products to refresh their changes.
          </p><h6><a name="id599806"></a>Declaration</h6><pre class="programlisting">Property Get/Let AutoRefresh As Boolean</pre><h6><a name="id599812"></a>Parameters</h6><table id="id599814"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id599826"></a>Return Value</h6>Boolean<h6><a name="id599830"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_ActiveKeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanControl.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanControl_DisableUserInterface.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanControl::ActiveKeyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanControl::DisableUserInterface</td></tr></table></div>
