<?php
  require_once('includes/template.php');

  head([
    'title' => "ITavultesoftKeyman::Errors"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">ITavultesoftKeyman::Errors</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Control.php">Prev</a> </td><th width="60%" align="center">ITavultesoftKeyman Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Keyboards.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_ITavultesoftKeyman_Errors"><a class="link" href="comapi_interface_ITavultesoftKeyman.php" title="ITavultesoftKeyman Interface">ITavultesoftKeyman</a>::Errors</h5></div></div></div><p>
            Returns an interface to the KeymanErrors collection.
          </p><h6><a name="id626040"></a>Declaration</h6><pre class="programlisting">Property Get Errors As IKeymanErrors</pre><h6><a name="id626046"></a>Parameters</h6><table id="id626048"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id626060"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanErrors.php" title="IKeymanErrors Interface">IKeymanErrors</a><h6><a name="id626066"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Control.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_ITavultesoftKeyman.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Keyboards.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">ITavultesoftKeyman::Control </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> ITavultesoftKeyman::Keyboards</td></tr></table></div>
