<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardInstalled::VisualKeyboard"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardInstalled::VisualKeyboard</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_Uninstall.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboards.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardInstalled_VisualKeyboard"><a class="link" href="comapi_interface_IKeymanKeyboardInstalled.php" title="IKeymanKeyboardInstalled Interface">IKeymanKeyboardInstalled</a>::VisualKeyboard</h5></div></div></div><p>
            Returns the on screen keyboard associated with this keyboard.
          </p><h6><a name="id628439"></a>Declaration</h6><pre class="programlisting">Property Get VisualKeyboard As IKeymanVisualKeyboard</pre><h6><a name="id628445"></a>Parameters</h6><table id="id628448"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id613179"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanVisualKeyboard.php" title="IKeymanVisualKeyboard Interface">IKeymanVisualKeyboard</a><h6><a name="id613185"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_Uninstall.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboards.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardInstalled::Uninstall </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboards Interface</td></tr></table></div>
