<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanSystemInfo::EngineInstallPath"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanSystemInfo::EngineInstallPath</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo.php">Prev</a> </td><th width="60%" align="center">IKeymanSystemInfo Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanSystemInfo_EngineVersion.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanSystemInfo_EngineInstallPath"><a class="link" href="comapi_interface_IKeymanSystemInfo.php" title="IKeymanSystemInfo Interface">IKeymanSystemInfo</a>::EngineInstallPath</h5></div></div></div><p>
            Returns the full path to Keyman Engine.
          </p><h6><a name="id609935"></a>Declaration</h6><pre class="programlisting">Property Get EngineInstallPath As String</pre><h6><a name="id609941"></a>Parameters</h6><table id="id609944"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id609956"></a>Return Value</h6>String<h6><a name="id609959"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanSystemInfo.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanSystemInfo_EngineVersion.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanSystemInfo Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanSystemInfo::EngineVersion</td></tr></table></div>
