<?php
  require_once('includes/template.php');

  head([
    'title' => "tagKeymanErrorSeverity Enumeration"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">tagKeymanErrorSeverity Enumeration</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_enumeration_tagKeymanKeyboardHotkey.php">Prev</a> </td><th width="60%" align="center">Enumerations</th><td width="20%" align="right"> <a accesskey="n" href="comapi_enumeration_tagKeymanSerializeFlags.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_enumeration_tagKeymanErrorSeverity">tagKeymanErrorSeverity Enumeration</h4></div></div></div><p>
        The severity of an error received or generated by Keyman Engine.
      </p><h5><a name="id638580"></a>Enumeration Members</h5><table id="id638582"><tr><th>Member Name</th><th>Member Value</th></tr><tr><td>kesFatal</td><td>0</td></tr><tr><td>kesError</td><td>1</td></tr><tr><td>kesWarning</td><td>2</td></tr><tr><td>kesHint</td><td>3</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_enumeration_tagKeymanKeyboardHotkey.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_enumerations.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_enumeration_tagKeymanSerializeFlags.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">tagKeymanKeyboardHotkey Enumeration </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> tagKeymanSerializeFlags Enumeration</td></tr></table></div>
