<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanAddin Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanAddin Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanCollection_Refresh.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddin_Description.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanAddin">IKeymanAddin Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanAddin_Description.php">IKeymanAddin::Description</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanAddin_Filename.php">IKeymanAddin::Filename</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanAddin_Name.php">IKeymanAddin::Name</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanAddin_OwnerPackage.php">IKeymanAddin::OwnerPackage</a></span></dt></dl></div><p>
        interface IKeymanAddin : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>Base interface describing a Keyman addin.</p><h5><a name="id666649"></a>Interface Properties</h5><table id="id666651"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanAddin_Description.php" title="IKeymanAddin::Description">Description</a></td><td>Property Get</td><td>Property Get Description As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanAddin_Filename.php" title="IKeymanAddin::Filename">Filename</a></td><td>Property Get</td><td>Property Get Filename As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanAddin_Name.php" title="IKeymanAddin::Name">Name</a></td><td>Property Get</td><td>Property Get Name As String</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanAddin_OwnerPackage.php" title="IKeymanAddin::OwnerPackage">OwnerPackage</a></td><td>Property Get</td><td>Property Get OwnerPackage As IKeymanPackage</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanCollection_Refresh.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddin_Description.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanCollection::Refresh </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanAddin::Description</td></tr></table></div>
