<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanPackageSubFile::AsStream"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanPackageSubFile::AsStream</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile.php">Prev</a> </td><th width="60%" align="center">IKeymanPackageSubFile Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanPackageSubFile_AsStream"><a class="link" href="comapi_interface_IKeymanPackageSubFile.php" title="IKeymanPackageSubFile Interface">IKeymanPackageSubFile</a>::AsStream</h5></div></div></div><p>
            Returns an IStream of the file.
          </p><h6><a name="id609177"></a>Declaration</h6><pre class="programlisting">Property Get AsStream As Unknown</pre><h6><a name="id609183"></a>Parameters</h6><table id="id609185"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id609197"></a>Return Value</h6>Unknown<h6><a name="id609201"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanPackageSubFile.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanPackageSubFile.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanPackageSubFile_CopyLocation.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanPackageSubFile Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanPackageSubFile::CopyLocation</td></tr></table></div>
