<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanKeyboardInstalled::OwnerPackage"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanKeyboardInstalled::OwnerPackage</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_Loaded.php">Prev</a> </td><th width="60%" align="center">IKeymanKeyboardInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_OwnerProduct.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanKeyboardInstalled_OwnerPackage"><a class="link" href="comapi_interface_IKeymanKeyboardInstalled.php" title="IKeymanKeyboardInstalled Interface">IKeymanKeyboardInstalled</a>::OwnerPackage</h5></div></div></div><p>
            Returns the package that the keyboard was installed as a part of.  If the keyboard was installed separately, then returns NULL.
          </p><h6><a name="id628314"></a>Declaration</h6><pre class="programlisting">Property Get OwnerPackage As IKeymanPackageInstalled</pre><h6><a name="id628320"></a>Parameters</h6><table id="id628323"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id628335"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanPackageInstalled.php" title="IKeymanPackageInstalled Interface">IKeymanPackageInstalled</a><h6><a name="id628341"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanKeyboardInstalled_Loaded.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanKeyboardInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanKeyboardInstalled_OwnerProduct.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanKeyboardInstalled::Loaded </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanKeyboardInstalled::OwnerProduct</td></tr></table></div>
