<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanVisualKeyboard Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanVisualKeyboard Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_RunDiagnostics.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard_Filename.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanVisualKeyboard">IKeymanVisualKeyboard Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanVisualKeyboard_Filename.php">IKeymanVisualKeyboard::Filename</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanVisualKeyboard_Uninstall.php">IKeymanVisualKeyboard::Uninstall</a></span></dt></dl></div><p>
        interface IKeymanVisualKeyboard : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>
        Returns information about an On Screen Keyboard installed in Keyman Engine.
      </p><h5><a name="id610136"></a>Interface Methods</h5><table id="id610138"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanVisualKeyboard_Uninstall.php" title="IKeymanVisualKeyboard::Uninstall">Uninstall</a></td><td>Method</td><td>Sub Uninstall</td></tr></table><h5><a name="id610159"></a>Interface Properties</h5><table id="id610161"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanVisualKeyboard_Filename.php" title="IKeymanVisualKeyboard::Filename">Filename</a></td><td>Property Get</td><td>Property Get Filename As String</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanSystemInfo_RunDiagnostics.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard_Filename.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanSystemInfo::RunDiagnostics </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanVisualKeyboard::Filename</td></tr></table></div>
