<?php
  require_once('includes/template.php');

  head([
    'title' => "ITavultesoftKeyman::Control"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">ITavultesoftKeyman::Control</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_BackgroundRefresh.php">Prev</a> </td><th width="60%" align="center">ITavultesoftKeyman Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Errors.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_ITavultesoftKeyman_Control"><a class="link" href="comapi_interface_ITavultesoftKeyman.php" title="ITavultesoftKeyman Interface">ITavultesoftKeyman</a>::Control</h5></div></div></div><p>
            Returns an interface to the KeymanControl object.
          </p><h6><a name="id625997"></a>Declaration</h6><pre class="programlisting">Property Get Control As IKeymanControl</pre><h6><a name="id626003"></a>Parameters</h6><table id="id626005"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id626017"></a>Return Value</h6><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a><h6><a name="id626023"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_BackgroundRefresh.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_ITavultesoftKeyman.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Errors.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">ITavultesoftKeyman::BackgroundRefresh </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> ITavultesoftKeyman::Errors</td></tr></table></div>
