<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanVisualKeyboard::Filename"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanVisualKeyboard::Filename</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanVisualKeyboard.php">Prev</a> </td><th width="60%" align="center">IKeymanVisualKeyboard Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard_Uninstall.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanVisualKeyboard_Filename"><a class="link" href="comapi_interface_IKeymanVisualKeyboard.php" title="IKeymanVisualKeyboard Interface">IKeymanVisualKeyboard</a>::Filename</h5></div></div></div><p>
            Returns the full path and filename of the on screen keyboard.
          </p><h6><a name="id599477"></a>Declaration</h6><pre class="programlisting">Property Get Filename As String</pre><h6><a name="id599483"></a>Parameters</h6><table id="id599485"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id599497"></a>Return Value</h6>String<h6><a name="id599501"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanVisualKeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanVisualKeyboard.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanVisualKeyboard_Uninstall.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanVisualKeyboard Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanVisualKeyboard::Uninstall</td></tr></table></div>
