<?php
  require_once('includes/template.php');

  head([
    'title' => "ITavultesoftKeyman::ObjectByIndex"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">ITavultesoftKeyman::ObjectByIndex</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Languages.php">Prev</a> </td><th width="60%" align="center">ITavultesoftKeyman Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Options.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_ITavultesoftKeyman_ObjectByIndex"><a class="link" href="comapi_interface_ITavultesoftKeyman.php" title="ITavultesoftKeyman Interface">ITavultesoftKeyman</a>::ObjectByIndex</h5></div></div></div><p>
            Returns an interface to the object with the UniqueIndex referred to by the Index, if it exists.  If it cannot be found, returns NULL.
          </p><h6><a name="id626170"></a>Declaration</h6><pre class="programlisting">Function ObjectByIndex(Index As Long) As Object</pre><h6><a name="id626176"></a>Parameters</h6><table id="id626178"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr><tr><td>1</td><td>Index</td><td>Long</td><td>The UniqueIndex of the object</td></tr></table><h6><a name="id626201"></a>Return Value</h6>Object<h6><a name="id626204"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_ITavultesoftKeyman_Languages.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_ITavultesoftKeyman.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeyman_Options.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">ITavultesoftKeyman::Languages </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> ITavultesoftKeyman::Options</td></tr></table></div>
