<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanOption::Enabled"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanOption::Enabled</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOption_DefaultValue.php">Prev</a> </td><th width="60%" align="center">IKeymanOption Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption_Group.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanOption_Enabled"><a class="link" href="comapi_interface_IKeymanOption.php" title="IKeymanOption Interface">IKeymanOption</a>::Enabled</h5></div></div></div><p>
            Returns True if the option can be set by the end user.  Some options are not relevant except on specific operating systems.
          </p><h6><a name="id601906"></a>Declaration</h6><pre class="programlisting">Property Get Enabled As Boolean</pre><h6><a name="id601912"></a>Parameters</h6><table id="id601915"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id601927"></a>Return Value</h6>Boolean<h6><a name="id601930"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanOption_DefaultValue.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanOption.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanOption_Group.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanOption::DefaultValue </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanOption::Group</td></tr></table></div>
