<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanAddinInstalled::Uninstall"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanAddinInstalled::Uninstall</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanAddinInstalled_InstalledByAdmin.php">Prev</a> </td><th width="60%" align="center">IKeymanAddinInstalled Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddinFile.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanAddinInstalled_Uninstall"><a class="link" href="comapi_interface_IKeymanAddinInstalled.php" title="IKeymanAddinInstalled Interface">IKeymanAddinInstalled</a>::Uninstall</h5></div></div></div><p>
            Uninstalls the addin. Note that all the default addins available for Keyman Engine 7.0 are installed through MSI and 
            should not be uninstalled with this function.  This function will probably be deprecated in a later version of Keyman.
          </p><h6><a name="id666988"></a>Declaration</h6><pre class="programlisting">Sub Uninstall</pre><h6><a name="id666994"></a>Parameters</h6><table id="id666997"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id667009"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanAddinInstalled_InstalledByAdmin.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanAddinInstalled.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanAddinFile.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanAddinInstalled::InstalledByAdmin </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanAddinFile Interface</td></tr></table></div>
