<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanHotkeys Interface"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanHotkeys Interface</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanHotkey_Value.php">Prev</a> </td><th width="60%" align="center">Interfaces</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanHotkeys_Add.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title" id="comapi_interface_IKeymanHotkeys">IKeymanHotkeys Interface</h4></div></div></div><div class="toc"><dl><dt><span class="section"><a href="comapi_interface_IKeymanHotkeys_Add.php">IKeymanHotkeys::Add</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanHotkeys_Apply.php">IKeymanHotkeys::Apply</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanHotkeys_Clear.php">IKeymanHotkeys::Clear</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanHotkeys_Delete.php">IKeymanHotkeys::Delete</a></span></dt><dt><span class="section"><a href="comapi_interface_IKeymanHotkeys_Items.php">IKeymanHotkeys::Items</a></span></dt></dl></div><p>
        interface IKeymanHotkeys : 
        <a class="link" href="comapi_interface_IKeymanCollection.php" title="IKeymanCollection Interface">IKeymanCollection</a> : 
        <a class="link" href="comapi_interface_IKeymanObject.php" title="IKeymanObject Interface">IKeymanObject</a> : 
        IDispatch</p><p>
        A collection of all the hotkeys for a product.
      </p><h5><a name="id626573"></a>Interface Methods</h5><table id="id626575"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanHotkeys_Add.php" title="IKeymanHotkeys::Add">Add</a></td><td>Method</td><td>Function Add(Value As Long, Target As Long) As IKeymanHotkey</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanHotkeys_Apply.php" title="IKeymanHotkeys::Apply">Apply</a></td><td>Method</td><td>Sub Apply</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanHotkeys_Clear.php" title="IKeymanHotkeys::Clear">Clear</a></td><td>Method</td><td>Sub Clear</td></tr><tr><td><a class="link" href="comapi_interface_IKeymanHotkeys_Delete.php" title="IKeymanHotkeys::Delete">Delete</a></td><td>Method</td><td>Sub Delete(Index As Long)</td></tr></table><h5><a name="id626629"></a>Interface Properties</h5><table id="id626632"><tr><th>Name</th><th>Type</th><th>Declaration</th></tr><tr><td><a class="link" href="comapi_interface_IKeymanHotkeys_Items.php" title="IKeymanHotkeys::Items">Items</a></td><td>Property Get</td><td>Property Get Items(Index As Long) As IKeymanHotkey</td></tr></table></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanHotkey_Value.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interfaces.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanHotkeys_Add.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanHotkey::Value </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanHotkeys::Add</td></tr></table></div>
