<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanControl::VisualKeyboardVisible"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanControl::VisualKeyboardVisible</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_UnregisterControllerWindow.php">Prev</a> </td><th width="60%" align="center">IKeymanControl Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeymanScript.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title" id="comapi_interface_IKeymanControl_VisualKeyboardVisible"><a class="link" href="comapi_interface_IKeymanControl.php" title="IKeymanControl Interface">IKeymanControl</a>::VisualKeyboardVisible</h5></div></div></div><p>
            Returns True if the On Screen Keyboard is currently visible.
          </p><h6><a name="id600335"></a>Declaration</h6><pre class="programlisting">Property Get VisualKeyboardVisible As Boolean</pre><h6><a name="id600341"></a>Parameters</h6><table id="id600343"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id600355"></a>Return Value</h6>Boolean<h6><a name="id600359"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanControl_UnregisterControllerWindow.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanControl.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_ITavultesoftKeymanScript.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanControl::UnregisterControllerWindow </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> ITavultesoftKeymanScript Interface</td></tr></table></div>
