<?php
  require_once('includes/template.php');

  head([
    'title' => "Chapter 5. Context Help"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 5. Context Help</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_tools_wix.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="context_frmKeymanDeveloper.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="context"><div class="titlepage"><div><div><h2 class="title">Chapter 5. Context Help</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="context_frmKeymanDeveloper.php">Keyman Developer Help</a></span></dt><dt><span class="section"><a href="context_frmProject.php">Project Window</a></span></dt><dt><span class="section"><a href="context_frmKeymanWizard.php">Keyboard Wizard</a></span></dt><dt><span class="section"><a href="context_frmDebug.php">Debug Window</a></span></dt><dt><span class="section"><a href="context_frmDebugStatus.php">Debugger Status</a></span></dt><dt><span class="section"><a href="context_frmPackageEditor.php">Package Editor</a></span></dt><dt><span class="section"><a href="context_frmKCTMain.php">Branding Editor</a></span></dt><dt><span class="section"><a href="context_frmInstallerEditor.php">Distribution Editor</a></span></dt><dt><span class="section"><a href="context_frmOSKEditor.php">On Screen Keyboard Editor</a></span></dt><dt><span class="section"><a href="context_frmEditor.php">Editor Window</a></span></dt><dt><span class="section"><a href="context_frmNew.php">New File Dialog</a></span></dt><dt><span class="section"><a href="context_frmAbout.php">About Dialog</a></span></dt><dt><span class="section"><a href="context_frmActivation.php">
    Activating Keyman Developer
  </a></span></dt><dt><span class="section"><a href="context_frmActivationModules.php">Buying and Activating Modules</a></span></dt><dt><span class="section"><a href="context_frmKeyTest.php">Virtual Key Identifier</a></span></dt><dt><span class="section"><a href="context_frmOptions.php">Options Dialog</a></span></dt><dt><span class="section"><a href="context_frmStartup.php">Splash Screen</a></span></dt><dt><span class="section"><a href="context_kmcomp.php">KMComp Command-line Options</a></span></dt><dt><span class="section"><a href="context_frmCharacterMapNew.php">Using the Character Map</a></span></dt><dt><span class="section"><a href="context_frmMessages.php">Message Window</a></span></dt></dl></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_tools_wix.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="context_frmKeymanDeveloper.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Windows Installer XML (WiX) </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Developer Help</td></tr></table></div>
