<?php
  require_once('includes/template.php');

  head([
    'title' => "KeymanWeb Utility Module"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">KeymanWeb Utility Module</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_kmw20_osk_classes.php">Prev</a> </td><th width="60%" align="center">KeymanWeb 2.0</th><td width="20%" align="right"> <a accesskey="n" href="reference_kmw20_util_addStyleSheet.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h3 class="title" id="reference_kmw20_utility">KeymanWeb Utility Module</h3></div><div><p class="releaseinfo">
  </p><p>
    The <span class="emphasis"><em>KeymanWeb</em></span> Utility Function module is exposed to the developer as 
    <code class="code">
      window.tavultesoft.keymanweb.util
    </code> 
  </p><p class="releaseinfo">
  </p></div></div></div><div class="toc"><dl><dt><span class="section"><a href="reference_kmw20_util_addStyleSheet.php">Function: addStyleSheet</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_attachDOMEvent.php">Function: attachDOMEvent</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_borderRadius.php">Function: borderRadius</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_boxShadow.php">Function: boxShadow</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_createElement.php">Function: createElement</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_createShim.php">Function: createShim</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_getAbsolute.php">Function: getAbsolute</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_getAbsoluteX.php">Function: getAbsoluteX</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_getAbsoluteX.php">Function: getAbsoluteY</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_getIEVersion.php">Function: getIEVersion</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_getOption.php">Function: getOption</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_hideShim.php">Function: hideShim</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_loadCookie.php">Function: loadCookie</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_rgba.php">Function: rgba</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_saveCookie.php">Function: saveCookie</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_setOption.php">Function: setOption</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_showShim.php">Function: showShim</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_toFloat.php">Function: toFloat</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_toNumber.php">Function: toNumber</a></span></dt><dt><span class="section"><a href="reference_kmw20_util_toNzString.php">Function: toNzString</a></span></dt></dl></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_kmw20_osk_classes.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference_kmw20_index.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="reference_kmw20_util_addStyleSheet.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">On-Screen Keyboard Class Names </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Function: addStyleSheet</td></tr></table></div>
