<?php
  require_once('includes/template.php');

  head([
    'title' => "KeymanWeb Keyboard Properties"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">KeymanWeb Keyboard Properties</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_kmw20_events.php">Prev</a> </td><th width="60%" align="center">KeymanWeb 2.0</th><td width="20%" align="right"> <a accesskey="n" href="reference_kmw20_example.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h3 class="title" id="reference_kmw20_keyboard_properties">KeymanWeb Keyboard Properties</h3></div></div></div><p>
    Most keyboards are generated automatically from the Keyman keyboard source by 
    <span class="emphasis"><em>Keyman Developer</em></span> and contain properties used by 
    <span class="emphasis"><em>KeymanWeb</em></span> during keyboard mapping. 
    Keyboards implement mapping by invoking functions within <span class="emphasis"><em>KeymanWeb</em></span>, 
    but do not interact directly with the user interface.  
    However, user interfaces may need to interact with custom developed keyboards if, for example, 
    they use a "pick list" or have other IME-like behavior.
  </p><p>
    Each registered keyboard object defines some or all of the following exposed string properties:
  </p><div class="informaltable"><table border="1"><colgroup><col><col><col><col></colgroup><thead><tr><th align="left">Property name</th><th align="left">Parameter in 'GetKeyboards'</th><th align="left">Defined by</th><th align="left">Description</th></tr></thead><tbody><tr><td align="left"><span class="emphasis"><em>KN</em></span></td><td align="left">name</td><td align="left">Keyboard (mandatory)</td><td align="left">Visible name of keyboard</td></tr><tr><td align="left"><span class="emphasis"><em>KI</em></span></td><td align="left">internalName</td><td align="left">Keyboard (mandatory)</td><td align="left">Internal name (must be unique)</td></tr><tr><td align="left"><span class="emphasis"><em>KD</em></span></td><td align="left">keyboardID</td><td align="left">Keyboard ID</td><td align="left">Globally unique ID (assigned by Tavultesoft)</td></tr><tr><td align="left"><span class="emphasis"><em>KL</em></span></td><td align="left">language</td><td align="left">Stub script</td><td align="left">Main supported language</td></tr><tr><td align="left"><span class="emphasis"><em>KLC</em></span></td><td align="left">languageCode</td><td align="left">Keyboard (optional) or stub script</td><td align="left">Standard ISO code(s) for supported keyboard language(s)</td></tr><tr><td align="left"><span class="emphasis"><em>KC</em></span></td><td align="left">country</td><td align="left">Stub script</td><td align="left">Name of country</td></tr><tr><td align="left"><span class="emphasis"><em>KCC</em></span></td><td align="left">countryCode</td><td align="left">Stub script</td><td align="left">Abbreviation for country name</td></tr><tr><td align="left"><span class="emphasis"><em>KR</em></span></td><td align="left">region</td><td align="left">Stub script</td><td align="left">Language region or continent</td></tr><tr><td align="left"><span class="emphasis"><em>KRC</em></span></td><td align="left">regionCode</td><td align="left">Stub script</td><td align="left">Three-letter region code</td></tr></tbody></table></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_kmw20_events.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference_kmw20_index.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="reference_kmw20_example.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">KeymanWeb 2.0 Events </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Using KeymanWeb: An Example</td></tr></table></div>
