<?php
  require_once('includes/template.php');

  head([
    'title' => "KeymanWeb 2.0 Initialization Options"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">KeymanWeb 2.0 Initialization Options</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_kmw20_ui_toolbar.php">Prev</a> </td><th width="60%" align="center">KeymanWeb 2.0</th><td width="20%" align="right"> <a accesskey="n" href="reference_kmw20_events.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h3 class="title" id="reference_kmw20_initialization">KeymanWeb 2.0 Initialization Options</h3></div></div></div><p>
    The following options can be defined by the site designer in the initialization call to <span class="emphasis"><em>KeymanWeb</em></span>.
  </p><div class="informaltable"><table border="1"><colgroup><col><col><col></colgroup><thead><tr><th align="left">Option name</th><th align="left">Description</th><th align="left">Default value</th></tr></thead><tbody><tr><td align="left"><span class="emphasis"><em>key</em></span></td><td align="left">License or subscription key</td><td align="left">(none)</td></tr><tr><td align="left"><span class="emphasis"><em>ui</em></span></td><td align="left">(Desktop) user interface to be used</td><td align="left">float</td></tr><tr><td align="left"><span class="emphasis"><em>root</em></span></td><td align="left">KeymanWeb script folder URL</td><td align="left">http://r.keymanweb.com/kmw20/</td></tr><tr><td align="left"><span class="emphasis"><em>resources</em></span></td><td align="left">UI image folder URL</td><td align="left">[root]/resources</td></tr><tr><td align="left"><span class="emphasis"><em>fonts</em></span></td><td align="left">List of embedded fonts required for OSK or keyboards</td><td align="left">(none)</td></tr><tr><td align="left"><span class="emphasis"><em>attachControlsByDefault</em></span></td><td align="left">Let all input controls have input remapped by KeymanWeb</td><td align="left">true (false not yet implemented)</td></tr><tr><td align="left"><span class="emphasis"><em>unmappedKeyboardName</em></span></td><td align="left">Normal keyboard language when keyboard mapping disabled</td><td align="left">English</td></tr><tr><td align="left"><span class="emphasis"><em>defaultKeyboardHelp</em></span></td><td align="left">KeymanWeb prompt message</td><td align="left">Select a keyboard from the drop-down list</td></tr><tr><td align="left"><span class="emphasis"><em>controlDownColor</em></span></td><td align="left">Active control key color in OSK</td><td align="left">#e0e0e0</td></tr><tr><td align="left"><span class="emphasis"><em>keyDownColor</em></span></td><td align="left">Active key color in OSK</td><td align="left">#c0c0ff</td></tr><tr><td align="left"><span class="emphasis"><em>keyHoverColor</em></span></td><td align="left">Hovered key color in OSK</td><td align="left">#e0e0ff</td></tr></tbody></table></div><p>
    All option values are strings, except for the <span class="emphasis"><em>ui</em></span> option, which can be 
    either a string or an object array containing named members.  
    If the <span class="emphasis"><em>ui</em></span> option is an object, one member must be <span class="emphasis"><em>name</em></span>, 
    and other members are specific to the ui.  The only currently defined ui-specific option is 
    <span class="emphasis"><em>position: 'right'</em></span> for right-alignment of the "float" ui.
  </p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_kmw20_ui_toolbar.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference_kmw20_index.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="reference_kmw20_events.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">'Toolbar' Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> KeymanWeb 2.0 Events</td></tr></table></div>
