<?php
  require_once('includes/template.php');

  head([
    'title' => "KeymanWeb Output Functions"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">KeymanWeb Output Functions</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_kmw20_util_toNzString.php">Prev</a> </td><th width="60%" align="center">KeymanWeb 2.0</th><td width="20%" align="right"> <a accesskey="n" href="reference_kmw20_output_KA.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h3 class="title" id="reference_kmw20_output">KeymanWeb Output Functions</h3></div><div><p class="releaseinfo">
  </p><p>
    The <span class="emphasis"><em>KeymanWeb</em></span> core object <code class="code">window.tavultesoft.keymanweb</code>
    also exposes a number of functions for low-level processing of input, context and output.  
    Custom user interfaces would not normally use these functions, but they are described here 
    as some custom keyboards, such as IME-style keyboards, may need to interact with the user interface.
  </p><p class="releaseinfo">
  </p></div></div></div><div class="toc"><dl><dt><span class="section"><a href="reference_kmw20_output_KA.php">Function: KA</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KB.php">Function: KB</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KBR.php">Function: KBR</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KC.php">Function: KC</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KCM.php">Function: KCM</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KDM.php">Function: KDM</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KDO.php">Function: KDO</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KIK.php">Function: KIK</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KIO.php">Function: KIO</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KKI.php">Function: KKI</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KKM.php">Function: KKM</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KN.php">Function: KN</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KO.php">Function: KO</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KR.php">Function: KR</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KRS.php">Function: KRS</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KSF.php">Function: KSF</a></span></dt><dt><span class="section"><a href="reference_kmw20_output_KT.php">Function: KT</a></span></dt></dl></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_kmw20_util_toNzString.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference_kmw20_index.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="reference_kmw20_output_KA.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Function: toNzString </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Function: KA</td></tr></table></div>
