<?php
  require_once('includes/template.php');
  require_once('../__interface-hierarchy.php');
  head([
    'title' => "IKeymanKeyboard Interface"
  ]);
?>

<h1>IKeymanKeyboard Interface</h1>

<h2>Introduction</h2>

<p>The <code>IKeymanKeyboard</code> interface describes a keyboard in Keyman Engine for Windows API. It is a base class
and describes both installed keyboards and keyboard files.</p>

<h2>Interface Hierarchy</h2>

<?php print_interface_hierarchy('IKeymanKeyboard', '../'); ?>

<h2>Properties</h2>

<dl>
  <dt><a href='Bitmap'><code>Bitmap</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the <a href='/developer/language/reference/bitmap'><code>&amp;bitmap</code></a> icon from the keyboard file as an <code>IPicture</code>.</dd>

  <dt><a href='Copyright'><code>Copyright</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the <a href='/developer/language/reference/copyright'><code>&amp;copyright</code></a> string from the keyboard file.</dd>

  <dt><a href='DefaultBCP47Languages'><code>DefaultBCP47Languages</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the set of default language ids for the keyboard as a space-separated list of BCP 47 codes. The first code in the
  list is the primary language.</dd>

  <dt><a href='DefaultHotkey'><code>DefaultHotkey</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the default hotkey for the keyboard.</dd>

  <dt><a href='DefaultPrimaryLanguage'><code>DefaultPrimaryLanguage</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the default primary language id for the keyboard.</dd>

  <dt><a href='DefaultWindowsLanguages'><code>DefaultWindowsLanguages</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the set of default language ids for the keyboard as a space-separated list of hexadecimal strings.</dd>

  <dt><a href='Encodings'><code>Encodings</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the set of encodings supported by the keyboard layout.</dd>

  <dt><a href='Filename'><code>Filename</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the fully-qualified filename of the keyboard file.</dd>

  <dt><a href='ID'><code>ID</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the identifier for the keyboard, which is the base name of the keyboard file without extension.</dd>

  <dt><a href='LayoutType'><code>LayoutType</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the layout type of the keyboard as specified by the <a href='/developer/language/reference/mnemoniclayout'><code>&amp;mnemoniclayout</code></a> store.</dd>

  <dt><a href='Message'><code>Message</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the <a href='/developer/language/reference/message'><code>&amp;message</code></a> string from the keyboard file.</dd>

  <dt><a href='Name'><code>Name</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the <a href='/developer/language/reference/name'><code>&amp;name</code></a> from the keyboard file.</dd>

  <dt><a href='Version'><code>Version</code></a> <span class='readonly'>read only</span></dt>
  <dd>Returns the <a href='/developer/language/reference/keyboardversion'><code>&amp;keyboardversion</code></a> string from the keyboard file.</dd>
</dl>

<h2>Methods</h2>

<dl>
  <dt><a href='GetCharsUsed'><code>GetCharsUsed()</code></a></dt>
  <dd>Returns a string with every Unicode character used or generated by the keyboard.</dd>
</dl>
