<?php
  require_once('includes/template.php');

  head([
    'title' => "Function: removeEventListener"
  ]);

  require_once('includes/__docheader.php');
?>

<h1 class="title" id="removeEventListener">removeEventListener</h1>

<h2 id="Summary" name="Summary">Summary</h2>

<p>Removes a user-defined event handler.</p>

<h2 id="Syntax" name="Syntax">Syntax</h2>

<?php
syntax("keyman.osk.removeEventListener(eventName, func);");
params('eventName', "string", "The name of an event generated by the <code>keyman.osk</code> object.",
  'func', 'Function', "A function currently set to handle that event when it is raised.");
returns();
?>

<h2 id="Description" name="Description">Description</h2>

<p>To be implemented.</p>
<p>Will be the OSK's analogue of the to-be-implemented core function
  <a href="../core/removeEventListener"><code>removeEventListener</code></a>.</p>