<?php
  require_once('includes/template.php');

  head([
    'title' => "Does Keyman include a virtual on-screen keyboard?"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Does Keyman include a virtual on-screen keyboard?</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="common_linux.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Common Questions</th><td width="20%" align="right"> <a accesskey="n" href="common_unicode.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="common_osk">Does Keyman include a virtual on-screen keyboard?</h2></div></div></div><p>Yes. However, some of the Keyman keyboards available on our website do not currently include an On Screen Keyboard. To know if a keyboard download includes an On Screen Keyboard, look for the <span class="inlinemediaobject"><img src="desktop_images/icon-osk.png"></span> icon in the Keyman keyboard downloads list.</p><p>To check if an installed keyboard includes an On Screen Keyboard, start Keyman Configuration, navigate to the Keyboards tab, and expand the details for the keyboard.  The
On Screen Keyboard entry in the details will give more information on whether or not an On Screen Keyboard is available for the selected keyboard.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="common_linux.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="common.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="common_unicode.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Does Keyman Desktop run on Linux? </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Does Keyman Desktop support Unicode?</td></tr></table></div>
