<?php
  require_once('includes/template.php');

  head([
    'title' => "What is new in  Keyman Desktop 10.0?"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">What is new in  Keyman Desktop 10.0?</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="common.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Common Questions</th><td width="20%" align="right"> <a accesskey="n" href="common_os.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="common_editions">What is new in  Keyman Desktop 10.0?</h2></div></div></div><p>Keyman Desktop 10 brings a number of features which are not available in the Free edition of the previous Keyman Desktop. These features are:</p><div class="itemizedlist"><ul type="disc"><li><p><a class="link" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Unlimited active keyboards</a></p></li><li><p><a class="link" href="basic_charactermap.php" title="Keyman Toolbox - Character Map">Keyman Character Map</a></p></li><li><p><a class="link" href="basic_languageswitcher.php" title="Language Switcher">Keyman Language Switcher</a></p></li><li><p><a class="link" href="basic_fonthelper.php" title="Keyman Toolbox - Font Helper">Advanced Font Helper - Character Chart</a></p></li><li><p><a class="link" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Advanced Hotkey Support - Windows Language Hotkeys</a></p></li><li><p><a class="link" href="advanced_tsf.php" title="Text Services Framework">Keyman Text Services Framework Addin</a></p></li></ul></div><p>
  You can review the full feature list of Keyman Desktop 10.0 online: <a class="ulink" href="http://www.keyman.com/desktop/" target="_blank">Keyman Website</a>.
 </p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="common.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="common.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="common_os.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 5. Common Questions </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> What operating systems does Keyman Desktop 10 support?</td></tr></table></div>
