sequenceDiagram
    autonumber
    participant User as User
    participant OS as Windows OS
    participant TSF as TSF Manager
    participant Keyman as Keyman TIP
    participant App as Application (Compliant)

    User->>OS: Press key (e.g. 'D')
    OS->>TSF: Deliver key event
    TSF->>Keyman: Call OnKeyDown(ITfContext)

    Note right of Keyman: Keyman create TIPEditSession & requests context
    Keyman->>TSF: ITfContext.GetStatus()
    Keyman->>TSF: ITfContext.GetSelection()
    TSF->>App: Request current selection
    App-->>TSF: Return caret/selection
    TSF-->>Keyman: Return GetSelection


    Note right of Keyman: Keyman applies keyboard rules and computes output

    Keyman->>TSF: ITfContext.SetText()
    TSF->>App: Delete or replace text in range

    App-->>User: Display “∆” in document