<?php
  require_once('includes/template.php');

  head([
    'title' => "tagKeymanErrorSeverity Enumeration"
  ]);
?>

<h1>tagKeymanErrorSeverity Enumeration</h1>

    <p>The severity of an error received or generated by Keyman Engine.</p>

    <h5><a name="id578446" id="id578446"></a>Enumeration Members</h5>

    <table id="id578455">
      <tr>
        <th>Member Name</th>

        <th>Member Value</th>
      </tr>

      <tr>
        <td>kesFatal</td>

        <td>0</td>
      </tr>

      <tr>
        <td>kesError</td>

        <td>1</td>
      </tr>

      <tr>
        <td>kesWarning</td>

        <td>2</td>
      </tr>

      <tr>
        <td>kesHint</td>

        <td>3</td>
      </tr>
    </table>
