<?php
  require_once('includes/template.php');

  head([
    'title' => "Chapter 1. About Keyman Desktop"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 1. About Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="index.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="about_welcome.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="about"><div class="titlepage"><div><div><h2 class="title">Chapter 1. About Keyman Desktop</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="about_welcome.php">Welcome to Keyman Desktop 8.0</a></span></dt><dt><span class="section"><a href="about_whatsnew.php">What's New</a></span></dt><dt><span class="section"><a href="about_purchase.php">Licensing Information</a></span></dt><dt><span class="section"><a href="about_requirements.php">System Requirements</a></span></dt><dt><span class="section"><a href="about_history.php">Version History</a></span></dt><dt><span class="section"><a href="about_credits.php">Credits</a></span></dt><dt><span class="section"><a href="about_license.php">End User Licence and Services Agreement</a></span></dt></dl></div><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>
        Can't find the help you need? Contact <a class="ulink" href="mailto:support@tavultesoft.com" target="_blank">Tavultesoft Support</a> and we would be happy to help.
      </p></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="index.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="about_welcome.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Desktop User Guide </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Welcome to Keyman Desktop 8.0</td></tr></table></div>
