<?php
  require_once('includes/template.php');

  head([
    'title' => "Chapter 4. Advanced Help"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 4. Advanced Help</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_help.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="advanced_proxy_config.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="advanced"><div class="titlepage"><div><div><h2 class="title">Chapter 4. Advanced Help</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="advanced_proxy_config.php">Proxy Configuration</a></span></dt><dt><span class="section"><a href="advanced_tsactivate.php">The Tavultesoft Online Activation Utility</a></span></dt><dt><span class="section"><a href="advanced_tsf.php">The Text Services Framework Addin</a></span></dt><dt><span class="section"><a href="advanced_richedit.php">The RichEdit Addin</a></span></dt><dt><span class="section"><a href="advanced_uniscribe.php">The Keyman Desktop Uniscribe Manager</a></span></dt><dt><span class="section"><a href="advanced_language_config.php">Language Configuration Tasks</a></span></dt><dt><span class="section"><a href="advanced_shadow_keyboards.php">System Shadow Keyboards</a></span></dt><dt><span class="section"><a href="advanced_locale_edit.php">The Locale Editor - Translating the Keyman Desktop User Interface</a></span></dt></dl></div><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>
        Can't find the help you need? Contact <a class="ulink" href="mailto:support@tavultesoft.com" target="_blank">Tavultesoft Support</a> and we would be happy to help.
      </p></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_help.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="advanced_proxy_config.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">The Keyman Desktop Help Menu </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Proxy Configuration</td></tr></table></div>
