<?php
  require_once('includes/template.php');

  head([
    'title' => "System Shadow Keyboards"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">System Shadow Keyboards</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="advanced_language_config.php">Prev</a> </td><th width="60%" align="center">Chapter 4. Advanced Help</th><td width="20%" align="right"> <a accesskey="n" href="advanced_locale_edit.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="advanced_shadow_keyboards">System Shadow Keyboards</h2></div></div></div><p>System shadow keyboards allow you to use Keyman Desktop keyboard layouts as if they were native Windows keyboards. </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>Unless you have a specific need to use system shadow keyboards, 
    you should instead use the <a class="link" href="basic_languages_tab.php" title="Keyman Configuration - Languages Tab">Languages tab</a> in Keyman Desktop Configuration.  System Shadow Keyboards are not recommended due to limitations 
    in their configuration and use, and are retained only for legacy support.  The system shadow keyboard functionality will be removed in a future version of Keyman Desktop.</p></div><p>For example:</p><div class="itemizedlist"><ul type="disc"><li><p>If you have a customized keyboard layout for French, you could use it in place of the standard French keyboard layout that Windows installs, or,</p></li><li><p>If you have a keyboard layout for a language not supported by Windows, you can associate that keyboard layout with a language you're not currently using. For example, 
      if you have a keyboard layout for Anglo-Saxon, which is not supported by Windows, you could 
      associate it with Afrikaans or Finnish (assuming that you don't normally use either of those languages).</p></li></ul></div><p>When you install a keyboard layout into Keyman Desktop, a Windows keyboard layout with the same name is also installed into the Windows Control Panel. You 
  can associate this keyboard layout with any language you like.</p><h3><a name="id631834"></a>Associate a keyboard layout with a language (Windows XP):</h3><div class="orderedlist"><ol type="1"><li><p>Click on the Start menu.</p></li><li><p>Select Control Panel.</p></li><li><p>Select 'Date, Time, Language, and Regional Options' (if not in Classic View) or 'Regional and Language Options' (Classic View).</p></li><li><p>Select the Languages tab.</p></li><li><p>Click <span class="guibutton">Details</span>.</p></li><li><p>Click <span class="guibutton">Add</span>.</p></li><li><p>Select the Input Language.</p></li><li><p>Select the Keyman Desktop keyboard layout from the list of Keyboard layouts/IMEs.</p></li><li><p>Click <span class="guibutton">OK</span> to apply changes.</p></li></ol></div><h3><a name="id631918"></a>Associate a keyboard layout with a language (Windows Vista):</h3><div class="orderedlist"><ol type="1"><li><p>Click on the Start menu.</p></li><li><p>Select Control Panel.</p></li><li><p>Select 'Regional and Language Options'.</p></li><li><p>Select the Keyboards and Languages tab.</p></li><li><p>Click <span class="guibutton">Change Keyboards</span>.</p></li><li><p>Click <span class="guibutton">Add</span>.</p></li><li><p>Select the Input Language.</p></li><li><p>Select Keyboard, and tick the box Show More.</p></li><li><p>Select the Keyman Desktop keyboard layout from the list of layouts/IMEs.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>The Keyman Desktop keyboard layout must be installed for 
      all users in order to be viewable from this screen. </div></li><li><p>Click <span class="guibutton">OK</span>.</p></li><li><p>Click <span class="guibutton">OK</span> to apply changes.</p></li></ol></div><h3><a name="id632023"></a>Associate a keyboard layout with a language (Windows 7):</h3><div class="orderedlist"><ol type="1"><li><p>Click on the Start menu and type 'Keyboards'.</p></li><li><p>Select 'Change keyboards or other input methods'.</p></li><li><p>Select <span class="guibutton">Change Keyboards…</span>.</p></li><li><p>Click <span class="guibutton">Add</span>.</p></li><li><p>Select the Input Language.</p></li><li><p>Select Keyboard, and tick the box Show More.</p></li><li><p>Select the Keyman Desktop keyboard layout from the list of layouts/IMEs.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>The Keyman Desktop keyboard layout must be installed for 
      all users in order to be viewable from this screen. </div></li><li><p>Click <span class="guibutton">OK</span>.</p></li><li><p>Click <span class="guibutton">OK</span> to apply changes.</p></li></ol></div><h3><a name="id632114"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_languages_tab.php" title="Keyman Configuration - Languages Tab">Keyman Configuration - Languages Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="advanced_language_config.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="advanced.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="advanced_locale_edit.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Language Configuration Tasks </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The Locale Editor - Translating the Keyman Desktop User Interface</td></tr></table></div>
