<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Configuration - Support Tab"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Support Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_languages_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_support_tab">Keyman Configuration - Support Tab</h2></div></div></div><p>The Support tab of Keyman Configuration displays Keyman Desktop version information, registration status, proxy settings and support tools. You can use the Support tab to run a support diagnostic, check Windows language settings, check for updates, configure proxy settings and view Keyman Desktop version information and registration status.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/tab-support.png"></span>
  </p><h3><a name="id626306"></a>Opening the Support Tab</h3><p>To open the Support tab of Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Support tab.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Keyman Configuration opens in the same tab you last closed it in.</div></li></ol></div><h3><a name="id625551"></a>Sending a Diagnostic</h3><p>You can send a support diagnostic to Tavultesoft from the Support tab of Keyman Configuration. You may need to send a support diagnostic if you are having a technical difficulty with Keyman Desktop. The support diagnostic will collect critical diagnostic information from your computer and generate a report.</p><p>To send a support diagnostic:</p><div class="orderedlist"><ol type="1"><li><p>Click <span class="guibutton">Diagnostic</span> in the Support tab of Keyman Configuration.</p></li><li><p>Select 'Diagnostic…'.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/diagnostic-link.png"></span>
  </p></li><li><p>Wait while your diagnostic data is collected.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/diagnostic-progress.png"></span>
  </p></li><li><p>Click <span class="guibutton">Send Report to Tavultesoft…</span>.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/diagnostic-report.png"></span>
  </p></li><li><p>Fill in your details, including details about the problem and any error messages you received.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/diagnostic-sendform.png"></span>
  </p></li><li><p>Click <span class="guibutton">Send</span>.</p></li><li><p>When we receive your support diagnostic, we will review it and reply promptly, working with you to help you find a solution to your issue.</p></li></ol></div><h3><a name="id627978"></a>Checking Windows Language Settings</h3><p>You can run a test to see if your Windows language settings are correct for your currently installed Keyman keyboards. To run a test:</p><div class="orderedlist"><ol type="1"><li><p>Click <span class="guibutton">Diagnostic</span> in the Support tab of Keyman Configuration.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/support-settings.png"></span>
  </p></li><li><p>Select 'Check Windows Language Settings'.</p></li><li><p>You will then see one of two possible screens:</p><div class="itemizedlist"><ul type="disc"><li><p>If all settings are correct, click <span class="guibutton">OK</span>.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/support-settingsok.png"></span>
</p></li><li><p>Otherwise, you will be presented with the Language Configuration Tasks menu. You have three options:</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/language-tasks.png"></span>
  </p><div class="itemizedlist"><ul type="circle"><li><p>Click <span class="guibutton">Apply</span> to apply the suggested configuration tasks.</p></li><li><p>Click <span class="guibutton">Remind me Later</span> to make the decision the next time you restart Keyman Desktop.</p></li><li><p>Tick 'Don't ask me about this again' and click <span class="guibutton">OK</span> to reject the suggested configuration tasks.</p></li></ul></div></li></ul></div></li></ol></div><h3><a name="id627422"></a>Checking for Updates</h3><p>To check for Keyman Desktop updates, from the Support tab of Keyman Configuration click the 'Check for Updates…' link. You can also download and install Keyman Desktop again from the Tavultesoft website.</p><h3><a name="id627396"></a>Changing Proxy Settings</h3><p>The <span class="guibutton">Proxy Settings…</span> button allows authorised users to alter proxy server configuration. For more information, see: <a class="xref" href="advanced_proxy_config.php" title="Proxy Configuration">Proxy Configuration</a></p><p>
    <span class="inlinemediaobject"><img src="desktop_images/proxy-empty.png"></span>
  </p><h3><a name="id627715"></a>About Version and Activation Information</h3><p>You can view version details and registration status from the Support tab of Keyman Configuration. In the Support tab you will see:</p><div class="itemizedlist"><ul type="disc"><li>Version Detals
			<div class="itemizedlist"><ul type="circle"><li><p>Edition — Details on your current edition of Keyman Desktop.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If you are running Keyman Desktop Light, you will see an <span class="guibutton">Upgrade to Professional…</span> button at the bottom left of the Keyman Configuration menu. If you are running Keyman Desktop Professional you will not see any buttons at the bottom left of Keyman Configuration.</p></div></li><li><p>Version — The current Keyman Desktop version number</p></li><li><p>Engine Version — The version number of the Keyman Engine</p></li></ul></div></li><li>Registration Status
			<div class="itemizedlist"><ul type="circle"><li><p>Activated — Displays 'Yes' if Keyman Desktop is activated and 'No' if not.</p></li><li><p>Days Used — Shows how many days remain in a free 30-day trial of Keyman Desktop. This field is blank once you activate Keyman Desktop.</p></li></ul></div></li></ul></div><h3><a name="id630646"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman Desktop">How To - Download and Install Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_languages_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Languages Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The Keyman Desktop Help Menu</td></tr></table></div>
