<?php
  require_once('includes/template.php');

  head([
    'title' => "Chapter 5. Common Questions"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 5. Common Questions</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="advanced_locale_edit.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="common_editions.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="common"><div class="titlepage"><div><div><h2 class="title">Chapter 5. Common Questions</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="common_editions.php">What is the difference between Keyman Desktop Light and Professional?</a></span></dt><dt><span class="section"><a href="common_os.php">What operating systems does Keyman Desktop 8 support?</a></span></dt><dt><span class="section"><a href="common_requirements.php">What are Keyman's hardware requirements?</a></span></dt><dt><span class="section"><a href="common_adware.php">Does Keyman include adware or spyware?</a></span></dt><dt><span class="section"><a href="common_mac.php">Does Keyman Desktop run on a Mac?</a></span></dt><dt><span class="section"><a href="common_linux.php">Does Keyman Desktop run on Linux?</a></span></dt><dt><span class="section"><a href="common_osk.php">Does Keyman include a virtual on-screen keyboard?</a></span></dt><dt><span class="section"><a href="common_unicode.php">Does Keyman Desktop support Unicode?</a></span></dt><dt><span class="section"><a href="common_compatibility.php">Does Keyman work with all software?</a></span></dt><dt><span class="section"><a href="common_license_details.php">Where can I find my licence details?</a></span></dt><dt><span class="section"><a href="common_license.php">Can I run Keyman Desktop on a second computer?</a></span></dt><dt><span class="section"><a href="common_license_duration.php">How long does my licence last?</a></span></dt><dt><span class="section"><a href="common_upgrades.php">Do I get free upgrades with my licence?</a></span></dt><dt><span class="section"><a href="common_transfer.php">Can I move my licence to a new computer?</a></span></dt><dt><span class="section"><a href="common_free.php">Where is the Free Edition?</a></span></dt><dt><span class="section"><a href="common_old_version.php">I am a registered Keyman 6.2 or Keyman Desktop 7 user. Can I still download Keyman 6.2 or Keyman Desktop 7?</a></span></dt><dt><span class="section"><a href="common_support.php">What support do I get with my Keyman Desktop licence?</a></span></dt><dt><span class="section"><a href="common_bug.php">I think I found a bug! How can I tell you about it?</a></span></dt></dl></div><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>
        Can't find the help you need? Contact <a class="ulink" href="mailto:support@tavultesoft.com" target="_blank">Tavultesoft Support</a> and we would be happy to help.
      </p></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="advanced_locale_edit.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="common_editions.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">The Locale Editor - Translating the Keyman Desktop User Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> What is the difference between Keyman Desktop Light and Professional?</td></tr></table></div>
