<?php
  require_once('includes/template.php');

  head([
    'title' => "The Text Services Framework Addin"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">The Text Services Framework Addin</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="advanced_tsactivate.php">Prev</a> </td><th width="60%" align="center">Chapter 4. Advanced Help</th><td width="20%" align="right"> <a accesskey="n" href="advanced_richedit.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="advanced_tsf">The Text Services Framework Addin</h2></div></div></div><h3><a name="id630959"></a>What is the Text Services Framework?</h3><p>The Text Services Framework, or TSF, is a set of components for modern applications that support advanced input and text processing. It supports features such 
  as keyboard drivers, handwriting recognition, speech recognition,   as well as spell checking and other text processing functions.</p><p>The Language Bar is the core user interface for TSF. From the Language Bar, you can select the input language,   and control keyboard input, handwriting recognition and speech 
  recognition.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images%5Clanguage-bar.png"></span>
  </p><p>The most important advantage of using TSF with Keyman Desktop is that Keyman Desktop can read the current 'context' from the application. The 'context' is the characters on the screen around the insertion point. Earlier versions of Keyman Desktop remembered the context while inputting text, but as soon as an arrow key was pressed,   or the mouse clicked, Keyman Desktop would forget the context. This means that existing text can be edited in a   much more intuitive manner when using TSF.</p><h3><a name="id630697"></a>What applications support TSF?</h3><p>At the time of the release of Keyman Desktop 8.0, TSF was fully supported by some Windows Vista and Windows 7 components, along with Word XP, Word 2007 and Word 2010.   Other applications support TSF to a varying degree.</p><h3><a name="id630704"></a>Using Keyman Desktop with the TSF</h3><p>When Keyman Desktop is installed, it will also install a Keyman Desktop add-in that is registered as a text service. This service will be listed as a 'Keyboard layout/IME' in the TSF configuration   dialog with the name 'Tavultesoft Keyman Desktop TSF Addin'.  When the 
  Keyman Desktop text service is installed, it will become available for every language currently installed on your system.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>The Keyman Desktop TSF Addin is disabled by default in Keyman Desktop 8.0.  To enable it, open Keyman Desktop Configuration, select the <a class="link" href="basic_addins_tab.php" title="Keyman Configuration - Addins Tab">Addins tab</a>, select Text Services Framework Addin, and select Enable.
    </p></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>The Keyman Desktop TSF Addin is available only in Keyman Desktop Professional 8.0.</p></div><p>When you install another language, you will need to configure the Keyman Desktop TSF Addin to attach to   this language.  You can do this by clicking 'Configure…' in Keyman Desktop Configuration, Addins tab.</p><p>The Keyman Desktop text service only supports Unicode keyboard layouts.  To use older keyboard layouts, you should use the Keyman Desktop icon in the 
  system notification area to select your keyboard layout.</p><h3><a name="id631231"></a>How to: Select a Keyman keyboard layout with the Language Bar (Word 2002 and other TSF-enabled applications)</h3><div class="orderedlist"><ol type="1"><li>Select the language you wish to type in from the Language Bar.</li><li>Select Tavultesoft Keyman Desktop TSF Addin from the list of input methods for the language.</li><li>Select the Keyman keyboard layout from the Keyman menu in the Language Bar.</li></ol></div><h3><a name="id631250"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_addins_tab.php" title="Keyman Configuration - Addins Tab">Keyman Configuration - Addins Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="advanced_tsactivate.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="advanced.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="advanced_richedit.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">The Tavultesoft Online Activation Utility </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The RichEdit Addin</td></tr></table></div>
