<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Configuration - Languages Tab"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Languages Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_addins_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_support_tab.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_languages_tab">Keyman Configuration - Languages Tab</h2></div></div></div><p>The Languages tab of Keyman Configuration shows the current association between all of your installed Windows languages and your Keyman keyboards. You can use the Languages tab to associate Keyman keyboards with Windows languages and layouts. Associating a Keyman keyboard with a Windows language means turning on a Windows language will activate the Keyman keyboard.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/tab-languages.png"></span>
  </p><h3><a name="id627000"></a>Opening the Languages Tab</h3><p>To open the Languages tab of Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Languages tab.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Keyman Configuration opens in the same tab you last closed it in.</div></li></ol></div><h3><a name="id626727"></a>Associating Keyboards</h3><p>For help associating Keyman keyboards with Windows languages and layouts, see: <a class="xref" href="start_configure_computer.php" title="How To - Set up Your Computer for a Keyman Keyboard">How To - Set up Your Computer for a Keyman Keyboard</a></p><h3><a name="id626720"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="start_configure_computer.php" title="How To - Set up Your Computer for a Keyman Keyboard">How To - Set up Your Computer for a Keyman Keyboard</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_addins_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_support_tab.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Addins Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Configuration - Support Tab</td></tr></table></div>
