<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Configuration - Addins Tab"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Addins Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_languages_tab.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_addins_tab">Keyman Configuration - Addins Tab</h2></div></div></div><p>The Addins tab of Keyman Configuration lists the installed addins for Keyman Desktop. You can use the Addins tab to enable, disable and configure addins.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/tab-addins.png"></span>
  </p><h3><a name="id626884"></a>Opening the Addins Tab</h3><p>To open the Addins tab of Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Addins tab.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Keyman Configuration opens in the same tab you last closed it in.</div></li></ol></div><h3><a name="id626839"></a>Enabling, Disabling and Configuring Addins</h3><p>To enable, disable or configure a Keyman Desktop addin:</p><div class="orderedlist"><ol type="1"><li><p>Find an addin in the addins list.</p></li><li><p>Click on the down arrow (<span class="inlinemediaobject"><img src="desktop_images/keyboards-downarrow.png"></span>) beside the addin name. The addin information window will expand.</p><p>
						<span class="inlinemediaobject"><img src="desktop_images/addin.png"></span>
					</p></li><li><p>Click 'Enable', 'Disable' or 'Configure…' to enable, disable or configure your Keyman Desktop addin. Disabled addins appear greyed out in the Addins tab.</p></li></ol></div><h3><a name="id626793"></a>About Addins</h3><p>Keyman Desktop installs with the Text Services Framework addin and the RichEdit addin. For more information, see:</p><div class="itemizedlist"><ul type="disc"><li><p><a class="link" href="advanced_tsf.php" title="The Text Services Framework Addin">Text Services Framework addin</a></p></li><li><p><a class="link" href="advanced_richedit.php" title="The RichEdit Addin">RichEdit addin</a></p></li></ul></div><h3><a name="id626750"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="advanced_tsf.php" title="The Text Services Framework Addin">The Text Services Framework Addin</a>
      </p></li><li><p>
        <a class="xref" href="advanced_richedit.php" title="The RichEdit Addin">The RichEdit Addin</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_languages_tab.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Hotkeys Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Configuration - Languages Tab</td></tr></table></div>
