<?php
  require_once('includes/template.php');

  head([
    'title' => "Software Task - Purchase Keyman Desktop"
  ,'css' => ['template.css','keyboard.css','keys.css']]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Software Task - Purchase Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_trial.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_activate.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_purchase">Software Task - Purchase Keyman Desktop</h2></div></div></div><p>After a free 30-day trial, you must purchase a licence of Keyman Desktop to continue using the program.</p><h3><a name="id617152"></a>Where to buy a licence</h3><p>You can purchase a licence of Keyman Desktop from the Keyman Desktop splash screen by clicking the <span class="guibutton">Buy a License</span> button. You can also purchase a licence from the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Tavultesoft Online Store</a>.</p><p>If you are unable to purchase Keyman Desktop through Tavultesoft, you may also buy Keyman Desktop through Share-It! or one of our other authorised resellers:</p><div class="itemizedlist"><ul type="disc"><li><a class="ulink" href="https://secure.tavultesoft.com/buy/shareit.php" target="_blank">Share-It!</a></li><li><a class="ulink" href="https://secure.tavultesoft.com/resellers.php" target="_blank">Tavultesoft Authorised Resellers</a></li></ul></div><h3><a name="id621330"></a>How to buy a licence</h3><p>You can purchase a licence of Keyman Desktop with credit card, PayPal, Western Union, wire transfer, direct deposit, or Australian dollar cheque/money order.</p><p>If you are unable to purchase Keyman Desktop by any of these methods, contact <a class="ulink" href="mailto:sales@tavultesoft.com" target="_blank">sales@tavultesoft.com</a> for more help.</p><h3><a name="id621347"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="about_purchase.php" title="Licensing Information">Licensing Information</a>
      </p></li><li><p>
        <a class="xref" href="basic_activate.php" title="Software Task - Activate Keyman Desktop">Software Task - Activate Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_trial.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_activate.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Software Task - Trial Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Software Task - Activate Keyman Desktop</td></tr></table></div>
