<?php
  require_once('includes/template.php');

  head([
    'title' => "What's New"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">What's New</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="about_welcome.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman Desktop</th><td width="20%" align="right"> <a accesskey="n" href="about_purchase.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="about_whatsnew">What's New</h2></div></div></div><p>Here are some of the great things we have added to Keyman Desktop 9.0. </p><div class="itemizedlist"><ul type="disc"><li>Free Edition – Keyman Desktop now has a Free Edition with no restrictions on use – use it in your office, your home, your school.  Upgrade to Pro for powerful features, additional keyboards, and personalized technical support.</li><li>Rewritten for Windows 7, 8 and 8.1.  Now integrates deeply into Windows Text Services Framework and presents as a keyboard through all Windows language interfaces.  This means that keyboard input support is more consistent and more efficient in all applications.</li><li>Behind the scenes, Keyman is now fully Unicode internally.</li><li>User interface extensively redesigned, cleaned up and simplified.</li><li>Keyboards now support hi-res icons for clean presentation on large screens.</li><li>Keyboards now have more version information and online help integration.</li><li>Keyman now supports iPhone, iPad and Android – all your favourite keyboard layouts available on your phone and tablet devices</li></ul></div><h3><a name="id568425"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="about_history.php" title="Version History">Version History</a>
      </p></li><li><p>
        <a class="xref" href="basic_newways.php" title="New Ways to Use Keyman Desktop">New Ways to Use Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="about_welcome.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="about.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="about_purchase.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Welcome to Keyman Desktop 9.0 </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Licensing Information</td></tr></table></div>
