<?php
  require_once('includes/template.php');

  head([
    'title' => "Licensing Information"
  ]);
?>  
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Licensing Information</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="about_whatsnew.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman Desktop</th><td width="20%" align="right"> <a accesskey="n" href="about_requirements.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div>

<p class='note' style='background: #e0e0e0; padding: 8px; margin: 10px'><b>Important note</b>: All Keyman products are now available completely <a href='https://keyman.com/free'>free of charge</a>. The information on this page is out of date.</p>

<h2 class="title" style="clear: both" id="about_purchase">Licensing Information</h2></div></div></div><h3><a name="id568491"></a>Do I need a licence?</h3><p><span class="application">Keyman Desktop</span> is available as both a free and paid product. See the <a class="link" href="about_license.php" title="End User Licence and Services Agreement">End User Licence and Services Agreement</a> for more information.</p><h3><a name="id568500"></a>Where do I buy a licence? </h3><p><span class="application">Keyman Desktop Professional</span> can be purchased from the Keyman Desktop splash screen by clicking the <span class="guibutton">'Upgrade'</span> button. Keyman Desktop Professional can also be purchased from the Keyman website via the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Online Store</a> or from registered Tavultesoft agents.</p><h3><a name="id568527"></a>How much does a licence cost?</h3><p>Current pricing can be obtained from the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Online Store</a>.</p><h3><a name="id568531"></a>How can I pay for a licence? </h3><p>Available payment methods will differ depending on the seller you are purchasing from, but if you buy from Tavultesoft the recommended payment method is by credit card or PayPal.</p><h3><a name="id568536"></a>How do I use my licence? </h3><p>When you purchase a licence to use Keyman Desktop, you can enter the licence into the free version of Keyman Desktop. This will convert the free version into the fully licensed Professional version.</p><h3><a name="id568595"></a>How many computers can I install my licence on?</h3><p>The simple answer is that each licensed seat of Keyman Desktop is for a single computer. When you purchase Keyman Desktop, you will find a 'seat count' included in the licence details. A standard licence includes one seat, which should be used on one computer. If more than one person uses the same computer, you still only need a single licence - except in Citrix, Terminal Services, or similar environments.</p><p>The fuller answer is that Keyman Desktop licences are per concurrent-user seat (like MS Office). For systems running Citrix, Terminal Services, or similar software to enable concurrent use of Keyman by multiple users on the same computer, the number of licensed seats defines the maximum number of permitted concurrent users.</p><h3><a name="id568599"></a>Can I move my licence to another computer?</h3><p>You can move a licence to another computer, even after you have activated Keyman Desktop, by contacting Tavultesoft Support with your licence details and a note about moving the licence and the reason for the move (for example, purchasing a new computer, or replacing a computer that had a hardware failure). You must also uninstall Keyman Desktop from your original computer.</p><h3><a name="id568568"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
    <a class="xref" href="basic_activate.php" title="Software Task - Upgrade From Free To Professional Edition">Software Task - Upgrade From Free To Professional Edition</a>
   </p></li><li><p>
    <a class="xref" href="basic_manual_activate.php" title="Software Task - Manually Activate Keyman Desktop">Software Task - Manually Activate Keyman Desktop</a>
   </p></li><li><p>
    <a class="xref" href="basic_purchase.php" title="Software Task - Purchase Keyman Desktop Professional Edition">Software Task - Purchase Keyman Desktop Professional Edition</a>
   </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="about_whatsnew.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="about.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="about_requirements.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">What's New </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> System Requirements</td></tr></table></div>
