<?php
  require_once('includes/template.php');

  head([
    'title' => "Software Task - Uninstall Keyman Desktop"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Software Task - Uninstall Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_update.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_enable_keyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_uninstall">Software Task - Uninstall Keyman Desktop</h2></div></div></div><p>To uninstall Keyman Desktop:</p><div class="orderedlist"><ol type="1"><li><p>Close Keyman Desktop.</p></li><li><p>Open Windows Control Panel.</p></li><li><p>Select 'Add or Remove Programs' or 'Programs and Features' or 'Uninstall a program'.</p></li><li><p>Click Tavultesoft Keyman Desktop in the list.</p></li><li><p>Click <span class="guibutton">Remove</span> or <span class="guibutton">Uninstall</span> or right-click 'Uninstall'.</p></li><li><p>Follow the prompts to complete the uninstall.</p></li></ol></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You may install Keyman Desktop again at any time. When you install Keyman Desktop again on the same computer, your licence should still be activated and you should not need to activate your licence again.</div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>If you wish to transfer your Keyman Desktop licence to an alternate computer, please contact
Tavultesoft Support on <a class="ulink" href="" target="_blank">support@keyman.com</a> for 
assistance.</div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_update.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_enable_keyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Software Task - Update Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyboard Task - Turn on a Keyboard</td></tr></table></div>
