<?php
  require_once('includes/template.php');
  require_once('includes/__docheader.php');

  head([
    'title' => "Function: addEventListener"
  ]);
?>

<h1 class="title" id="core_addEventListener">addEventListener</h1>

<h2 id="Summary" name="Summary">Summary</h2>

<p>Adds an event listener for user-handling of KeymanWeb events.</p>

<?php
syntax("$kmw.addEventListener(event, func);");
params("event", "string", <<<END
The name of an event to be generated by the <code>$kmw</code> object.  Please see the <a href="../events">Events section</a>
for more details and examples.
END
, "func", "function", "A function to be called when the event is raised.  This function should expect a single parameter, ".
  "which will be set to the originally-generated event object.");
returns("boolean", "Returns <code>true</code> if successful, otherwise <code>false</code>.");
?>

<h2 id="Description" name="Description">Description</h2>

<p>Note: Standard HTML element events for the KeymanWeb element 
      (focus, blur, keydown, keypress, etc.) may be intercepted 
      and used to modify the user interface as necessary. 
      User-defined event handlers should normally return true 
      to allow other event handling to be processed normally.
</p>

<h2 id=""Example" name="Example">Example</h2>

<?=codebox(<<<END
$kmw.addEventListener('focus', function(e) {
  console.log("Now handling input for control " + e.target "!");
});
END
);?>