<?php
  require_once('includes/template.php');

  head([
    'title' => "Function: removeEventListener"
  ]);
  require_once('includes/__docheader.php');
?>

<h1 class="title" id="core_removeEventListener">removeEventListener</h1>

<h2 id="Summary" name="Summary">Summary</h2>

<p>Removes a user-defined event handler.</p>

<?php
syntax("$kmw.removeEventListener(event, func);");
params("event", "string", "The name of an event generated by the <code>$kmw</code> object.",
  "func", "function", "A function currently set to handle that event when it is raised.");
returns();
?>

<h2 id="Description" name="Description">Description</h2>

<p>
  See also:  <a href="addEventListener.php"><code><?="$kmw.addEventListener()"?></code></a>.
</p>
<p>To be implemented.
</p>