<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Welcome to Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_splash.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_langsetup.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_welcome">Welcome to Keyman Desktop</h2></div></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><span class="application">Keyman Desktop</span> must be installed and running     before a Keyman keyboard layout can be used. For help on installing <span class="application">Keyman Desktop</span>, please see <a class="xref" href="guide_install.php" title="Installing Keyman Desktop">Installing Keyman Desktop</a>.</div><p>When running <span class="application">Keyman Desktop</span> for the first time, the Welcome screen is displayed.</p><p>
    <span class="inlinemediaobject"><img src="images/context_welcome_01.png"></span>
  </p><p>There are four steps to start using <span class="application">Keyman Desktop</span>:</p><div class="orderedlist"><ol type="1"><li><p>Install a keyboard layout.</p><div class="itemizedlist"><ul type="disc"><li><p><a class="xref" href="context_downloadkeyboard.php" title="Download Keyboard from Tavultesoft Dialog">Download Keyboard from Tavultesoft Dialog</a>.</p></li><li><p><a class="xref" href="context_installkeyboard.php" title="Install Keyboard/Package Dialog">Install Keyboard/Package Dialog</a>.</p></li></ul></div></li><li><p>Start an application you would like to type in.</p></li><li><p>Enable the keyboard layout.</p><div class="orderedlist"><ol type="a"><li><p>Click on the <span class="application">Keyman Desktop</span> tray icon.</p></li><li><p>Select the keyboard layout you installed in step 1.</p></li></ol></div></li><li><p>Start typing!</p></li></ol></div><p>The <span class="guibutton">Get Started</span> button from the Welcome Screen can also take you on a short tutorial to introduce you to <span class="application">Keyman Desktop</span> (see <a class="xref" href="context_tutorial.php" title="Getting Started with Keyman Desktop">Getting Started with Keyman Desktop</a>).</p><h3><a name="id762226"></a>Turning off the Welcome Screen</h3><p>The Welcome screen will by default be displayed every time you run <span class="application">Keyman Desktop</span>. To turn it off, check the <span class="guilabel">Don't show this window again</span> checkbox and click <span class="guibutton">Close</span>.</p><p>You can turn on the Welcome screen again from the Options tab in Keyman Configuration.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_splash.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_langsetup.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Splash Screen </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Language Configuration Tasks dialog</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
