<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Download Keyboard from Tavultesoft Dialog</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_installkeyboard.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_traymenu.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_downloadkeyboard">Download Keyboard from Tavultesoft Dialog</h2></div></div></div><p>Clicking on the <span class="guibutton">Download Keyboard</span> button will display the Download Keyboard from Tavultesoft dialog box:</p><p>
    <span class="inlinemediaobject"><img src="images/context_downloadkeyboard_01.png"></span>
  </p><div class="orderedlist"><ol type="1"><li><p>Search for a keyboard layout by selecting the language or country appropriate from the       dropdown boxes, and clicking <span class="guibutton">Search</span>.</p></li><li><p>If the keyboard layout you want to install is available from the Tavultesoft       website, click the <span class="guibutton">Install Keyboard</span> button for that keyboard layout. You may also choose to download the keyboard layout without installing it by checking the <span class="guibutton">Don't install, just download</span> checkbox at the bottom of the dialog window.</p><p>If the keyboard layout is not available on the Tavultesoft website, but has       a link to an external website, clicking on that link will open the external       website in your web browser. From here, locate the keyboard layout download link and click on it.       Depending on your browser, this may save the keyboard layout or package to your computer or       attempt to install it into <span class="application">Keyman Desktop</span>. If it is saved to       your computer, see <a class="link" href="guide_keyboard_install.php#section.anchor.2">Installing a keyboard layout or package from a local folder.</a></p></li><li><p>When the <span class="guilabel">Install Keyboard/Package </span> dialog is displayed, click <span class="guibutton">Install</span> to install the keyboard layout or package.</p></li></ol></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If a keyboard layout with the same name is already installed, <span class="application">Keyman Desktop</span> will     confirm whether you want to replace the old keyboard layout or cancel the installation.</p></div><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>This dialog connects to the Tavultesoft Website.  No personal information is sent to   Tavultesoft in this process.  The information in this dialog may not be displayed in the same   language as the rest of the application, as it comes from a variety of sources.</p></div><h3><a name="id759960"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Configuration &#8211; Keyboard Layouts Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_installkeyboard.php" title="Install Keyboard/Package Dialog">Install Keyboard/Package Dialog</a>
      </p></li><li><p>
        <a class="xref" href="guide_keyboard_install.php" title="Installing a Keyboard Layout or Package">Installing a Keyboard Layout or Package</a>
      </p></li><li><p>
        <a class="xref" href="guide_keyboard_unload.php" title="Disabling a Keyboard Layout">Disabling a Keyboard Layout</a>
      </p></li><li><p>
        <a class="xref" href="context_keyman.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_installkeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_traymenu.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Install Keyboard/Package Dialog </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Desktop Icon and Menu</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
