<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">On Screen Keyboard - Keyboard View</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_onscreenkeyboard.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_osk_usage.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_osk_keyboard">On Screen Keyboard - Keyboard View</h2></div></div></div><p>The Keyboard View of the <a class="link" href="context_onscreenkeyboard.php" title="The On Screen Keyboard">On Screen Keyboard</a> shows the currently selected Keyman Desktop or Windows keyboard layout.</p><p>
    <span class="inlinemediaobject"><img src="images/osk_keyboard.png"></span>
  </p><p>When a <span class="application">Keyman Desktop</span> keyboard layout is selected, black keycaps will show the characters assigned to each key.  Many <span class="application">Keyman</span> keyboard layouts also show a second set of blue keycaps. These blue keycaps indicate the characters of the Windows keyboard associated with the current <span class="application">Keyman</span> keyboard layout.</p><p>When no <span class="application">Keyman Desktop</span> keyboard layout is selected, full-sized blue keycaps will display the characters of your chosen Windows keyboard.</p><h3><a name="id759485"></a>Using the On Screen Keyboard to type</h3><p>You can type using the On Screen Keyboard by clicking directly on the keycaps.  First, select where you want to start entering text into an application. Then, simply click on the keys to type as normal.  You can access Shift, Ctrl and Alt by clicking any of these keys on the keyboard first.  You can even mix inputs. For instance, if you hold the Shift key on your hardware keyboard, the On Screen Keyboard will automatically update to show the shifted keycaps.</p><h3><a name="id759466"></a>When no On Screen Keyboard keycaps are shown - Phonetic Keyboard Layouts</h3><p>Some Keyman Desktop keyboard layouts are designed phonetically and do not show any keycaps.  This is because there is not a simple 1-1 correspondence between each key and the letter you want to type.  For these keyboard layouts, the <a class="link" href="context_osk_usage.php" title="On Screen Keyboard - Usage View">Usage view</a> is often helpful and Keyman Desktop will switch to this      view by default.  This option can be changed in <a class="link" href="context_configuration_options.php" title="Keyman Configuration - Options Tab">Keyman Configuration</a>.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_onscreenkeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_osk_usage.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">The On Screen Keyboard </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> On Screen Keyboard - Usage View</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
