<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Desktop Icon and Menu</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_downloadkeyboard.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_activate.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_traymenu">Keyman Desktop Icon and Menu</h2></div></div></div><h3><a name="id760146"></a>Keyman Desktop Icon</h3><p>After starting <span class="application">Keyman Desktop</span>, the <span class="guiicon">Keyman Desktop Icon</span> is displayed on the Windows Taskbar, near the clock. This area is called the System Tray or System Notification Area.</p><p>
    <span class="inlinemediaobject"><img src="images%5Ctray.png"></span>
  </p><div class="itemizedlist"><ul type="disc"><li>Click on the Keyman Desktop Icon to display the Keyman Desktop Menu.</li><li>Double-click on the icon to show or hide the <a class="link" href="context_onscreenkeyboard.php" title="The On Screen Keyboard">On Screen Keyboard</a>.</li></ul></div><p>What to do if you cannot find the Keyman Desktop Icon:</p><div class="itemizedlist"><ul type="disc"><li>Make sure Keyman Desktop has been started.</li><li>If Keyman Desktop has been started, look for the digital clock on your screen.  The Keyman Desktop Icon will usually be displayed to the left of the clock.  If       you have turned off the clock, find the <em class="glossterm">Start Menu button</em> on the Taskbar and then look at the opposite end of the Taskbar for the Keyman Desktop Icon.</li><li>If the Taskbar is set to hide automatically (known as "Auto-hide"), you may have to move your mouse cursor around the edges of the screen to get the Taskbar to pop up.</li><li>Windows sometimes hides icons from the system tray to reduce clutter.  Click the expansion button <span class="inlinemediaobject"><img src="images%5Ctray_expansion.png"></span> to see if Windows has hidden the Keyman Desktop Icon.</li><li>If you have checked all these steps and still cannot locate the Keyman Desktop Icon, contact Tavultesoft Support for further assistance.</li></ul></div><h3><a name="id760230"></a>Keyman Desktop Menu</h3><p>Clicking on the <span class="guiicon">Keyman Desktop</span> icon with either mouse button     will bring up the Keyman Desktop menu.</p><div class="informaltable"><table border="0"><colgroup><col><col></colgroup><tbody><tr><td class="segmentedgraphic">
            <span class="inlinemediaobject"><img src="images%5Cmenu_1.png"></span>
          </td><td> </td></tr><tr><td class="segmentedgraphic">
            <span class="inlinemediaobject"><img src="images%5Cmenu_2.png"></span>
          </td><td>This section of the menu shows the list of Keyman Desktop keyboard layouts that you currently have loaded on your system.  You can             add further keyboard layouts to this menu through <a class="link" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Desktop Configuration, Keyboard Layouts tab</a>.</td></tr><tr><td class="segmentedgraphic">
            <span class="inlinemediaobject"><img src="images%5Cmenu_3.png"></span>
          </td><td>Return to your standard Windows keyboard layout.</td></tr><tr><td class="segmentedgraphic">
            <span class="inlinemediaobject"><img src="images%5Cmenu_4.png"></span>
          </td><td>These additional menu entries are described below.</td></tr></tbody></table></div><div class="variablelist"><dl><dt><span class="term">On Screen Keyboard</span></dt><dd>Displays or hides the <a class="link" href="context_onscreenkeyboard.php" title="The On Screen Keyboard">On Screen Keyboard</a> for the currently selected Keyman keyboard layout. If no Keyman keyboard layout is selected, the On Screen Keyboard displays the current Windows keyboard layout.</dd><dt><span class="term">Configuration...</span></dt><dd>Opens <a class="link" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Desktop Configuration</a>, where you can change options and add or remove keyboard layouts.</dd><dt><span class="term">Help...</span></dt><dd>Gives access to help on both the currently selected keyboard layout and the general Keyman Desktop help.</dd><dt><span class="term">Exit</span></dt><dd>Closes down Keyman Desktop.  Keyman keyboard layouts will not be available until Keyman Desktop is started again.</dd></dl></div><p>
    </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>The right and left button menus were merged in version 7.0.247.0 of Keyman Desktop.  Previously, keyboard layouts were on the       left click menu and other menu items were on the right click menu.</div><p>
  </p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_downloadkeyboard.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_activate.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Download Keyboard from Tavultesoft Dialog </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> 
    Activating Keyman Desktop
  </td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
