<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Language Configuration Tasks dialog</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_welcome.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_selectlanguage.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_langsetup">Language Configuration Tasks dialog</h2></div></div></div><p>Keyman Desktop displays the Language Configuration Tasks dialog when it detects that you have installed a keyboard layout which requires your system to be reconfigured.  Keyman Desktop will also display this dialog at startup if it detects that it needs to reconfigure your language settings.
  </p><p>The Language Configuration Tasks dialog lets you decide which recommended changes you make to your system. If you don't want to make a particular change, simply untick it in the list.
  </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>
      If you don't make the recommended changes to your system, Windows may not display your language correctly, or may corrupt the
      text you type.  This is particularly true for languages such as Hebrew or Arabic, which display right-to-left.  For these
      languages, it is critical you complete the tasks listed in the dialog.
    </p></div><h3><a name="id762256"></a>Disabling Language Configuration Task detection</h3><p>
    You can stop Language Configuration Tasks from prompting you to make changes by ticking the checkbox "Don't ask me about this again".
    If you select this option, Keyman Desktop will stop detecting the items you have left unticked, unless you access the dialog through Diagnostics, as described below.
  </p><h3><a name="id762206"></a>Accessing the Language Configuration Tasks dialog manually</h3><p>To access the Language Configuration Tasks dialog manually: from the <a class="link" href="context_configuration_support.php" title="Keyman Configuration - Support Tab">Support Tab</a> of Keyman Configuration, click the Diagnostics button and select Check Windows Language Settings. When you access the dialog through this link, all configuration tasks, including those previously disabled, will be displayed for your review.
  </p><h3><a name="id762190"></a>Language Configuration Tasks available</h3><p>The following items are currently checked by Keyman Desktop:</p><div class="itemizedlist"><ul type="disc"><li><a class="link" href="langsetup_psrtcomplexscript.php" title="Configure Complex Script Support">Complex script language support</a> - especially Indic and other Asian languages</li><li><a class="link" href="langsetup_psrtrtl.php" title="Configure Right-to-Left Script Support">Right-to-left language support</a> - especially Hebrew, Arabic and related languages</li><li><a class="link" href="langsetup_psrteuroscript.php" title="Configure European Script Support">European language support</a> - only on Windows 2000</li><li><a class="link" href="langsetup_psrtfareast.php" title="Configure East Asian Script Support">East Asian language support</a> - Chinese, Japanese, Korean</li><li><a class="link" href="langsetup_psrtmsofficelanguage.php" title="Configure Microsoft Office Language Support">Microsoft Office Language Settings</a></li><li><a class="link" href="langsetup_psrtsupplementary.php" title="Configure Supplementary Plane Support">Supplementary character support</a></li><li><a class="link" href="langsetup_psrtwindowslanguage.php" title="Configure Windows Language">Installed Windows languages</a></li><li><a class="link" href="langsetup_psrtuniscribe.php" title="Enable Keyman Uniscribe Manager">Uniscribe display support and version</a></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_welcome.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_selectlanguage.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Welcome to Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Select Language</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
