<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 5. Context Help</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="langsetup_psrtwindowslanguage.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="context_tutorial.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="context"><div class="titlepage"><div><div><h2 class="title">Chapter 5. Context Help</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="context_tutorial.php">Getting Started with Keyman Desktop</a></span></dt><dt><span class="section"><a href="context_keyman.php">Keyman Desktop Configuration</a></span></dt><dt><span class="section"><a href="context_configuration_keyboards.php">Keyman Configuration &#8211; Keyboard Layouts Tab</a></span></dt><dt><span class="section"><a href="context_configuration_options.php">Keyman Configuration - Options Tab</a></span></dt><dt><span class="section"><a href="context_configuration_hotkeys.php">Keyman Configuration - HotKeys Tab</a></span></dt><dt><span class="section"><a href="context_configuration_addins.php">Keyman Configuration - Addins Tab</a></span></dt><dt><span class="section"><a href="context_configuration_languages.php">Keyman Configuration - Languages Tab</a></span></dt><dt><span class="section"><a href="context_configuration_support.php">Keyman Configuration - Support Tab</a></span></dt><dt><span class="section"><a href="context_installkeyboard.php">Install Keyboard/Package Dialog</a></span></dt><dt><span class="section"><a href="context_downloadkeyboard.php">Download Keyboard from Tavultesoft Dialog</a></span></dt><dt><span class="section"><a href="context_traymenu.php">Keyman Desktop Icon and Menu</a></span></dt><dt><span class="section"><a href="context_activate.php">
    Activating Keyman Desktop
  </a></span></dt><dt><span class="section"><a href="context_manualactivate.php">Manually Activating Keyman Desktop</a></span></dt><dt><span class="section"><a href="context_tsactivate.php">Using Tavultesoft Online Activation Utility</a></span></dt><dt><span class="section"><a href="context_onscreenkeyboard.php">The On Screen Keyboard</a></span></dt><dt><span class="section"><a href="context_osk_keyboard.php">On Screen Keyboard - Keyboard View</a></span></dt><dt><span class="section"><a href="context_osk_usage.php">On Screen Keyboard - Usage View</a></span></dt><dt><span class="section"><a href="context_font_helper.php">On Screen Keyboard - Font Helper</a></span></dt><dt><span class="section"><a href="context_character_map.php">On Screen Keyboard - Character Map</a></span></dt><dt><span class="section"><a href="context_splash.php">Splash Screen</a></span></dt><dt><span class="section"><a href="context_welcome.php">Welcome to Keyman Desktop</a></span></dt><dt><span class="section"><a href="context_langsetup.php">Language Configuration Tasks dialog</a></span></dt><dt><span class="section"><a href="context_selectlanguage.php">Select Language</a></span></dt><dt><span class="section"><a href="context_onlineupdate.php">Online Update</a></span></dt><dt><span class="section"><a href="context_proxyconfiguration.php">Proxy Configuration</a></span></dt></dl></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="langsetup_psrtwindowslanguage.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="context_tutorial.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Configure Windows Language </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Getting Started with Keyman Desktop</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
