<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Options Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_configuration_keyboards.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_configuration_hotkeys.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_configuration_options">Keyman Configuration - Options Tab</h2></div></div></div><p>
    <span class="inlinemediaobject"><img src="images/context_configuration_options_01.png"></span>
  </p><h3><a name="id758797"></a>General</h3><p>
    <span class="inlinemediaobject"><img src="images/context_options_general.png"></span>
  </p><div class="itemizedlist"><ul type="disc"><li><p>Keyboard hotkeys toggle keyboard activation</p><p>When selected, a keyboard layout hotkey will toggle the keyboard layout on and off, instead of just switching it on.</p></li><li><p>Simulate AltGr with Ctrl+Alt:</p><p>Some hardware keyboards do not have a right alt or AltGr key, particularly some notebooks. When this option is         selected, pressing Ctrl+Alt will be equivalent to pressing right alt or AltGr.</p></li><li><p>Show hint messages:</p><p>Hints are automatically shown at certain times during the usage of Keyman Desktop.  Once you are familiar with the program, you will probably         want to switch these off.  This can be done on a case-by-case basis, or this option will switch all the hints off, across the whole program.</p></li><li><p>The Reset Hints button:</p><p>The Reset Hints button switches all Keyman hints on again, even those that you have switched off on a case-by-case basis.</p></li></ul></div><h3><a name="id758862"></a>Startup</h3><p>
    <span class="inlinemediaobject"><img src="images/context_options_startup.png"></span>
  </p><div class="itemizedlist"><ul type="disc"><li><p>Start when Windows starts</p><p>Select this option to have <span class="application">Keyman Desktop</span> start automatically when you turn on your computer.</p></li><li><p>Show splash screen</p><p>The <span class="application">Keyman Desktop</span> Splash screen is the screen that shows when Keyman Desktop is starting up.  This option will only be enabled if <span class="application">Keyman Desktop</span> has been activated.</p></li><li><p>Show welcome screen</p><p>This option can be used to turn on or off the Welcome screen which normally shows after <span class="application">Keyman Desktop</span> has started and gives you pointers on how to start using Keyman Desktop.</p></li><li><p>Automatically check www.tavultesoft.com weekly for updates.</p><p>When checked, <span class="application">Keyman Desktop</span> will automatically check for program updates on the Tavultesoft website once a week. No personally identifiable information is sent to Tavultesoft in this process. If this box is not checked, Keyman Desktop can be updated manually through the Support tab in the Configuration menu.</p></li><li><p>Test for conflicting applications when Keyman Desktop starts:</p><p>Some applications are not written according to the Windows software development standards and can cause           problems with keyboard input.  Keyman Desktop can detect these applications and work around them when it           starts up.</p></li></ul></div><h3><a name="id758958"></a>On Screen Keyboard</h3><p>
    <span class="inlinemediaobject"><img src="images/context_options_osk.png"></span>
  </p><div class="itemizedlist"><ul type="disc"><li><p>Release Shift/Ctrl/Alt on On Screen Keyboard after clicking a key:</p><p>The default behaviour of the On Screen Keyboard is to keep the Ctrl/Shift/Alt keys down once they have been clicked, until they are clicked again,       or the user presses the keys on the hardware keyboard.  This option will make the keys automatically reset after another key is clicked.</p></li><li><p>Always show On Screen Keyboard Window when Keyman keyboard is selected:</p><p>When you select a Keyman Desktop keyboard layout, the On Screen Keyboard window will pop up to show you how to use the keyboard layout.  Once you are          familiar with a keyboard layout, you might wish to turn this option off.</p></li><li><p>Switch to appropriate On Screen Keyboard/Help automatically when a keyboard is selected</p><p>When this option is selected, Keyman Desktop will detect whether it is most appropriate to display either the On Screen Keyboard view or the Keyboard Usage view for a selected keyboard layout. The display will be switched automatically whenever you change keyboard layouts. If this option is deselected, then Keyman Desktop will not detect and switch its display automatically.</p></li></ul></div><h3><a name="id756700"></a>Advanced</h3><p>
    <span class="inlinemediaobject"><img src="images/context_options_advanced.png"></span>
  </p><div class="itemizedlist"><ul type="disc"><li><p>Turn on Unicode supplementary character display (requires restart)</p><p>This option is available under Windows 2000, XP, Server 2003. If unselected, you will not be able to view text that uses <a class="ulink" href="http://unicode.org/glossary/index.php#supplementary_code_point" target="_blank">supplementary code points</a>, which are outside the Unicode Basic Multilingual Plane.  This option is on by default in Windows Vista. Windows 95, 98, Me and NT4 are unable to display supplementary characters in most situations.</p></li><li><p>Turn on 'Unknown' language:</p><p>This will install the 'Unknown' language in Control Panel.  This option is available for legacy reasons         and should not be used in most situations.</p></li><li><p>Debugging</p><p>Turning debugging on will create a log file in a folder called <span class="guilabel">keymanlog</span> on the user's desktop. This log file will contain information about <span class="application">Keyman Desktop</span> processes that can be helpful for resolving issues. You should not need to use this option unless specifically requested by Tavultesoft in relation to an issue you are experiencing.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>It is very important that you switch off this option after obtaining the log file         as the file can grow in size very quickly!</p></div><div class="warning" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Warning</h3><p>Privacy Warning - debug mode records every keystroke into the log file, including logins and passwords!           For this reason, it is important that you always keep this option switched off unless specifically            instructed by Tavultesoft support staff.  Tavultesoft only recommends switching the debug log on for            short and isolated tests.</p></div></li><li><p>Switch Windows language when a Keyman keyboard is selected</p><p>When this option is selected, choosing a Keyman keyboard layout from the Keyman menu or the On Screen Keyboard         will automatically switch the Windows language at the same time.  This is highly desirable for right-to-left languages and some complex script languages.</p></li><li><p>Enable Keyman Uniscribe Manager</p><p>This option activates the Keyman Uniscribe Manager, which makes the features of the latest version of Uniscribe available on Windows 2000 and Windows XP. The Keyman Uniscribe manager enables applications running on these operating systems to correctly display Tibetan, Khmer and many other languages.  For more information on the Keyman Uniscribe Manager, please read the reference documentation.</p></li></ul></div><h3><a name="id756586"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_keyman.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Configuration &#8211; Keyboard Layouts Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_hotkeys.php" title="Keyman Configuration - HotKeys Tab">Keyman Configuration - HotKeys Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_addins.php" title="Keyman Configuration - Addins Tab">Keyman Configuration - Addins Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_languages.php" title="Keyman Configuration - Languages Tab">Keyman Configuration - Languages Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_support.php" title="Keyman Configuration - Support Tab">Keyman Configuration - Support Tab</a>
      </p></li><li><p>
        <a class="xref" href="ref_uniscribe.php" title="Keyman Uniscribe Manager">Keyman Uniscribe Manager</a>
      </p></li><li><p>
        <a class="xref" href="guide_install.php" title="Installing Keyman Desktop">Installing Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_configuration_keyboards.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_configuration_hotkeys.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration &#8211; Keyboard Layouts Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Configuration - HotKeys Tab</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
