<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Setting a Hotkey</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="guide_keyboard_install.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Step by Step Guides</th><td width="20%" align="right"> <a accesskey="n" href="guide_keyboard_unload.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="guide_hotkey_set">Setting a Hotkey</h2></div></div></div><p>A hotkey is a keyboard layout shortcut. In <span class="application">Keyman Desktop</span> these are used to access some standard functions and to enable and disable installed keyboard layouts.</p><p>To set the hotkey for a <span class="application">Keyman Desktop</span> option:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="application">Keyman Desktop</span> icon<span class="inlinemediaobject"><img src="images/tray_01.png"></span>in the system tray.</p></li><li><p>From the Keyman menu select Configuration.</p></li><li><p>Select Hotkeys from the tabs along the left-hand side.</p><p></p></li><li><p>Click on the hotkey link of the option or keyboard layout you want to change. The       Change Hotkey dialog box will be displayed.</p><p>
        <span class="inlinemediaobject"><img src="images/context_configuration_hotkeys_02.png"></span>
      </p></li><li><p>Type the hotkey you wish to use. For example, to set a hotkey to Ctrl + Alt + M, press the Ctrl, Alt and M keys together. This will give the following:</p><p>
        <span class="inlinemediaobject"><img src="images/context_configuration_hotkeys_03.png"></span>
      </p><p>If you press a single letter or Shift plus a single letter, the hotkey will default to Ctrl + Alt + the letter you pressed to avoid conflicts with standard input. Be aware that you can set the hotkey to replace standard Windows hotkeys (Ctrl + C, Ctrl + V, etc).</p><p>To clear a hotkey that has been set previously, click <span class="guibutton">Clear Hotkey</span> or press Backspace.</p></li><li><p>Click <span class="guibutton">OK</span> to save your selection.</p></li><li><p>Click <span class="guibutton">OK</span> again from the Configuration window to apply the changes.</p></li></ol></div><p>The new hotkey will now be displayed as in the image below:</p><p>
    <span class="inlinemediaobject"><img src="images/context_configuration_hotkeys_04.png"></span>
  </p><h3><a name="id756159"></a>Setting a hotkey for keyboard layouts</h3><p>In addition to the method above, you can set hotkeys for installed keyboard layouts from the Keyboard Layouts tab of Keyman Configuration.</p><div class="orderedlist"><ol type="1"><li><p>Click on the Keyman Desktop icon<span class="inlinemediaobject"><img src="images/tray_01.png"></span>in the system tray.</p></li><li><p>From the Keyman menu select <span class="guimenuitem">Configuration</span>.</p></li><li><p>Select Keyboard Layouts from the tabs along the left-hand side.</p></li><li><p>Click on the <span class="guibutton">Options</span> button for the keyboard layout you wish to set a hotkey for.</p></li><li><p>Select <span class="guimenuitem">Change Hotkey</span>.</p></li><li><p>Type the hotkey you wish to use. For example, to set a hotkey to Ctrl + Alt + M, press the Ctrl, Alt and M keys together. This will give the       following:</p><p>
        <span class="inlinemediaobject"><img src="images/context_configuration_hotkeys_03.png"></span>
      </p><p>If you press a single letter or Shift plus a single letter, the hotkey will default to Ctrl + Alt + the letter you pressed to avoid conflicts with standard input. Be aware that you can set the hotkey to replace standard Windows hotkeys (Ctrl + C, Ctrl + V, etc).</p><p>To clear a hotkey that has been set previously, click <span class="guibutton">Clear Hotkey</span> or press Backspace.</p></li><li><p>Click <span class="guibutton">OK</span> to save your selection.</p></li><li><p>Click <span class="guibutton">OK</span> again from the Configuration window to apply the changes.</p></li></ol></div><p>The new hotkey will now be displayed in that keyboard layout's row in the list.</p><h3><a name="id756284"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_configuration_hotkeys.php" title="Keyman Configuration - HotKeys Tab">Keyman Configuration - HotKeys Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="guide_keyboard_install.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="guide.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="guide_keyboard_unload.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Installing a Keyboard Layout or Package </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Disabling a Keyboard Layout</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
