<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Disabling a Keyboard Layout</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="guide_hotkey_set.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Step by Step Guides</th><td width="20%" align="right"> <a accesskey="n" href="guide_keyboard_uninstall.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="guide_keyboard_unload">Disabling a Keyboard Layout</h2></div></div></div><p>Disabling a keyboard layout in Keyman Desktop will remove it from the keyboard layout selection menu but will not uninstall the keyboard layout. This is useful if:</p><div class="itemizedlist"><ul type="disc"><li><p>You are using a single keyboard layout from a package with multiple keyboard layouts and want to remove the unused keyboard layouts from the Keyboard Layout selection menu.</p></li><li><p>You have a keyboard layout installed which you aren't currently using but don't want to uninstall.</p></li></ul></div><p>You can disable a keyboard layout using the following steps:</p><div class="orderedlist"><ol type="1"><li><p>Click on the Keyman Desktop icon<span class="inlinemediaobject"><img src="images%5Ctray_01.png"></span>in the system tray.</p></li><li><p>From the Keyman menu select Configuration.</p></li><li><p>Select Keyboard Layouts from the tabs along the left-hand side.</p></li><li><p>Clear the checkbox beside the <span class="guibutton">Options</span> button in the desired keyboard layout's row in the list.</p></li><li><p>Click on <span class="guibutton">OK</span>.</p></li></ol></div><p>When a keyboard layout is disabled, its name appears in grey and its checkbox is cleared.</p><p>You can re-enable a disabled keyboard layout by clicking on the checkbox again.</p><h3><a name="id755290"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="guide_keyboard_uninstall.php" title="Uninstalling a Keyboard Layout">Uninstalling a Keyboard Layout</a>
      </p></li><li><p>
        <a class="xref" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Configuration &#8211; Keyboard Layouts Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="guide_hotkey_set.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="guide.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="guide_keyboard_uninstall.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Setting a Hotkey </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Uninstalling a Keyboard Layout</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
