<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Installing a Keyboard Layout or Package</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="guide_install.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Step by Step Guides</th><td width="20%" align="right"> <a accesskey="n" href="guide_hotkey_set.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="guide_keyboard_install">Installing a Keyboard Layout or Package</h2></div></div></div><p>Keyman Desktop is a program designed to allow you to type in multiple languages and scripts from a single computer keyboard.  In order for Keyman Desktop to function, you must first install specific keyboard layouts. These keyboard layouts are what enable a single computer keyboard to type in alternate languages and scripts. You can install keyboard layouts onto your system in Keyman Configuration.</p><p>There are two methods of installing a <span class="application">Keyman Desktop</span> keyboard layout or package: you can either install directly from your local computer, or download and install from the <span class="application">Tavultesoft</span> website.</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="application">Keyman</span> icon<span class="inlinemediaobject"><img src="images%5Ctray_01.png"></span>in the system tray.</p><p>The <span class="application">Keyman</span> menu is displayed:</p><p>
        <span class="inlinemediaobject"><img src="images%5Cmenu.png"></span>
      </p></li><li><p>Select Configuration.</p></li><li><p>Select Keyboard Layouts from the tabs along the left-hand side. Then continue with either set of instructions below, as appropriate</p></li></ol></div><h3><a name="id755783"></a>
    <a name="section.anchor.2"></a>Installing a keyboard layout or package from a local folder</h3><div class="orderedlist"><ol type="1"><li><p>Click <span class="guibutton">Install Keyboard</span>.</p></li><li><p>Find the keyboard layout or package file, select it and click <span class="guibutton">Open</span>. The Install Keyboard/Package window will be displayed, with information about the keyboard layout or package being installed.</p></li><li><p>Click <span class="guibutton">Install</span> to install the keyboard layout or package.</p></li></ol></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If a keyboard layout with the same name is already installed, <span class="application">Keyman Desktop</span> will confirm whether you want to replace the old keyboard layout or cancel the installation.</p></div><h3><a name="id755841"></a>Installing a keyboard layout or package from the Tavultesoft website</h3><div class="orderedlist"><ol type="1"><li><p>Click <span class="guibutton">Download Keyboard</span>. This will display the <span class="guilabel">Download Keyboard from Tavultesoft</span> dialog.</p></li><li><p>Search for a keyboard layout by selecting the language or country appropriate from the         dropdown boxes and clicking <span class="guibutton">Search</span>.</p></li><li><p>If the keyboard layout you want to install is available from the Tavultesoft         website, click the <span class="guibutton">Install Keyboard</span> button for that keyboard layout. You may also choose to download the keyboard layout without installing it by checking the <span class="guibutton">Don't install, just download</span> checkbox at the bottom of the dialog window.</p><p>If the keyboard layout is not available on the Tavultesoft website, but has a link to an external website, clicking on that link will open the external website in your web browser. From here, locate the keyboard layout download link and click on it. Depending on your browser, this may save the keyboard layout or package to your computer or attempt to install it into <span class="application">Keyman Desktop</span>. If it is saved to your computer, install it by following the instructions above for <a class="link" href="guide_keyboard_install.php#section.anchor.2">Installing a keyboard layout or package from a local folder.</a></p></li><li><p>When the <span class="guilabel">Install Keyboard/Package</span> dialog is displayed, click <span class="guibutton">Install</span> to install the keyboard layout or package.</p></li></ol></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If a keyboard layout with the same name is already installed, <span class="application">Keyman Desktop</span> will confirm whether you want to replace the old keyboard layout or cancel the installation.</p></div><h3><a name="id755926"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Configuration &#8211; Keyboard Layouts Tab</a>
      </p></li><li><p>
        <a class="xref" href="context_installkeyboard.php" title="Install Keyboard/Package Dialog">Install Keyboard/Package Dialog</a>
      </p></li><li><p>
        <a class="xref" href="context_downloadkeyboard.php" title="Download Keyboard from Tavultesoft Dialog">Download Keyboard from Tavultesoft Dialog</a>
      </p></li><li><p>
        <a class="xref" href="guide_keyboard_uninstall.php" title="Uninstalling a Keyboard Layout">Uninstalling a Keyboard Layout</a>
      </p></li><li><p>
        <a class="xref" href="guide_keyboard_unload.php" title="Disabling a Keyboard Layout">Disabling a Keyboard Layout</a>
      </p></li><li><p>
        <a class="xref" href="context_keyman.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="guide_install.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="guide.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="guide_hotkey_set.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Installing Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Setting a Hotkey</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
