<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Configure Microsoft Office Language Support</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="langsetup_psrtfareast.php">Prev</a> </td><th width="60%" align="center">Chapter 4. Language Configuration Tasks Documentation</th><td width="20%" align="right"> <a accesskey="n" href="langsetup_psrtrtl.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="langsetup_psrtmsofficelanguage">Configure Microsoft Office Language Support</h2></div></div></div><p>If Microsoft Office 2000 or later is installed on your system, Keyman Desktop will automatically configure it to work in the language of your chosen keyboard layout.  This      is required for editing some languages, such as right-to-left languages, or some complex script languages.</p><p>This will also control autocorrection, spell checking and other language-specific features throughout Microsoft Office.  Depending on the version of Office that you have installed, you may have to restart Office applications before the changes will take effect.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="langsetup_psrtfareast.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="langsetup.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="langsetup_psrtrtl.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Configure East Asian Script Support </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Configure Right-to-Left Script Support</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
