<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 4. Language Configuration Tasks Documentation</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="ref_uniscribe.php">Prev</a> </td><th width="60%" align="center"> </th><td width="20%" align="right"> <a accesskey="n" href="langsetup_psrtcomplexscript.php">Next</a></td></tr></table><hr></div><div class="chapter" lang="en" id="langsetup"><div class="titlepage"><div><div><h2 class="title">Chapter 4. Language Configuration Tasks Documentation</h2></div></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt><span class="section"><a href="langsetup_psrtcomplexscript.php">Configure Complex Script Support</a></span></dt><dt><span class="section"><a href="langsetup_psrteuroscript.php">Configure European Script Support</a></span></dt><dt><span class="section"><a href="langsetup_psrtfareast.php">Configure East Asian Script Support</a></span></dt><dt><span class="section"><a href="langsetup_psrtmsofficelanguage.php">Configure Microsoft Office Language Support</a></span></dt><dt><span class="section"><a href="langsetup_psrtrtl.php">Configure Right-to-Left Script Support</a></span></dt><dt><span class="section"><a href="langsetup_psrtsupplementary.php">Configure Supplementary Plane Support</a></span></dt><dt><span class="section"><a href="langsetup_psrtuniscribe.php">Enable Keyman Uniscribe Manager</a></span></dt><dt><span class="section"><a href="langsetup_psrtwindowslanguage.php">Configure Windows Language</a></span></dt></dl></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="ref_uniscribe.php">Prev</a> </td><td width="20%" align="center"> </td><td width="40%" align="right"> <a accesskey="n" href="langsetup_psrtcomplexscript.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Uniscribe Manager </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Configure Complex Script Support</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
