<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Welcome to Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="main.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman Desktop</th><td width="20%" align="right"> <a accesskey="n" href="main_whatsnew.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="main_welcome">Welcome to Keyman Desktop</h2></div></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>
      <span class="application">Keyman Desktop</span> must be installed and running       before a Keyman keyboard layout can be used. For help on installing <span class="application">Keyman Desktop</span>, please see <a class="xref" href="guide_install.php" title="Installing Keyman Desktop">Installing Keyman Desktop</a>.</p></div><h3><a name="id754616"></a>What is Keyman Desktop?</h3><p>Keyman Desktop is a keyboard reconfiguration program.  It allows you to remap your hardware keyboard to input in any language.  For example, the standard English QWERTY keyboard can be remapped to allow you to type in Amharic.  Keyboard layouts for many languages are available on the <a class="ulink" href="" target="_blank"> Keyman Keyboards Website</a>, or you can use <a class="ulink" href="" target="_blank">Keyman Developer</a> to create your own keyboard layout for a language.</p><p>Keyman Desktop is the program which allows you to use the your downloaded or self-created keyboard layout. You can use your keyboard layout with Keyman Desktop in almost any Windows application, such as Word, Internet Explorer, Outlook, or Adobe InDesign.  Keyman Desktop fully supports <a class="ulink" href="" target="_blank"> Unicode</a>, as well as legacy codepage-based applications.</p><p>
    <span class="inlinemediaobject"><img src="images%5Cosk_keyboard.png"></span>
  </p><p>The image above shows Keyman Desktop's On Screen Keyboard, with a Devanagari keyboard layout loaded.</p><p>Keyman Desktop includes features such as an on-screen keyboard, phonetic and visual-order     input methods, and seamless integration with the Windows XP Language Bar. A full list of     features in Keyman Desktop 7.0 is available <a class="link" href="main_whatsnew.php" title="What's New in Keyman Desktop">here</a>.</p><h3><a name="id754667"></a>Supported Platforms</h3><p>Keyman Desktop 7.0 supports the following operating systems:</p><div class="itemizedlist"><ul type="disc"><li><p>Microsoft Windows 95</p></li><li><p>Microsoft Windows 98</p></li><li><p>Microsoft Windows Me</p></li><li><p>Microsoft Windows NT 4.0 (SP6 and later)</p></li><li><p>Microsoft Windows 2000</p></li><li><p>Microsoft Windows XP</p></li><li><p>Microsoft Windows Server 2003</p></li><li><p>Microsoft Windows Vista</p></li><li><p>Microsoft Windows Server 2008</p></li></ul></div><p>There are differences in the way Keyman Desktop works in some of these operating systems.  Older     versions of Windows do have some limitations for specific languages, and will need extra effort     in configuration.  Windows Vista and later versions include extra security, which means that some     configuration actions will require you to confirm security prompts.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="main.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="main.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="main_whatsnew.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 1. About Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> What's New in Keyman Desktop</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
