<?php
  require_once('includes/template.php');

  head([
    'title' => "Class Names and Identifiers for On-Screen Keyboard and Other KeymanWeb Elements"
  ]);
?>
<h1 class="title" id="classes">Class Names and Identifiers for On-Screen Keyboard and Other KeymanWeb Elements</h1>

  <p>
    The appearance of the <span class="emphasis"><em>KeymanWeb</em></span> on-screen keyboard, menu amd other elements can be customized
    by a web designer by redefining (or adding to) the default styles.  Styles and named elements
    all have the class name (or id) prefix <span class="emphasis"><em>kmw-</em></span> joined to the object and item names,
    for example <span class="emphasis"><em>kmw-key-text</em></span>, to set the basic style for the keycap text on each on-screen keyboard key.
    Multiple classes are applied to many objects, with top-level classes of <span class="emphasis"><em>tablet</em></span>,
    <span class="emphasis"><em>phone</em></span> and <span class="emphasis"><em>desktop</em></span> used to set different element styles according to the device type.
    Unique elements, such as the menu and pop-up key frame, are named rather than referred to by class.
  </p><p>Most visual attributes such as text size and colour, background colour, shading, margins, etc. can be varied
    according to preference but developers should avoid changing positional attributes.
  </p><p class="h5">
    Class names applied to on-screen keyboard elements:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name</th><th align="left">Keyboard element</th></tr></thead><tbody><tr><td class="rowhead" align="left">kmw-osk-frame</td><td align="left">Outer keyboard frame</td></tr><tr><td class="rowhead" align="left">kmw-osk-inner-frame</td><td align="left">Inner keyboard frame</td></tr><tr><td class="rowhead" align="left">kmw-key-layer-group</td><td align="left">Keyboard layers container element</td></tr><tr><td class="rowhead" align="left">kmw-key-layer</td><td align="left">Keyboard layer element</td></tr><tr><td class="rowhead" align="left">kmw-key-row</td><td align="left">Keyboard row container element</td></tr><tr><td class="rowhead" align="left">kmw-key-square</td><td align="left">Keyboard key container element</td></tr><tr><td class="rowhead" align="left">kmw-key-square-ex</td><td align="left">Pop-up key container element</td></tr><tr><td class="rowhead" align="left">kmw-key</td><td align="left">Key element</td></tr><tr><td class="rowhead" align="left">kmw-key-label</td><td align="left">Key label (desktop OSK and phonetic layouts)</td></tr><tr><td class="rowhead" align="left">kmw-key-text</td><td align="left">Keycap text</td></tr><tr><td class="rowhead" align="left">kmw-key-popup-icon</td><td align="left">Text or graphic to indicate that a keyboard key has associated popup keys</td></tr><tr><td class="rowhead" align="left">kmw-spacebar-caption</td><td align="left">Style applied to caption on spacebar</td></tr></tbody></table></div><p class="h5">
    Class names applied to different types of keys:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name</th><th align="left">Key style</th></tr></thead><tbody><tr><td class="rowhead" align="left">kmw-key-default</td><td align="left">Default</td></tr><tr><td class="rowhead" align="left">kmw-key-shift</td><td align="left">Shift key</td></tr><tr><td class="rowhead" align="left">kmw-key-shift-on</td><td align="left">Active shift key</td></tr><tr><td class="rowhead" align="left">kmw-key-deadkey</td><td align="left">Dead key</td></tr><tr><td class="rowhead" align="left">kmw-key-blank</td><td align="left">Blank key (unmapped)</td></tr><tr><td class="rowhead" align="left">kmw-key-hidden</td><td align="left">Hidden key (spacer)</td></tr><tr><td class="rowhead" align="left">kmw-key-touched</td><td align="left">Active (touched) key</td></tr></tbody></table></div><p class="h5">
    Element identifiers and class names for desktop on-screen keyboard elements:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name or id</th><th align="left">Desktop OSK element</th></tr></thead><tbody><tr><td class="rowhead" align="left">kmw-title-bar</td><td align="left">OSK title bar</td></tr><tr><td class="rowhead" align="left">kmw-title-bar-caption</td><td align="left">OSK title bar caption (keyboard name)</td></tr><tr><td class="rowhead" align="left">kmw-title-bar-actions</td><td align="left">Container for image elements in OSK title bar</td></tr><tr><td class="rowhead" align="left">kmw-title-bar-image</td><td align="left">Active image element in OSK title bar</td></tr><tr><td class="rowhead" align="left">kmw-footer</td><td align="left">Desktop OSK footer element</td></tr><tr><td class="rowhead" align="left">kmw-footer-caption</td><td align="left">Caption in desktop OSK footer</td></tr><tr><td class="rowhead" align="left">kmw-footer-resize</td><td align="left">Style for resizing icon</td></tr><tr><td class="rowhead" align="left">kmw-osk-static</td><td align="left">Container style for non-sizable keyboards</td></tr><tr><td class="rowhead" align="left">kmw-osk-none</td><td align="left">Empty keyboard container style</td></tr><tr><td class="rowhead" align="left">#kmw-pin-image</td><td align="left">Style of icon to return OSK to default position</td></tr><tr><td class="rowhead" align="left">#kmw-config-image</td><td align="left">Style of icon to open configuration options window</td></tr><tr><td class="rowhead" align="left">#kmw-help-image</td><td align="left">Style of icon to open keymanweb help window</td></tr><tr><td class="rowhead" align="left">#kmw-close-button</td><td align="left">Style of close button image</td></tr></tbody></table></div><p class="h5">
    Element identifiers and class names applied to pop-up key container elements:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name or id</th><th align="left">Element</th></tr></thead><tbody><tr><td class="rowhead" align="left">#kmw-popup-keys</td><td align="left">Pop-up key container</td></tr><tr><td class="rowhead" align="left">arrow-border</td><td align="left">Style setting callout arrow border</td></tr><tr><td class="rowhead" align="left">arrow-content</td><td align="left">Style setting callout arrow background</td></tr></tbody></table></div><p class="h5">
    Element identifiers and class names applied to language menu elements:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name</th><th align="left">Menu element</th></tr></thead><tbody><tr><td class="rowhead" align="left">#kmw-language-menu</td><td align="left">Language menu container element</td></tr><tr><td class="rowhead" align="left">#kmw-language-menu-background</td><td align="left">Hidden background layer preventing unwanted action while selecting a language or keyboard.</td></tr><tr><td class="rowhead" align="left">#kmw-menu-scroll-container</td><td align="left">Container for language list scroller</td></tr><tr><td class="rowhead" align="left">#kmw-menu-scroller</td><td align="left">Language list scroller</td></tr><tr><td class="rowhead" align="left">#kmw-menu-index</td><td align="left">Container for language index</td></tr><tr><td class="rowhead" align="left">#kmw-menu-footer</td><td align="left">Placeholder at bottom of scroller</td></tr><tr><td class="rowhead" align="left">kbd-list</td><td align="left">Style for language list element</td></tr><tr><td class="rowhead" align="left">kbd-list-open</td><td align="left">Style for list element when expanded</td></tr><tr><td class="rowhead" align="left">kbd-list-closed</td><td align="left">Style for list element when not expanded</td></tr><tr><td class="rowhead" align="left">kmw-list-entry</td><td align="left">Language entry in language list</td></tr><tr><td class="rowhead" align="left">kmw-single-entry</td><td align="left">Single keyboard entry in language list</td></tr><tr><td class="rowhead" align="left">current</td><td align="left">Active keyboard entry in language list</td></tr><tr><td class="rowhead" align="left">selected</td><td align="left">Touched entry in language list</td></tr></tbody></table></div><p class="h5">
    Message box class names:
  </p><div class="informaltable"><table border="1"><colgroup><col align="left"><col align="left"></colgroup><thead><tr><th align="left">Class name</th><th align="left">Element</th></tr></thead><tbody><tr><td class="rowhead" align="left">kmw-wait-box</td><td align="left">Message box</td></tr><tr><td class="rowhead" align="left">kmw-wait-background</td><td align="left">Message box background</td></tr><tr><td class="rowhead" align="left">kmw-wait-text</td><td align="left">Message box wait text</td></tr><tr><td class="rowhead" align="left">kmw-wait-graphic</td><td align="left">Message box wait icon</td></tr><tr><td class="rowhead" align="left">kmw-alert-text</td><td align="left">Message box alert text</td></tr><tr><td class="rowhead" align="left">kmw-alert-close</td><td align="left">Message box close icon</td></tr></tbody></table></div><p>
    The default styles for any released build of <span class="emphasis"><em>KeymanWeb</em></span> can be found on line, for example,
    <a class="ulink" href="https://s.keyman.com/kmw/engine/339/osk/kmwosk.css" target="_blank">https://s.keyman.com/kmw/engine/339/osk/kmwosk.css</a> for Build 339.
  </p></div>