<?php
  require_once('includes/template.php');

  head([
    'title' => "The Tavultesoft Online Activation Utility"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">The Tavultesoft Online Activation Utility</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="advanced_proxy_config.php">Prev</a> </td><th width="60%" align="center">Chapter 4. Advanced Help</th><td width="20%" align="right"> <a accesskey="n" href="advanced_language_config.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="advanced_tsactivate">The Tavultesoft Online Activation Utility</h2></div></div></div><p>When you <a class="link" href="basic_manual_activate.php" title="Software Task - Manually Activate Keyman Desktop">manually activate</a> Keyman Desktop using the removable disk
  activation method, the <span class="application">Tavultesoft Online Activation Utility</span> is saved to your removable disk. It will run automatically 
  when you insert the disk into another computer.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If the utility does not run automatically, you should use Explorer to browse to your removable disk and double-click to start the <span class="application">tsactivate</span> program.</p></div><p>Once the Tavultesoft Online Activation Utility is running on a computer with internet access, click <span class="guibutton">Activate…</span> at the prompt 
  and wait for the activation process to complete. Then, return your removable disk to the computer where you installed Keyman Desktop and continue 
  with step three of the <a class="link" href="basic_manual_activate.php" title="Software Task - Manually Activate Keyman Desktop">Manual Activation</a> dialog.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>The Online Activation Utility supports activating multiple computers in one go. If you need to activate Keyman Desktop on multiple computers, you should 
    run the Manual Activation Step 1 on each computer in turn before proceeding to Step 2. Once you have begun Step 2, you can choose not to activate a computer by unselecting 
    it from the list of activation files before clicking <span class="guibutton">Activate…</span>. Please note that on a multiple install you MUST make sure
    that each computer has a unique name, as the activation request files are given the same name as the computer.</p><p>
  </p></div><h3><a name="id589101"></a>The Online Activation Utility Dialog</h3><p>The Welcome screen of the <span class="application">Tavultesoft Online Utility</span> explains the basic instructions for manually 
  activating <span class="application">Keyman Desktop</span> using a removable disk.</p><span class="inlinemediaobject"><img src="desktop_images/tsactivate_01.png"></span><p>The Request Computer Code screen allows you to quickly enter and save multiple <span class="application">Keyman Desktop</span> licences from multiple computers.</p><span class="inlinemediaobject"><img src="desktop_images/tsactivate_02.png"></span><p>When running on a computer with internet access, the Activate Online screen processes your activation request via the Tavultesoft servers. If you want to load
  activation request data from different folder than the one suggested, click <span class="guibutton">Browse…</span>. You can choose not to activate a computer by unselecting it from
  the list of activation files. If you access the Internet through a proxy server, you can also configure proxy settings by clicking <span class="guibutton">Proxy Settings…</span>.</p><p>The activation log will show you whether or not each computer has had a successful activation.  Activation can fail if the Tavultesoft Online Activation
  Utility cannot access the Internet, or cannot contact the Tavultesoft website, or if you have already activated all the computers that your licence covers.</p><span class="inlinemediaobject"><img src="desktop_images/tsactivate_03.png"></span><p>The Apply Activation screen is an alternate way to load activation responses easily on multiple computers. Once you have loaded an activation response on a computer,
  that computer's licence of <span class="application">Keyman Desktop</span> is activated.</p><span class="inlinemediaobject"><img src="desktop_images/tsactivate_04.png"></span><h3><a name="id589178"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_manual_activate.php" title="Software Task - Manually Activate Keyman Desktop">Software Task - Manually Activate Keyman Desktop</a>
      </p></li><li><p>
        <a class="xref" href="basic_activate.php" title="Software Task - Upgrade From Free To Professional Edition">Software Task - Upgrade From Free To Professional Edition</a>
      </p></li><li><p>
        <a class="xref" href="about_purchase.php" title="Licensing Information">Licensing Information</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="advanced_proxy_config.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="advanced.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="advanced_language_config.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Proxy Configuration </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Language Configuration Tasks</td></tr></table></div>
