<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyman Configuration - Support Tab"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Configuration - Support Tab</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_support_tab">Keyman Configuration - Support Tab</h2></div></div></div><p>The Support tab of Keyman Configuration displays Keyman Desktop version information and support tools. You can use the Support tab to send a support request, check Windows language settings, check for updates, and view Keyman Desktop version information.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/tab-support.png"></span>
  </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>Important! Only Pro Edition users have access to personal support direct from Tavultesoft. Free Edition users can access support via the Keyman Community Forum.</p></div><h3><a name="id588684"></a>Opening the Support Tab</h3><p>To open the Support tab of Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p></li><li><p>From the Keyman Desktop menu, select <span class="guilabel">Configuration…</span>.</p></li><li><p>Select the Support tab.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>Keyman Configuration opens in the same tab you last closed it in.</div></li></ol></div><h3><a name="id588729"></a>Collecting Diagnostic Information</h3><p>You can collect diagnostic information about Keyman by clicking the 'Diagnostics' link under the 'Useful Links' section. The support diagnostic will collect critical diagnostic information from your computer and generate a report.</p><h3><a name="id588711"></a>Checking Windows Language Settings</h3><p>You can run a test to see if your Windows language settings are correct for your currently installed Keyman keyboards. To run a test:</p><div class="orderedlist"><ol type="1"><li><p>Click 'Check Language Settings' in the Support tab of Keyman Configuration. The link is under the 'Useful Links' section on the right.</p><p>
  </p></li><li><p>You will then see one of two possible screens:</p><div class="itemizedlist"><ul type="disc"><li><p>If all settings are correct, click <span class="guibutton">OK</span>.</p><p>
              <span class="inlinemediaobject"><img src="desktop_images/support-settingsok.png"></span>
          </p></li><li><p>Otherwise, you will be presented with the Language Configuration Tasks menu. You have three options:</p><p>
            <span class="inlinemediaobject"><img src="desktop_images/language-tasks.png"></span>
          </p><div class="itemizedlist"><ul type="circle"><li><p>Click <span class="guibutton">Apply</span> to apply the suggested configuration tasks.</p></li><li><p>Click <span class="guibutton">Remind me Later</span> to make the decision the next time you restart Keyman Desktop.</p></li><li><p>Tick 'Don't ask me about this again' and click <span class="guibutton">OK</span> to reject the suggested configuration tasks.</p></li></ul></div></li></ul></div></li></ol></div><h3><a name="id588836"></a>Checking for Updates</h3><p>To check for Keyman Desktop updates, from the Support tab of Keyman Configuration click the 'Check for Updates' link. You can also download and install Keyman Desktop again from the Tavultesoft website.</p><h3><a name="id588846"></a>About Version Information</h3><p>You can view version details from the Support tab of Keyman Configuration. In the Support tab you will see:</p><div class="itemizedlist"><ul type="disc"><li>Version Detals
    <div class="itemizedlist"><ul type="circle"><li><p>Edition — Details on your current edition of Keyman Desktop.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If you are running Keyman Desktop Free Edition, you will see an <span class="guibutton">Upgrade to Professional…</span> button at the bottom left of the Keyman Configuration menu. If you are running Keyman Desktop Professional you will not see any buttons at the bottom left of Keyman Configuration.</p></div></li><li><p>Version — The current Keyman Desktop version number</p></li></ul></div></li></ul></div><h3><a name="id588865"></a>Sending a Support Request</h3><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>This feature is only available in Keyman Desktop Professional.</div><p>To send a support request through to Tavultesoft:</p><div class="itemizedlist"><ul type="disc"><li><p>Click <span class="guibutton">Send Support Request</span></p></li><li><p>In the pop up, enter information regarding your request. Please be as detailed as possible.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/support-request.png"></span>
      </p></li><li><p>Click the <span class="guibutton">Send Request</span> button. Your support request will be sent through to Tavultesoft, along with a diagnostic report from Keyman. You will need to have internet access for this to send successfully.</p><p>Replies to your support request will be sent to the email address you registered your account with.</p></li></ul></div><p>After sending a support request, you will receive an automatic reply acknowledging that Tavultesoft has received your request. You can reply to this email if you wish to add any further information or have any attachments.</p><h3><a name="id588925"></a>Accessing the Keyman Community Forum</h3><p>Free Edition users will only have support via the Keyman Community Forum. Professional Edition users can also use this feature if they so choose.</p><div class="itemizedlist"><ul type="disc"><li><p>Click the <span class="guibutton">Open Keyman Community Forum</span> button. The forums will open in your internet browser. You will need to have internet access for this to open successfully.</p></li></ul></div><h3><a name="id588992"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman Desktop">How To - Download and Install Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_hotkeys_tab.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_help.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Configuration - Hotkeys Tab </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The Keyman Desktop Help Menu</td></tr></table></div>
