
!include ..\..\..\Defines.mak
!include ..\Defines.mak

all:    tute_A_01.html \
        tute_A_02.html \
        tute_A_03.html \
        tute_A_04.html \
        tute_A_05.html \
        tute_A_06.html \
        tute_A_07.html \
        tute_A_08.html \
        tute_A_09.html \
        tute_A_10.html \
        tute_A_11.html

clean:
  -del *.html

.php.html:
  $(PHP) $< > $@
