<?php
  require_once('includes/template.php');

  head([
    'title' => "Function: addEventListener"
  ]);

  require_once('includes/__docheader.php')
?>

<h1 class="title" id="addEventListener">addEventListener</h1>

<h2 id="Summary" name="Summary">Summary</h2>

<p>Adds an event listener for user-handling of On-Screen keyboard events.</p>

<?php
syntax("$kmw.osk.addEventListener(eventName, func)");
params("eventName", "string", "The name of an event generated by the <code>$kmw.osk</code> object.  ".
  "See <a href='../events'>the Events section</a> for details and examples.",
  "func", "function(Object)", "A function to be called when the event is raised.");
returns("boolean");
?>

<h2 id="Description" name="Description">Description</h2>

<p>Standard HTML element events for the On-Screen Keyboard element may 
      also be intercepted and used to modify the user interface if necessary.
</p>