<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Desktop Configuration</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_tutorial.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_configuration_keyboards.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_keyman">Keyman Desktop Configuration</h2></div></div></div><p>To open Keyman Configuration:</p><div class="orderedlist"><ol type="1"><li><p>Click on the <span class="application">Keyman Desktop</span> icon<span class="inlinemediaobject"><img src="images%5Ctray_01.png"></span>in the system tray.</p><p>A menu is displayed:</p><p><span class="inlinemediaobject"><img src="images%5Cmenu.png"></span></p></li><li><p>From the menu select Configuration or click on the title, Keyman Desktop 7.0, to display the Keyman Configuration window. </p><p><span class="inlinemediaobject"><img src="images%5Ccontext_configuration_tabs_01.png"></span></p></li></ol></div><p>Keyman Configuration is used to install keyboard layouts, modify <span class="application">Keyman Desktop</span> options, configure hotkeys and language layouts and activate <span class="application">Keyman Desktop</span>.</p><p>For more information on these functions, please see:</p><div class="itemizedlist"><ul type="disc"><li><p><a class="xref" href="context_configuration_keyboards.php" title="Keyman Configuration &#8211; Keyboard Layouts Tab">Keyman Configuration &#8211; Keyboard Layouts Tab</a></p></li><li><p><a class="xref" href="context_configuration_options.php" title="Keyman Configuration - Options Tab">Keyman Configuration - Options Tab</a></p></li><li><p><a class="xref" href="context_configuration_hotkeys.php" title="Keyman Configuration - HotKeys Tab">Keyman Configuration - HotKeys Tab</a></p></li><li><p><a class="xref" href="context_configuration_addins.php" title="Keyman Configuration - Addins Tab">Keyman Configuration - Addins Tab</a></p></li><li><p><a class="xref" href="context_configuration_languages.php" title="Keyman Configuration - Languages Tab">Keyman Configuration - Languages Tab</a></p></li><li><p><a class="xref" href="context_configuration_support.php" title="Keyman Configuration - Support Tab">Keyman Configuration - Support Tab</a></p></li><li><p><a class="xref" href="context_activate.php" title="Activating Keyman Desktop">
    Activating Keyman Desktop
  </a></p></li></ul></div><h3><a name="id758134"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_splash.php" title="Splash Screen">Splash Screen</a>
      </p></li><li><p>
        <a class="xref" href="context_traymenu.php" title="Keyman Desktop Icon and Menu">Keyman Desktop Icon and Menu</a>
      </p></li><li><p>
        <a class="xref" href="guide_install.php" title="Installing Keyman Desktop">Installing Keyman Desktop</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_tutorial.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_configuration_keyboards.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Getting Started with Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Configuration &#8211; Keyboard Layouts Tab</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
