<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">On Screen Keyboard - Font Helper</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="context_osk_usage.php">Prev</a> </td><th width="60%" align="center">Chapter 5. Context Help</th><td width="20%" align="right"> <a accesskey="n" href="context_character_map.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="context_font_helper">On Screen Keyboard - Font Helper</h2></div></div></div><p>The Font Helper tool in the <a class="link" href="context_onscreenkeyboard.php" title="The On Screen Keyboard">On Screen Keyboard</a> identifies fonts on your system that should work with the currently selected keyboard layout.</p><p>
    <span class="inlinemediaobject"><img src="images%5Cosk_fonthelper.png"></span>
  </p><p>Before you begin typing with a keyboard layout, in your application you should select one of the fonts which Font Helper lists as having the greatest compatibility with your language.  Every application has its own method for selecting fonts.  A common place to look is the Format menu or the toolbar of the application.</p><p>Each font listed in the Font Helper includes a percentage value.  This value indicates how many characters in the current keyboard layout are available from the font.  Most of the time, fonts with greater than 90% coverage will work for nearly all texts.</p><p>If no fonts are listed in this view, check the documentation of the keyboard layout to see if it includes information on where to obtain the fonts you need.</p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="context_osk_usage.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="context.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context_character_map.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">On Screen Keyboard - Usage View </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> On Screen Keyboard - Character Map</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
