<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Configure Windows Language</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="langsetup_psrtuniscribe.php">Prev</a> </td><th width="60%" align="center">Chapter 4. Language Configuration Tasks Documentation</th><td width="20%" align="right"> <a accesskey="n" href="context.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="langsetup_psrtwindowslanguage">Configure Windows Language</h2></div></div></div><p>Keyman Desktop will detect when you need to install a Windows language.  It will automatically install the language in Control Panel/Regional and Language Options, and     link the relevant Keyman Desktop keyboard layout to that language.</p><p>After Keyman Desktop has installed the language, you will see the new language listed in the<em class="glossterm">Language Bar</em>. You may choose to switch keyboard layouts using the Language Bar or using the <a class="link" href="context_traymenu.php" title="Keyman Desktop Icon and Menu">Keyman Desktop menu</a>.  Keyman Desktop will     automatically manage the link between the Windows language and the Keyman Desktop keyboard layout.</p><h3><a name="id757881"></a>Managing Windows Languages</h3><p>Keyman Desktop Configuration includes a <a class="link" href="context_configuration_languages.php" title="Keyman Configuration - Languages Tab">Languages tab</a> where you can see the currently installed      Windows keyboard layouts and which Keyman keyboard layouts they are associated with.</p><h3><a name="id757893"></a>Why is this important?</h3><p>Linking your keyboard layouts to a Windows language is important for a number of reasons:</p><div class="itemizedlist"><ul type="disc"><li>Right-to-left and complex script languages may not display correctly in some applications unless you install the Windows language first.</li><li>Tagging the text you type with a relevant language code ensures that applications will not corrupt your text or "autocorrect" it</li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="langsetup_psrtuniscribe.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="langsetup.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="context.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Enable Keyman Uniscribe Manager </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Chapter 5. Context Help</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
