<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Purchasing Keyman Desktop</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="main_license.php">Prev</a> </td><th width="60%" align="center">Chapter 1. About Keyman Desktop</th><td width="20%" align="right"> <a accesskey="n" href="main_credits.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="main_purchasing_keyman">Purchasing Keyman Desktop</h2></div></div></div><h3><a name="id754876"></a>Who must register?</h3><p>
    <span class="application">Keyman Desktop</span>is made available as trial software.  You may use Keyman Desktop freely for up to 30 days for evaluation purposes.  After such time, you must purchase a licence to continue using Keyman Desktop or uninstall it. See the <a class="link" href="main_license.php" title="Keyman® Desktop End User Licence and Services Agreement">End User Licence and Services Agreement</a> for more information.  When you purchase a licence to continue using Keyman Desktop, you can enter this into the trial version, which will convert the trial version into the fully licensed version.</p><h3><a name="id754859"></a>How to Purchase</h3><p>
    <span class="application">Keyman Desktop</span>can be purchased directly from Tavultesoft via the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Tavultesoft Online Store</a> or from registered Tavultesoft agents.</p><p>Clicking the <span class="guibutton">Buy</span> button on the splash screen will open the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Tavultesoft Online Store</a> in your web browser.</p><h3><a name="id754833"></a>Pricing</h3><p>Current pricing can be obtained from the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Tavultesoft Online Store</a>.</p><h3><a name="id754820"></a>Payment methods</h3><p>Available payment methods will differ depending on the seller you are purchasing       from, but if purchasing from Tavultesoft the recommended payment method is by       credit card over the Internet at the Tavultesoft Online Store. Other payment methods       available from the Tavultesoft Online Store are PayPal Online, Western Union,        Wire Transfer/Direct Deposit and Cheque/Money Order. For more information on these methods,       please visit the <a class="ulink" href="https://secure.tavultesoft.com/buy/" target="_blank">Tavultesoft Online Store</a> or contact Tavultesoft.</p><h3><a name="id755127"></a>Moving a licence to another computer</h3><p>You can move a licence to another computer, even after you have activated Keyman Desktop, by contacting Tavultesoft Support (<a class="ulink" href="mailto:support@tavultesoft.com" target="_blank">support@tavultesoft.com</a>)       with your licence details and a note about moving the licence and the reason for the move (for example,       purchasing a new computer, or replacing a computer that had a hardware failure).</p><h3><a name="id755139"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="context_activate.php" title="Activating Keyman Desktop">
    Activating Keyman Desktop
  </a>
      </p></li><li><p>
        <a class="xref" href="context_manualactivate.php" title="Manually Activating Keyman Desktop">Manually Activating Keyman Desktop</a>
      </p></li><li><p>
        <a class="xref" href="guide_install.php" title="Installing Keyman Desktop">Installing Keyman Desktop</a>
      </p></li><li><p>
        <a class="xref" href="context_splash.php" title="Splash Screen">Splash Screen</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="main_license.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="main.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="main_credits.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman® Desktop End User Licence and Services Agreement </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Credits</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
