<?php
  require_once('includes/template.php');
  
  head([
    'title' => 'Keyman Support | Type to the world in your language',
    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']
  ]);
?>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyman Desktop and the Text Services Framework</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="ref_locale.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Reference Documentation</th><td width="20%" align="right"> <a accesskey="n" href="ref_uniscribe.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="ref_tsf">Keyman Desktop and the Text Services Framework</h2></div></div></div><h3><a name="id738871"></a>What is the Text Services Framework?</h3><p>The Text Services Framework, or TSF, is a set of components for modern applications that support advanced   input and text processing. It supports features such as keyboard drivers, handwriting recognition, speech recognition,   as well as spell checking and other text processing functions.</p><p>The Language Bar is the core user interface for TSF. From the Language Bar, you can select the input language,   and control keyboard input, handwriting recognition and speech recognition.</p><p>
    <span class="inlinemediaobject"><img src="images%5Cref_tsf_languagebar.png"></span>
  </p><p>The most important advantage of using TSF with Keyman Desktop is that Keyman Desktop can read the current "context"   from the application. The "context" is the characters on the screen around the insertion point. Previous   versions of Keyman Desktop remembered the context while inputting text, but as soon as an arrow key was pressed,   or the mouse clicked, Keyman Desktop would forget the context. This means that existing text can be edited in a   much more intuitive manner when using TSF.</p><h3><a name="id757350"></a>What applications support TSF?</h3><p>At the time of the release of Keyman Desktop 7.0, TSF was fully supported by many Windows Vista components, along with Word XP (2002) and later versions.   Other applications support TSF to a varying degree.</p><h3><a name="id757342"></a>Using Keyman Desktop with the TSF</h3><p>When Keyman Desktop is installed, it will also install a Keyman Desktop add-in that is registered as a   text service. This service will be listed as a "Keyboard layout/IME" in the TSF configuration   dialog with the name "Tavultesoft Keyman Desktop TSF Addin".  When the Keyman Desktop text   service is installed, it will become available for every language currently installed on your system.</p><p>When you install another language, you will need to configure the Keyman Desktop TSF Addin to attach to   this language.  You can do this by clicking the Configure button in Keyman Desktop Configuration, Addins tab.</p><p>The Keyman Desktop text service only supports Unicode keyboard layouts.  To use older keyboard layouts, you should use the Keyman Desktop icon in the system notification area to select your keyboard layout.</p><h3><a name="id757328"></a>How to: Select a Keyman keyboard layout with the Language Bar (Word 2002 and other TSF-enabled applications)</h3><div class="orderedlist"><ol type="1"><li>Select the language you wish to type in from the Language Bar.</li><li>Select Tavultesoft Keyman Desktop TSF Addin from the list of input methods for the language.</li><li>Select the Keyman keyboard layout from the Keyman menu in the Language Bar.</li></ol></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="ref_locale.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="ref_uniscribe.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Translating the Keyman Desktop User Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyman Uniscribe Manager</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
