<?php
  require_once('includes/template.php');

  head([
    'title' => "Keyboard Task - Turn on a Keyboard"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Keyboard Task - Turn on a Keyboard</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_uninstall.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_disable_keyboard.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_enable_keyboard">Keyboard Task - Turn on a Keyboard</h2></div></div></div><p>Here are five simple ways to turn on a Keyman keyboard. </p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>To use a Keyman keyboard, the keyboard must be enabled in the Keyboard Layouts tab of Keyman Configuration. For help enabling your keyboard, see: <a class="xref" href="basic_disable_keyboard.php" title="Keyboard Task - Enable and Disable a Keyboard">Keyboard Task - Enable and Disable a Keyboard</a></div><h3><a name="id580550"></a>Turning on a Keyboard from the Keyman Menu</h3><p>To turn on a keyboard from the Keyman menu:</p><div class="orderedlist"><ol type="1"><li><p>Open an application to type in, like MS Word.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You need to have an application open for your Keyman keyboard to load correctly.</div></li><li><p>Start Keyman Desktop.</p></li><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/menu.png"></span>
    </p></li><li><p>Select your Keyman keyboard from the list. You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p></li></ol></div><h3><a name="id580572"></a>Turning on a Keyboard from the Keyman Toolbox</h3><p>To turn on a keyboard from the Keyman Toolbox:</p><div class="orderedlist"><ol type="1"><li><p>Open an application to type in, like MS Word.</p></li><li><p>Start Keyman Desktop.</p></li><li><p>Click on the <span class="guiicon">Keyman Desktop</span> icon <span class="inlinemediaobject"><img src="desktop_images/icon-keyman.png"></span>, on the Windows Taskbar near the clock.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/menu.png"></span>
    </p></li><li><p>Click to open the On Screen Keyboard view of the Keyman Toolbox.</p><p>
        <span class="inlinemediaobject"><img src="desktop_images/osk-tibetan.png"></span>
    </p></li><li><p>Click to select your Keyman keyboard from the toolbar of the Keyman Toolbox. You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p></li></ol></div><h3><a name="id582434"></a>Turning on a Keyboard from the Language Switcher</h3><p>Here's how to turn on a keyboard using the Language Switcher:</p><div class="orderedlist"><ol type="1"><li><p>Open an application to type in, like MS Word.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You need to have an application open for your Keyman keyboard to load correctly.</div></li><li><p>Start Keyman Desktop.</p></li><li><p>Press the Language Switcher hotkey to bring up the Language Switcher. If you are using the default Language Switcher hotkey (<span class="keycap"><strong>Left.Alt</strong></span> + <span class="keycap"><strong>Shift</strong></span>) or another hotkey with <span class="keycap"><strong>Alt</strong></span>, you will need to press and HOLD the <span class="keycap"><strong>Alt</strong></span> part of the hotkey and press and RELEASE the last key in the hotkey to use the Language Switcher. When you release <span class="keycap"><strong>Alt</strong></span>, the Language Switcher will close.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>By default, the Language Switcher hotkey is <span class="keycap"><strong>Left.Alt</strong></span> + <span class="keycap"><strong>Shift</strong></span>.  You can view or change the current Language Switcher hotkey from the <a class="link" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Hotkeys tab</a> of Keyman Configuration.</p></div><p>
        <span class="inlinemediaobject"><img src="desktop_images/languageswitcher-small.png"></span>
    </p></li><li><p>Navigate the Language Switcher using the arrow keys or by pressing <span class="keycap"><strong>Shift</strong></span> to select your Keyman keyboard.</p></li><li><p>Release the Language Switcher hotkey or press <span class="keycap"><strong>Enter</strong></span> to activate the selected keyboard and close the Language Switcher. You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p></li></ol></div><h3><a name="id582569"></a>Turning on a Keyboard with a Hotkey</h3><p>To turn on a keyboard from the Keyman menu:</p><div class="orderedlist"><ol type="1"><li><p>Open an application to type in, like MS Word.</p></li><li><p>Start Keyman Desktop.</p></li><li><p>Press and release the hotkey for your Keyman keyboard.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You can find the current hotkey for your keyboard in the Keyman menu. You can set or reset a hotkey for your keyboard from the <a class="link" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Hotkeys tab</a> of Keyman Configuration.</div><p>
        <span class="inlinemediaobject"><img src="desktop_images/menu.png"></span>
    </p></li><li><p>You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p></li></ol></div><h3><a name="id582646"></a>Turning on a Keyboard by switching Windows languages</h3><p>Because Keyman keyboards are always associated with a Windows language, turning on that Windows language will automatically turn on the Keyman keyboard. If a Windows keyboard is also associated with the language, or multiple Keyman keyboards are associated with the language, an extra icon will appear next to the Windows language that will allow you to choose the keyboard you want to use.</p><span class="inlinemediaobject"><img src="desktop_images/lang-assoc-multi.png"></span><h3><a name="id582622"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_traymenu.php" title="The Keyman Desktop Menu">The Keyman Desktop Menu</a>
      </p></li><li><p>
        <a class="xref" href="basic_toolbox.php" title="The Keyman Desktop Toolbox">The Keyman Desktop Toolbox</a>
      </p></li><li><p>
        <a class="xref" href="basic_languageswitcher.php" title="Language Switcher">Language Switcher</a>
      </p></li><li><p>
        <a class="xref" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Keyman Configuration - Hotkeys Tab</a>
      </p></li><li><p>
        <a class="xref" href="basic_keyboards_tab.php" title="Keyman Configuration - Keyboard Layouts Tab">Keyman Configuration - Keyboard Layouts Tab</a>
      </p></li><li><p>
        <a class="xref" href="start_download-install_keyboard.php" title="How To - Download and Install a Keyman Keyboard">How To - Download and Install a Keyman Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_disable_keyboard.php" title="Keyboard Task - Enable and Disable a Keyboard">Keyboard Task - Enable and Disable a Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="troubleshooting_hidden.php" title="How To - Fix A Problem with an Active Keyman Keyboard Not Typing">How To - Fix A Problem with an Active Keyman Keyboard Not Typing</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_uninstall.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_disable_keyboard.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Software Task - Uninstall Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Keyboard Task - Enable and Disable a Keyboard</td></tr></table></div>
