<?php
  require_once('includes/template.php');

  head([
    'title' => "Language Switcher"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Language Switcher</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="basic_charactermap.php">Prev</a> </td><th width="60%" align="center">Chapter 3. Basic Help</th><td width="20%" align="right"> <a accesskey="n" href="basic_text_editor.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="basic_languageswitcher">Language Switcher</h2></div></div></div><p>The Keyman Desktop Language Switcher is a single popup menu to let you rapidly switch between any installed Keyman keyboard, Windows language or Windows layout.</p><p>
    <span class="inlinemediaobject"><img src="desktop_images/languageswitcher.png"></span>
  </p><h3><a name="id570136"></a>Opening and Using the Language Switcher</h3><p>To open and use the Keyman Desktop Language Switcher </p><div class="orderedlist"><ol type="1"><li><p>Press the Language Switcher hotkey to bring up the Language Switcher. If you are using the default Language Switcher hotkey (<span class="keycap"><strong>Left.Alt</strong></span> + <span class="keycap"><strong>Shift</strong></span>) or another hotkey with <span class="keycap"><strong>Alt</strong></span>, you will need to press and HOLD the <span class="keycap"><strong>Alt</strong></span> part of the hotkey and press and RELEASE the last key in the hotkey to use the Language Switcher. When you release <span class="keycap"><strong>Alt</strong></span>, the Language Switcher will close.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>By default, the Language Switcher hotkey is <span class="keycap"><strong>Left.Alt</strong></span> + <span class="keycap"><strong>Shift</strong></span>.  You can view or change the current Language Switcher hotkey from the <a class="link" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Hotkeys tab</a> of Keyman Configuration.</p></div><p>
        <span class="inlinemediaobject"><img src="desktop_images/languageswitcher-small.png"></span>
    </p></li><li><p>Navigate the Language Switcher using the arrow keys or by pressing <span class="keycap"><strong>Shift</strong></span> to select your Keyman keyboard.</p></li><li><p>Release the Language Switcher hotkey or press <span class="keycap"><strong>Enter</strong></span> to activate the selected keyboard and close the Language Switcher. You will notice the Keyman menu icon change to the icon of your Keyman keyboard. This means your Keyman keyboard is on.</p></li></ol></div><h3><a name="id570216"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="basic_traymenu.php" title="The Keyman Desktop Menu">The Keyman Desktop Menu</a>
      </p></li><li><p>
        <a class="xref" href="basic_hotkeys_tab.php" title="Keyman Configuration - Hotkeys Tab">Keyman Configuration - Hotkeys Tab</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="basic_charactermap.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="basic.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="basic_text_editor.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Keyman Toolbox - Character Map </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> The Keyman Desktop Text Editor</td></tr></table></div>
