<?php
  require_once('includes/template.php');

  head([
    'title' => "How To - Download and Install a Keyman Keyboard"
  ]);
?>
<div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">How To - Download and Install a Keyman Keyboard</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="start_download-install_keyman.php">Prev</a> </td><th width="60%" align="center">Chapter 2. Getting Started</th><td width="20%" align="right"> <a accesskey="n" href="start_configure_computer.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both" id="start_download-install_keyboard">How To - Download and Install a Keyman Keyboard</h2></div></div></div><p>You must have a Keyman keyboard installed to type with Keyman Desktop in your language. You can download and install a Keyman keyboard at the same time you download and install Keyman Desktop. For more information, see:  <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman Desktop">How To - Download and Install Keyman Desktop</a>.</p><p>You can also add keyboards to Keyman Desktop after you have installed Keyman Desktop. For more information, keep reading.</p><h3><a name="id558743"></a><a name="install_tav"></a>Downloading &amp; Installing a Keyman Keyboard within Keyman Desktop</h3><p>Here's how to download and install a Keyman keyboard within Keyman Desktop:</p><div class="orderedlist"><ol type="1"><li><p>Start Keyman Desktop.</p></li><li><p>Open Keyman Configuration, from the Keyman menu (on the Windows Taskbar near the clock).</p><p>
		<span class="inlinemediaobject"><img src="desktop_images/start_tray.png"></span>
	</p></li><li><p>Select the Keyboard Layouts tab.</p></li><li><p>Click <span class="guibutton">Download keyboard…</span>.</p></li><li><p>From the dropdown boxes, find a language associated with your keyboard and click <span class="guibutton">Search</span>.</p></li><li><p>Click <span class="guibutton">Install Keyboard</span> for the keyboard you want to install. </p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3><p>The icons to the right of each keyboard name show valuable information about what the keyboard includes:</p><div class="itemizedlist"><ul type="disc"><li><span class="inlinemediaobject"><img src="desktop_images/icon-unicode.png"></span> – means that the keyboard is a Unicode keyboard.</li><li><span class="inlinemediaobject"><img src="desktop_images/icon-osk.png"></span> – means the keyboard has a virtual On Screen Keyboard.</li><li><span class="inlinemediaobject"><img src="desktop_images/icon-help.png"></span> – means the keyboard contains help documentation.</li><li><span class="inlinemediaobject"><img src="desktop_images/icon-fonts.png"></span> – means the keyboard comes with fonts.</li><li><span class="inlinemediaobject"><img src="desktop_images/icon-intro.png"></span> – means the keyboard has introductory help.</li></ul></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>You may also download the keyboard without installing it. Tick 'Don't install, just download' in the Download Keyboard window.</div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p>If the keyboard you want doesn't have an <span class="guibutton">Install Keyboard</span> button, then the keyboard has been made available from a third-party site. You can download the keyboard by following the links provided. If the keyboard doesn't install automatically, follow the instructions below to <a class="link" href="start_download-install_keyboard.php#install_folder">install a keyboard from your computer</a>.</p></div></li><li><p>Click <span class="guibutton">Install</span> at the Install Keyboard or Package dialog.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>The Install Keyboard/Package dialog includes some helpful information about the keyboard you are installing. In addition to the name, encoding standard, and version of the keyboard, the dialog may also show:
	    <div class="itemizedlist"><ul type="disc"><li><p>Fonts to be installed with the keyboard.</p></li><li><p>Author name and contact information.</p></li><li><p>Specific help and readme information (under the readme tab).</p></li><li><p>Other details.</p></li></ul></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p><span class="guibutton">Install</span> installs the keyboard for anyone who can log on to your computer.  You may be prompted by User Account Control to allow Keyman to make changes to your computer -- click 'Yes'.</p></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>If a keyboard with the same name is already installed, Keyman Desktop will ask you if you want to replace the old keyboard or cancel the installation.</div></li><li><p>Click <span class="guibutton">OK</span> if asked to configure you computer to work with your new keyboard.</p></li><li><p>Click <span class="guibutton">OK</span> to save your settings and exit Keyman Configuration.</p></li></ol></div><h3><a name="id558951"></a><a name="install_folder"></a>Installing a Keyman Keyboard from a Folder on Your Computer</h3><p>There are two ways you can install a Keyman keyboard from a folder on your computer. The easiest way is to find the keyboard on your computer and double-click to install it. Keyman keyboards have a file name that ends with .KMX or .KMP.</p><p>You can also install a keyboard from your computer within Keyman Desktop. Here's how:</p><div class="orderedlist"><ol type="1"><li><p>Start Keyman</p></li><li><p>Open Keyman Configuration, from the Keyman menu in the Windows taskbar.</p><p><span class="inlinemediaobject"><img src="desktop_images/start_tray.png"></span></p></li><li><p>Select the Keyboard Layouts tab.</p></li><li><p>Click <span class="guibutton">Install keyboard…</span>.</p></li><li><p>Find and select the keyboard on your computer. </p></li><li><p>Click <span class="guibutton">Open</span>.</p></li><li><p>Click <span class="guibutton">Install</span> at the Install Keyboard or Package dialog.  You may be prompted by User Account Control to allow Keyman to make changes to your computer -- click 'Yes'.</p><div class="tip" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Tip</h3>The Install Keyboard/Package dialog includes some helpful information about the keyboard you are installing. In addition to the name, encoding standard, and version of the keyboard, the dialog may also show:
	    <div class="itemizedlist"><ul type="disc"><li><p>Fonts to be installed with the keyboard.</p></li><li><p>Author name and contact information.</p></li><li><p>Specific help and readme information (under the readme tab).</p></li><li><p>Other details.</p></li></ul></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3><p><span class="guibutton">Install</span> installs the keyboard for anyone who can log on to your computer.</p></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><h3 class="title">Note</h3>If a keyboard with the same name is already installed, Keyman Desktop will ask you if you want to replace the old keyboard or cancel the installation.</div></li><li><p>Click <span class="guibutton">OK</span> if asked to configure you computer to work with your new keyboard.</p></li><li><p>Click <span class="guibutton">OK</span> to save your settings and exit Keyman Configuration.</p></li></ol></div><h3><a name="id559098"></a>Related Topics</h3><div class="itemizedlist"><ul type="disc"><li><p>
        <a class="xref" href="start_download-install_keyman.php" title="How To - Download and Install Keyman Desktop">How To - Download and Install Keyman Desktop</a>
      </p></li><li><p>
        <a class="xref" href="basic_enable_keyboard.php" title="Keyboard Task - Turn on a Keyboard">Keyboard Task - Turn on a Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_disable_keyboard.php" title="Keyboard Task - Enable and Disable a Keyboard">Keyboard Task - Enable and Disable a Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_uninstall_keyboard.php" title="Keyboard Task - Uninstall a Keyboard">Keyboard Task - Uninstall a Keyboard</a>
      </p></li><li><p>
        <a class="xref" href="basic_keyboards_tab.php" title="Keyman Configuration - Keyboard Layouts Tab">Keyman Configuration - Keyboard Layouts Tab</a>
      </p></li><li><p>
        <a class="xref" href="basic_config_menu.php" title="Keyman Desktop Configuration">Keyman Desktop Configuration</a>
      </p></li></ul></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="start_download-install_keyman.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="start.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="start_configure_computer.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">How To - Download and Install Keyman Desktop </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> How To - Set up Your Computer for a Keyman Keyboard</td></tr></table></div>
