<?php
  require_once('includes/template.php');

  head([
    'title' => "IKeymanError Interface"
  ]);
?>

<h1>IKeymanError Interface</h1>

    <div class="toc">
      <dl>
        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Description">IKeymanError::Description</a></span></dt>

        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ErrorCode">IKeymanError::ErrorCode</a></span></dt>

        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Parameter">IKeymanError::Parameter</a></span></dt>

        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ParameterCount">IKeymanError::ParameterCount</a></span></dt>

        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ParameterValue">IKeymanError::ParameterValue</a></span></dt>

        <dt><span class="section"><a href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Severity">IKeymanError::Severity</a></span></dt>
      </dl>
    </div>

    <p>interface IKeymanError : <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanObject" title="IKeymanObject Interface">IKeymanObject</a>
    : IDispatch</p>

    <p>Returns information about a specific error received by or generated by Keyman Engine. An error is made up of a string, plus a set of
    parameters that are the information specific to the error. The parameters can be used to build a useful error message in your
    environment or translated to another language.</p>

    <h5><a name="id571033" id="id571033"></a>Interface Properties</h5>

    <table id="id571054">
      <tr>
        <th>Name</th>

        <th>Type</th>

        <th>Declaration</th>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Description" title="IKeymanError::Description">Description</a>
        </td>

        <td>Property Get</td>

        <td>Property Get Description As String</td>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ErrorCode" title="IKeymanError::ErrorCode">ErrorCode</a>
        </td>

        <td>Property Get</td>

        <td>Property Get ErrorCode As Long</td>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Parameter" title="IKeymanError::Parameter">Parameter</a>
        </td>

        <td>Property Get</td>

        <td>Property Get Parameter(Index As Long) As String</td>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ParameterCount" title="IKeymanError::ParameterCount">ParameterCount</a>
        </td>

        <td>Property Get</td>

        <td>Property Get ParameterCount As Long</td>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/ParameterValue" title="IKeymanError::ParameterValue">ParameterValue</a>
        </td>

        <td>Property Get</td>

        <td>Property Get ParameterValue(Index As Long) As String</td>
      </tr>

      <tr>
        <td>
          <a class="link" href="/developer/engine/desktop/9.0/comapi/interfaces/IKeymanError/Severity" title="IKeymanError::Severity">Severity</a>
        </td>

        <td>Property Get</td>

        <td>Property Get Severity As KeymanErrorSeverity</td>
      </tr>
    </table>
