<?php  require_once('includes/template.php');    head([    'title' => 'Keyman Support | Type to the world in your language',    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']  ]);?><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">IKeymanHotkey::Target</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="comapi_interface_IKeymanHotkey.php">Prev</a> </td><th width="60%" align="center">IKeymanHotkey Interface</th><td width="20%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanHotkey_Value.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h5 class="title"><a name="comapi_interface_IKeymanHotkey_Target"></a><a class="link" href="comapi_interface_IKeymanHotkey.php" title="IKeymanHotkey Interface">IKeymanHotkey</a>::Target</h5></div></div></div><p>
            The product-specific target value for the shortcut.  Keyman Engine defines:
              khKeymanOff = 0;
              khKeyboardMenu = 1;
              khVisualKeyboard = 2;
              khKeymanConfiguration = 3;
          </p><h6><a name="id737418"></a>Declaration</h6><pre class="programlisting">Property Get/Let Target As Long</pre><h6><a name="id737424"></a>Parameters</h6><table id="id737426"><tr><th>No</th><th>Name</th><th>Type</th><th>Description</th></tr></table><h6><a name="id737438"></a>Return Value</h6>Long<h6><a name="id737442"></a>Example Code</h6><pre class="programlisting"></pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="comapi_interface_IKeymanHotkey.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="comapi_interface_IKeymanHotkey.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="comapi_interface_IKeymanHotkey_Value.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">IKeymanHotkey Interface </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> IKeymanHotkey::Value</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
