<?php  require_once('includes/template.php');    head([    'title' => 'Keyman Support | Type to the world in your language',    'css' => ['template.css','keyboard.css','keys.css','Kmhelp.css']  ]);?><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Variable: KeymanWeb_ControlDownColor</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="reference_kmw_KeymanWeb_KeyHoverColor.php">Prev</a> </td><th width="60%" align="center">Global Variables</th><td width="20%" align="right"> <a accesskey="n" href="reference_kmw_KeymanWeb_DefaultKeyboardName.php">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h4 class="title"><a name="reference_kmw_KeymanWeb_ControlDownColor"></a>Variable: KeymanWeb_ControlDownColor</h4></div></div></div><p>
      This is an optional variable, that if set, will define the color of the shift keys on the visual keyboard when they are 'down'.
    </p><p>
      This is not handled as a css class due to bugs in Internet Explorer's CSS handling.
    </p><h5><a name="id763849"></a>Example</h5><pre class="programlisting">
KeymanWeb_ControlDownColor = 'blue';
    </pre></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="reference_kmw_KeymanWeb_KeyHoverColor.php">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="reference_kmw__variables.php">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="reference_kmw_KeymanWeb_DefaultKeyboardName.php">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Variable: KeymanWeb_KeyHoverColor </td><td width="20%" align="center"><a accesskey="h" href="index.php">Home</a></td><td width="40%" align="right" valign="top"> Variable: KeymanWeb_DefaultKeyboardName</td></tr></table></div>
  <script src="topicresponse.js" type="text/javascript"></script>
</body></html>
