name: CI

on: [pull_request]

jobs:

  build-test:
    runs-on: ubuntu-latest
    env:
      KEYMANHOSTS_TIER: TIER_TEST
      CONTAINER_DESC: help-keyman-com-app
      CONTAINER_PORT: 8055

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    # Build the docker image and create link to vendor/ dependencies
    - name: Build the Docker image
      shell: bash
      run: |
        echo "TIER_TEST" > tier.txt
        ./build.sh configure build start --debug
      env:
        fail-fast: true

    #
    # Run tests -- these step definitions are NEARLY identical across:
    #   help.keyman.com, keyman.com, keymanweb.com, api.keyman.com
    #
    # No differences on this site
    #
    - name: Test setup
      shell: bash
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_record_start_time
        echo "TEST_START_TIME=${TEST_START_TIME}" >> "$GITHUB_ENV"

    - name: PHP test
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_unit_tests "$CONTAINER_DESC"

    - name: Lint
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_lint "$CONTAINER_DESC"

    - name: Check broken links
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_links "http://localhost:${CONTAINER_PORT}" /

      # We split the reporting of broken links into a separate step for ease of
      # viewing because the broken links are otherwise hidden in a sea of good
      # links in a very long report

    - name: Report on broken links
      if: ${{ !cancelled() }}
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_print_link_report

    - name: Check PHP errors
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        source ./_common/tests.inc.sh
        set -e
        do_test_print_container_error_logs "$CONTAINER_DESC"

    - name: Verify .bootstrap-required-version
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        # We want to avoid merging a bootstrap version that is not based on a published tag
        # in the shared-sites repo. We will do this with a heuristic based on the normal
        # shape of the tags, which is `v#.#.#`. Any other shape we will assume is a test
        # branch.
        cat resources/.bootstrap-required-version | grep -qP '^v\d+\.\d+\.\d+$' || (
          echo "::error file=resources/.bootstrap-required-version,line=1,col=1::This branch cannot be merged, because resources/.bootstrap-required-version references \`$(cat resources/.bootstrap-required-version)\`, which does not appear to be a published tag -- is it a test branch?"
          exit 1
        )
