name: Prune images
on:
  workflow_run:
    workflows: [Docker-build]
    types: [completed]

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - name: prune
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: keymanapp
        container: help-keyman-com
        dry-run: false
        keep-younger-than: 7
        keep-last: 3
        prune-tags-regexes: ^.*$
        prune-untagged: true
