name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'keymanapp/help.keyman.com'
    runs-on: ubuntu-latest
    steps:
    - name: Update labels based on PR title
      id: labeler
      uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        config-path: .github/multi-labeler.yml
